/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body of the acknowledge request. The timestamp is the server's clock, so
 * only the reason travels.
 * @export
 * @interface AcknowledgeDataQualityRequest
 */
export interface AcknowledgeDataQualityRequest {
    /**
     * 
     * @type {string}
     * @memberof AcknowledgeDataQualityRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the AcknowledgeDataQualityRequest interface.
 */
export function instanceOfAcknowledgeDataQualityRequest(value: object): value is AcknowledgeDataQualityRequest {
    return true;
}

export function AcknowledgeDataQualityRequestFromJSON(json: any): AcknowledgeDataQualityRequest {
    return AcknowledgeDataQualityRequestFromJSONTyped(json, false);
}

export function AcknowledgeDataQualityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcknowledgeDataQualityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function AcknowledgeDataQualityRequestToJSON(json: any): AcknowledgeDataQualityRequest {
    return AcknowledgeDataQualityRequestToJSONTyped(json, false);
}

export function AcknowledgeDataQualityRequestToJSONTyped(value?: AcknowledgeDataQualityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'note': value['note'],
    };
}

