/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MapInfoResponse } from './MapInfoResponse';
import {
    MapInfoResponseFromJSON,
    MapInfoResponseFromJSONTyped,
    MapInfoResponseToJSON,
    MapInfoResponseToJSONTyped,
} from './MapInfoResponse';
import type { VersionInfoResponse } from './VersionInfoResponse';
import {
    VersionInfoResponseFromJSON,
    VersionInfoResponseFromJSONTyped,
    VersionInfoResponseToJSON,
    VersionInfoResponseToJSONTyped,
} from './VersionInfoResponse';
import type { GitInfoResponse } from './GitInfoResponse';
import {
    GitInfoResponseFromJSON,
    GitInfoResponseFromJSONTyped,
    GitInfoResponseToJSON,
    GitInfoResponseToJSONTyped,
} from './GitInfoResponse';

/**
 * 
 * @export
 * @interface AppInfoResponse
 */
export interface AppInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof AppInfoResponse
     */
    buildTime: string;
    /**
     * 
     * @type {GitInfoResponse}
     * @memberof AppInfoResponse
     */
    git: GitInfoResponse;
    /**
     * 
     * @type {MapInfoResponse}
     * @memberof AppInfoResponse
     */
    map: MapInfoResponse;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResponse
     */
    rustChannel: string;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResponse
     */
    rustEdition: string;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResponse
     */
    rustVersion: string;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResponse
     */
    version: string;
    /**
     * 
     * @type {VersionInfoResponse}
     * @memberof AppInfoResponse
     */
    versionInfo: VersionInfoResponse;
}

/**
 * Check if a given object implements the AppInfoResponse interface.
 */
export function instanceOfAppInfoResponse(value: object): value is AppInfoResponse {
    if (!('buildTime' in value) || value['buildTime'] === undefined) return false;
    if (!('git' in value) || value['git'] === undefined) return false;
    if (!('map' in value) || value['map'] === undefined) return false;
    if (!('rustChannel' in value) || value['rustChannel'] === undefined) return false;
    if (!('rustEdition' in value) || value['rustEdition'] === undefined) return false;
    if (!('rustVersion' in value) || value['rustVersion'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('versionInfo' in value) || value['versionInfo'] === undefined) return false;
    return true;
}

export function AppInfoResponseFromJSON(json: any): AppInfoResponse {
    return AppInfoResponseFromJSONTyped(json, false);
}

export function AppInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'buildTime': json['buildTime'],
        'git': GitInfoResponseFromJSON(json['git']),
        'map': MapInfoResponseFromJSON(json['map']),
        'rustChannel': json['rustChannel'],
        'rustEdition': json['rustEdition'],
        'rustVersion': json['rustVersion'],
        'version': json['version'],
        'versionInfo': VersionInfoResponseFromJSON(json['versionInfo']),
    };
}

export function AppInfoResponseToJSON(json: any): AppInfoResponse {
    return AppInfoResponseToJSONTyped(json, false);
}

export function AppInfoResponseToJSONTyped(value?: AppInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buildTime': value['buildTime'],
        'git': GitInfoResponseToJSON(value['git']),
        'map': MapInfoResponseToJSON(value['map']),
        'rustChannel': value['rustChannel'],
        'rustEdition': value['rustEdition'],
        'rustVersion': value['rustVersion'],
        'version': value['version'],
        'versionInfo': VersionInfoResponseToJSON(value['versionInfo']),
    };
}

