/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WateringStatus } from './WateringStatus';
import {
    WateringStatusFromJSON,
    WateringStatusFromJSONTyped,
    WateringStatusToJSON,
    WateringStatusToJSONTyped,
} from './WateringStatus';

/**
 * 
 * @export
 * @interface ClusterBoundaryResponse
 */
export interface ClusterBoundaryResponse {
    /**
     * GeoJSON polygon (convex hull of the cluster's trees, buffered in meters).
     * @type {object}
     * @memberof ClusterBoundaryResponse
     */
    boundary: object;
    /**
     * 
     * @type {string}
     * @memberof ClusterBoundaryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ClusterBoundaryResponse
     */
    name: string;
    /**
     * 
     * @type {WateringStatus}
     * @memberof ClusterBoundaryResponse
     */
    wateringStatus: WateringStatus;
}



/**
 * Check if a given object implements the ClusterBoundaryResponse interface.
 */
export function instanceOfClusterBoundaryResponse(value: object): value is ClusterBoundaryResponse {
    if (!('boundary' in value) || value['boundary'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('wateringStatus' in value) || value['wateringStatus'] === undefined) return false;
    return true;
}

export function ClusterBoundaryResponseFromJSON(json: any): ClusterBoundaryResponse {
    return ClusterBoundaryResponseFromJSONTyped(json, false);
}

export function ClusterBoundaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterBoundaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'boundary': json['boundary'],
        'id': json['id'],
        'name': json['name'],
        'wateringStatus': WateringStatusFromJSON(json['watering_status']),
    };
}

export function ClusterBoundaryResponseToJSON(json: any): ClusterBoundaryResponse {
    return ClusterBoundaryResponseToJSONTyped(json, false);
}

export function ClusterBoundaryResponseToJSONTyped(value?: ClusterBoundaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boundary': value['boundary'],
        'id': value['id'],
        'name': value['name'],
        'watering_status': WateringStatusToJSON(value['wateringStatus']),
    };
}

