/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterBoundaryResponse } from './ClusterBoundaryResponse';
import {
    ClusterBoundaryResponseFromJSON,
    ClusterBoundaryResponseFromJSONTyped,
    ClusterBoundaryResponseToJSON,
    ClusterBoundaryResponseToJSONTyped,
} from './ClusterBoundaryResponse';

/**
 * 
 * @export
 * @interface ClusterBoundaryListResponse
 */
export interface ClusterBoundaryListResponse {
    /**
     * 
     * @type {Array<ClusterBoundaryResponse>}
     * @memberof ClusterBoundaryListResponse
     */
    data: Array<ClusterBoundaryResponse>;
}

/**
 * Check if a given object implements the ClusterBoundaryListResponse interface.
 */
export function instanceOfClusterBoundaryListResponse(value: object): value is ClusterBoundaryListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ClusterBoundaryListResponseFromJSON(json: any): ClusterBoundaryListResponse {
    return ClusterBoundaryListResponseFromJSONTyped(json, false);
}

export function ClusterBoundaryListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterBoundaryListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ClusterBoundaryResponseFromJSON)),
    };
}

export function ClusterBoundaryListResponseToJSON(json: any): ClusterBoundaryListResponse {
    return ClusterBoundaryListResponseToJSONTyped(json, false);
}

export function ClusterBoundaryListResponseToJSONTyped(value?: ClusterBoundaryListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ClusterBoundaryResponseToJSON)),
    };
}

