/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single comment on a tree cluster or a watering plan.
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    authorId: string;
    /**
     * Display name of the author; absent if the account no longer resolves.
     * @type {string}
     * @memberof CommentResponse
     */
    authorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    createdAt: string;
    /**
     * Present once the author has edited the comment.
     * @type {string}
     * @memberof CommentResponse
     */
    editedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CommentResponse interface.
 */
export function instanceOfCommentResponse(value: object): value is CommentResponse {
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CommentResponseFromJSON(json: any): CommentResponse {
    return CommentResponseFromJSONTyped(json, false);
}

export function CommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authorId': json['author_id'],
        'authorName': json['author_name'] == null ? undefined : json['author_name'],
        'body': json['body'],
        'createdAt': json['created_at'],
        'editedAt': json['edited_at'] == null ? undefined : json['edited_at'],
        'id': json['id'],
    };
}

export function CommentResponseToJSON(json: any): CommentResponse {
    return CommentResponseToJSONTyped(json, false);
}

export function CommentResponseToJSONTyped(value?: CommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author_id': value['authorId'],
        'author_name': value['authorName'],
        'body': value['body'],
        'created_at': value['createdAt'],
        'edited_at': value['editedAt'],
        'id': value['id'],
    };
}

