/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whether a sensor's recent readings look trustworthy.
 * @export
 */
export const DataHealth = {
    Ok: 'ok',
    Suspect: 'suspect'
} as const;
export type DataHealth = typeof DataHealth[keyof typeof DataHealth];


export function instanceOfDataHealth(value: any): boolean {
    for (const key in DataHealth) {
        if (Object.prototype.hasOwnProperty.call(DataHealth, key)) {
            if (DataHealth[key as keyof typeof DataHealth] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataHealthFromJSON(json: any): DataHealth {
    return DataHealthFromJSONTyped(json, false);
}

export function DataHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataHealth {
    return json as DataHealth;
}

export function DataHealthToJSON(value?: DataHealth | null): any {
    return value as any;
}

export function DataHealthToJSONTyped(value: any, ignoreDiscriminator: boolean): DataHealth {
    return value as DataHealth;
}

