/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataStatisticsResponse
 */
export interface DataStatisticsResponse {
    /**
     * 
     * @type {number}
     * @memberof DataStatisticsResponse
     */
    sensorCount: number;
    /**
     * 
     * @type {number}
     * @memberof DataStatisticsResponse
     */
    treeClusterCount: number;
    /**
     * 
     * @type {number}
     * @memberof DataStatisticsResponse
     */
    treeCount: number;
    /**
     * 
     * @type {number}
     * @memberof DataStatisticsResponse
     */
    vehicleCount: number;
    /**
     * 
     * @type {number}
     * @memberof DataStatisticsResponse
     */
    wateringPlanCount: number;
}

/**
 * Check if a given object implements the DataStatisticsResponse interface.
 */
export function instanceOfDataStatisticsResponse(value: object): value is DataStatisticsResponse {
    if (!('sensorCount' in value) || value['sensorCount'] === undefined) return false;
    if (!('treeClusterCount' in value) || value['treeClusterCount'] === undefined) return false;
    if (!('treeCount' in value) || value['treeCount'] === undefined) return false;
    if (!('vehicleCount' in value) || value['vehicleCount'] === undefined) return false;
    if (!('wateringPlanCount' in value) || value['wateringPlanCount'] === undefined) return false;
    return true;
}

export function DataStatisticsResponseFromJSON(json: any): DataStatisticsResponse {
    return DataStatisticsResponseFromJSONTyped(json, false);
}

export function DataStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataStatisticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sensorCount': json['sensorCount'],
        'treeClusterCount': json['treeClusterCount'],
        'treeCount': json['treeCount'],
        'vehicleCount': json['vehicleCount'],
        'wateringPlanCount': json['wateringPlanCount'],
    };
}

export function DataStatisticsResponseToJSON(json: any): DataStatisticsResponse {
    return DataStatisticsResponseToJSONTyped(json, false);
}

export function DataStatisticsResponseToJSONTyped(value?: DataStatisticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sensorCount': value['sensorCount'],
        'treeClusterCount': value['treeClusterCount'],
        'treeCount': value['treeCount'],
        'vehicleCount': value['vehicleCount'],
        'wateringPlanCount': value['wateringPlanCount'],
    };
}

