/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Evaluation result for a single tree cluster within a watering plan.
 * @export
 * @interface EvaluationValueResponse
 */
export interface EvaluationValueResponse {
    /**
     * Amount of water consumed for this cluster in liters.
     * @type {number}
     * @memberof EvaluationValueResponse
     */
    consumedWater: number;
    /**
     * Identifier of the tree cluster that was evaluated.
     * @type {string}
     * @memberof EvaluationValueResponse
     */
    treeClusterId: string;
    /**
     * Identifier of the watering plan this evaluation belongs to.
     * @type {string}
     * @memberof EvaluationValueResponse
     */
    wateringPlanId: string;
}

/**
 * Check if a given object implements the EvaluationValueResponse interface.
 */
export function instanceOfEvaluationValueResponse(value: object): value is EvaluationValueResponse {
    if (!('consumedWater' in value) || value['consumedWater'] === undefined) return false;
    if (!('treeClusterId' in value) || value['treeClusterId'] === undefined) return false;
    if (!('wateringPlanId' in value) || value['wateringPlanId'] === undefined) return false;
    return true;
}

export function EvaluationValueResponseFromJSON(json: any): EvaluationValueResponse {
    return EvaluationValueResponseFromJSONTyped(json, false);
}

export function EvaluationValueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationValueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'consumedWater': json['consumed_water'],
        'treeClusterId': json['tree_cluster_id'],
        'wateringPlanId': json['watering_plan_id'],
    };
}

export function EvaluationValueResponseToJSON(json: any): EvaluationValueResponse {
    return EvaluationValueResponseToJSONTyped(json, false);
}

export function EvaluationValueResponseToJSONTyped(value?: EvaluationValueResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consumed_water': value['consumedWater'],
        'tree_cluster_id': value['treeClusterId'],
        'watering_plan_id': value['wateringPlanId'],
    };
}

