/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Evaluation input for a single tree cluster within a watering plan.
 * @export
 * @interface EvaluationValueRequest
 */
export interface EvaluationValueRequest {
    /**
     * Amount of water consumed for this cluster in liters.
     * @type {number}
     * @memberof EvaluationValueRequest
     */
    consumedWater: number;
    /**
     * Identifier of the tree cluster that was evaluated.
     * @type {string}
     * @memberof EvaluationValueRequest
     */
    treeClusterId: string;
    /**
     * Identifier of the watering plan this evaluation belongs to.
     * @type {string}
     * @memberof EvaluationValueRequest
     */
    wateringPlanId: string;
}

/**
 * Check if a given object implements the EvaluationValueRequest interface.
 */
export function instanceOfEvaluationValueRequest(value: object): value is EvaluationValueRequest {
    if (!('consumedWater' in value) || value['consumedWater'] === undefined) return false;
    if (!('treeClusterId' in value) || value['treeClusterId'] === undefined) return false;
    if (!('wateringPlanId' in value) || value['wateringPlanId'] === undefined) return false;
    return true;
}

export function EvaluationValueRequestFromJSON(json: any): EvaluationValueRequest {
    return EvaluationValueRequestFromJSONTyped(json, false);
}

export function EvaluationValueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationValueRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'consumedWater': json['consumed_water'],
        'treeClusterId': json['tree_cluster_id'],
        'wateringPlanId': json['watering_plan_id'],
    };
}

export function EvaluationValueRequestToJSON(json: any): EvaluationValueRequest {
    return EvaluationValueRequestToJSONTyped(json, false);
}

export function EvaluationValueRequestToJSONTyped(value?: EvaluationValueRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consumed_water': value['consumedWater'],
        'tree_cluster_id': value['treeClusterId'],
        'watering_plan_id': value['wateringPlanId'],
    };
}

