/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitInfoResponse
 */
export interface GitInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof GitInfoResponse
     */
    branch: string;
    /**
     * 
     * @type {string}
     * @memberof GitInfoResponse
     */
    commit: string;
    /**
     * 
     * @type {string}
     * @memberof GitInfoResponse
     */
    repository: string;
}

/**
 * Check if a given object implements the GitInfoResponse interface.
 */
export function instanceOfGitInfoResponse(value: object): value is GitInfoResponse {
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('commit' in value) || value['commit'] === undefined) return false;
    if (!('repository' in value) || value['repository'] === undefined) return false;
    return true;
}

export function GitInfoResponseFromJSON(json: any): GitInfoResponse {
    return GitInfoResponseFromJSONTyped(json, false);
}

export function GitInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'],
        'commit': json['commit'],
        'repository': json['repository'],
    };
}

export function GitInfoResponseToJSON(json: any): GitInfoResponse {
    return GitInfoResponseToJSONTyped(json, false);
}

export function GitInfoResponseToJSONTyped(value?: GitInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'commit': value['commit'],
        'repository': value['repository'],
    };
}

