/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngestResultResponse } from './IngestResultResponse';
import {
    IngestResultResponseFromJSON,
    IngestResultResponseFromJSONTyped,
    IngestResultResponseToJSON,
    IngestResultResponseToJSONTyped,
} from './IngestResultResponse';
import type { IngestSummaryResponse } from './IngestSummaryResponse';
import {
    IngestSummaryResponseFromJSON,
    IngestSummaryResponseFromJSONTyped,
    IngestSummaryResponseToJSON,
    IngestSummaryResponseToJSONTyped,
} from './IngestSummaryResponse';

/**
 * 
 * @export
 * @interface IngestBatchResponse
 */
export interface IngestBatchResponse {
    /**
     * 
     * @type {Array<IngestResultResponse>}
     * @memberof IngestBatchResponse
     */
    results: Array<IngestResultResponse>;
    /**
     * 
     * @type {IngestSummaryResponse}
     * @memberof IngestBatchResponse
     */
    summary: IngestSummaryResponse;
}

/**
 * Check if a given object implements the IngestBatchResponse interface.
 */
export function instanceOfIngestBatchResponse(value: object): value is IngestBatchResponse {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function IngestBatchResponseFromJSON(json: any): IngestBatchResponse {
    return IngestBatchResponseFromJSONTyped(json, false);
}

export function IngestBatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestBatchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(IngestResultResponseFromJSON)),
        'summary': IngestSummaryResponseFromJSON(json['summary']),
    };
}

export function IngestBatchResponseToJSON(json: any): IngestBatchResponse {
    return IngestBatchResponseToJSONTyped(json, false);
}

export function IngestBatchResponseToJSONTyped(value?: IngestBatchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(IngestResultResponseToJSON)),
        'summary': IngestSummaryResponseToJSON(value['summary']),
    };
}

