/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Per-status counts across a batch, so a caller need not tally `results`
 * itself.
 * @export
 * @interface IngestSummaryResponse
 */
export interface IngestSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof IngestSummaryResponse
     */
    created: number;
    /**
     * 
     * @type {number}
     * @memberof IngestSummaryResponse
     */
    failed: number;
    /**
     * 
     * @type {number}
     * @memberof IngestSummaryResponse
     */
    unchanged: number;
    /**
     * 
     * @type {number}
     * @memberof IngestSummaryResponse
     */
    updated: number;
}

/**
 * Check if a given object implements the IngestSummaryResponse interface.
 */
export function instanceOfIngestSummaryResponse(value: object): value is IngestSummaryResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('unchanged' in value) || value['unchanged'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function IngestSummaryResponseFromJSON(json: any): IngestSummaryResponse {
    return IngestSummaryResponseFromJSONTyped(json, false);
}

export function IngestSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'failed': json['failed'],
        'unchanged': json['unchanged'],
        'updated': json['updated'],
    };
}

export function IngestSummaryResponseToJSON(json: any): IngestSummaryResponse {
    return IngestSummaryResponseToJSONTyped(json, false);
}

export function IngestSummaryResponseToJSONTyped(value?: IngestSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'failed': value['failed'],
        'unchanged': value['unchanged'],
        'updated': value['updated'],
    };
}

