/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignalResponse } from './SignalResponse';
import {
    SignalResponseFromJSON,
    SignalResponseFromJSONTyped,
    SignalResponseToJSON,
    SignalResponseToJSONTyped,
} from './SignalResponse';

/**
 * A single data payload received from a LoRaWAN sensor.
 * @export
 * @interface ListResponseSensorDataResponseDataInner
 */
export interface ListResponseSensorDataResponseDataInner {
    /**
     * Timestamp when the data was first recorded (RFC 3339).
     * @type {string}
     * @memberof ListResponseSensorDataResponseDataInner
     */
    createdAt: string;
    /**
     * Raw sensor payload as a JSON object (structure depends on the sensor type).
     * @type {object}
     * @memberof ListResponseSensorDataResponseDataInner
     */
    data: object;
    /**
     * Unique identifier of the reading.
     * @type {string}
     * @memberof ListResponseSensorDataResponseDataInner
     */
    id: string;
    /**
     * LoRaWAN radio quality of the strongest gateway for this reading, if present.
     * @type {SignalResponse}
     * @memberof ListResponseSensorDataResponseDataInner
     */
    signal?: SignalResponse | null;
    /**
     * Timestamp when the data was last modified (RFC 3339).
     * @type {string}
     * @memberof ListResponseSensorDataResponseDataInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the ListResponseSensorDataResponseDataInner interface.
 */
export function instanceOfListResponseSensorDataResponseDataInner(value: object): value is ListResponseSensorDataResponseDataInner {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ListResponseSensorDataResponseDataInnerFromJSON(json: any): ListResponseSensorDataResponseDataInner {
    return ListResponseSensorDataResponseDataInnerFromJSONTyped(json, false);
}

export function ListResponseSensorDataResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseSensorDataResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'data': json['data'],
        'id': json['id'],
        'signal': json['signal'] == null ? undefined : SignalResponseFromJSON(json['signal']),
        'updatedAt': json['updated_at'],
    };
}

export function ListResponseSensorDataResponseDataInnerToJSON(json: any): ListResponseSensorDataResponseDataInner {
    return ListResponseSensorDataResponseDataInnerToJSONTyped(json, false);
}

export function ListResponseSensorDataResponseDataInnerToJSONTyped(value?: ListResponseSensorDataResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'data': value['data'],
        'id': value['id'],
        'signal': SignalResponseToJSON(value['signal']),
        'updated_at': value['updatedAt'],
    };
}

