/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListResponseTreeResponseDataInner } from './ListResponseTreeResponseDataInner';
import {
    ListResponseTreeResponseDataInnerFromJSON,
    ListResponseTreeResponseDataInnerFromJSONTyped,
    ListResponseTreeResponseDataInnerToJSON,
    ListResponseTreeResponseDataInnerToJSONTyped,
} from './ListResponseTreeResponseDataInner';
import type { PaginationResponse } from './PaginationResponse';
import {
    PaginationResponseFromJSON,
    PaginationResponseFromJSONTyped,
    PaginationResponseToJSON,
    PaginationResponseToJSONTyped,
} from './PaginationResponse';

/**
 * 
 * @export
 * @interface ListResponseTreeResponse
 */
export interface ListResponseTreeResponse {
    /**
     * 
     * @type {Array<ListResponseTreeResponseDataInner>}
     * @memberof ListResponseTreeResponse
     */
    data: Array<ListResponseTreeResponseDataInner>;
    /**
     * 
     * @type {PaginationResponse}
     * @memberof ListResponseTreeResponse
     */
    pagination: PaginationResponse;
}

/**
 * Check if a given object implements the ListResponseTreeResponse interface.
 */
export function instanceOfListResponseTreeResponse(value: object): value is ListResponseTreeResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListResponseTreeResponseFromJSON(json: any): ListResponseTreeResponse {
    return ListResponseTreeResponseFromJSONTyped(json, false);
}

export function ListResponseTreeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseTreeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ListResponseTreeResponseDataInnerFromJSON)),
        'pagination': PaginationResponseFromJSON(json['pagination']),
    };
}

export function ListResponseTreeResponseToJSON(json: any): ListResponseTreeResponse {
    return ListResponseTreeResponseToJSONTyped(json, false);
}

export function ListResponseTreeResponseToJSONTyped(value?: ListResponseTreeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ListResponseTreeResponseDataInnerToJSON)),
        'pagination': PaginationResponseToJSON(value['pagination']),
    };
}

