/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListResponseUserResponseDataInner } from './ListResponseUserResponseDataInner';
import {
    ListResponseUserResponseDataInnerFromJSON,
    ListResponseUserResponseDataInnerFromJSONTyped,
    ListResponseUserResponseDataInnerToJSON,
    ListResponseUserResponseDataInnerToJSONTyped,
} from './ListResponseUserResponseDataInner';
import type { PaginationResponse } from './PaginationResponse';
import {
    PaginationResponseFromJSON,
    PaginationResponseFromJSONTyped,
    PaginationResponseToJSON,
    PaginationResponseToJSONTyped,
} from './PaginationResponse';

/**
 * 
 * @export
 * @interface ListResponseUserResponse
 */
export interface ListResponseUserResponse {
    /**
     * 
     * @type {Array<ListResponseUserResponseDataInner>}
     * @memberof ListResponseUserResponse
     */
    data: Array<ListResponseUserResponseDataInner>;
    /**
     * 
     * @type {PaginationResponse}
     * @memberof ListResponseUserResponse
     */
    pagination: PaginationResponse;
}

/**
 * Check if a given object implements the ListResponseUserResponse interface.
 */
export function instanceOfListResponseUserResponse(value: object): value is ListResponseUserResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListResponseUserResponseFromJSON(json: any): ListResponseUserResponse {
    return ListResponseUserResponseFromJSONTyped(json, false);
}

export function ListResponseUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ListResponseUserResponseDataInnerFromJSON)),
        'pagination': PaginationResponseFromJSON(json['pagination']),
    };
}

export function ListResponseUserResponseToJSON(json: any): ListResponseUserResponse {
    return ListResponseUserResponseToJSONTyped(json, false);
}

export function ListResponseUserResponseToJSONTyped(value?: ListResponseUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ListResponseUserResponseDataInnerToJSON)),
        'pagination': PaginationResponseToJSON(value['pagination']),
    };
}

