/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationResponse } from './PaginationResponse';
import {
    PaginationResponseFromJSON,
    PaginationResponseFromJSONTyped,
    PaginationResponseToJSON,
    PaginationResponseToJSONTyped,
} from './PaginationResponse';
import type { ListResponseCommentResponseDataInner } from './ListResponseCommentResponseDataInner';
import {
    ListResponseCommentResponseDataInnerFromJSON,
    ListResponseCommentResponseDataInnerFromJSONTyped,
    ListResponseCommentResponseDataInnerToJSON,
    ListResponseCommentResponseDataInnerToJSONTyped,
} from './ListResponseCommentResponseDataInner';

/**
 * 
 * @export
 * @interface ListResponseCommentResponse
 */
export interface ListResponseCommentResponse {
    /**
     * 
     * @type {Array<ListResponseCommentResponseDataInner>}
     * @memberof ListResponseCommentResponse
     */
    data: Array<ListResponseCommentResponseDataInner>;
    /**
     * 
     * @type {PaginationResponse}
     * @memberof ListResponseCommentResponse
     */
    pagination: PaginationResponse;
}

/**
 * Check if a given object implements the ListResponseCommentResponse interface.
 */
export function instanceOfListResponseCommentResponse(value: object): value is ListResponseCommentResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ListResponseCommentResponseFromJSON(json: any): ListResponseCommentResponse {
    return ListResponseCommentResponseFromJSONTyped(json, false);
}

export function ListResponseCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ListResponseCommentResponseDataInnerFromJSON)),
        'pagination': PaginationResponseFromJSON(json['pagination']),
    };
}

export function ListResponseCommentResponseToJSON(json: any): ListResponseCommentResponse {
    return ListResponseCommentResponseToJSONTyped(json, false);
}

export function ListResponseCommentResponseToJSONTyped(value?: ListResponseCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ListResponseCommentResponseDataInnerToJSON)),
        'pagination': PaginationResponseToJSON(value['pagination']),
    };
}

