/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LoRaWAN connection details exposed publicly. The `config` map is filtered
 * via [`redact_lorawan_config`] to strip OTAA / session keys and the device
 * password before serialization.
 * @export
 * @interface LorawanInfoResponse
 */
export interface LorawanInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof LorawanInfoResponse
     */
    appEui: string;
    /**
     * 
     * @type {string}
     * @memberof LorawanInfoResponse
     */
    atPin?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LorawanInfoResponse
     */
    config?: object | null;
    /**
     * 
     * @type {string}
     * @memberof LorawanInfoResponse
     */
    devEui: string;
    /**
     * 
     * @type {string}
     * @memberof LorawanInfoResponse
     */
    otaPin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LorawanInfoResponse
     */
    serialNumber: string;
}

/**
 * Check if a given object implements the LorawanInfoResponse interface.
 */
export function instanceOfLorawanInfoResponse(value: object): value is LorawanInfoResponse {
    if (!('appEui' in value) || value['appEui'] === undefined) return false;
    if (!('devEui' in value) || value['devEui'] === undefined) return false;
    if (!('serialNumber' in value) || value['serialNumber'] === undefined) return false;
    return true;
}

export function LorawanInfoResponseFromJSON(json: any): LorawanInfoResponse {
    return LorawanInfoResponseFromJSONTyped(json, false);
}

export function LorawanInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LorawanInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appEui': json['app_eui'],
        'atPin': json['at_pin'] == null ? undefined : json['at_pin'],
        'config': json['config'] == null ? undefined : json['config'],
        'devEui': json['dev_eui'],
        'otaPin': json['ota_pin'] == null ? undefined : json['ota_pin'],
        'serialNumber': json['serial_number'],
    };
}

export function LorawanInfoResponseToJSON(json: any): LorawanInfoResponse {
    return LorawanInfoResponseToJSONTyped(json, false);
}

export function LorawanInfoResponseToJSONTyped(value?: LorawanInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_eui': value['appEui'],
        'at_pin': value['atPin'],
        'config': value['config'],
        'dev_eui': value['devEui'],
        'ota_pin': value['otaPin'],
        'serial_number': value['serialNumber'],
    };
}

