/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LoRaWAN credentials supplied when registering a new sensor. `app_key` is
 * write-only and never echoed back in responses.
 * @export
 * @interface LorawanCredentialsRequest
 */
export interface LorawanCredentialsRequest {
    /**
     * 
     * @type {string}
     * @memberof LorawanCredentialsRequest
     */
    appEui: string;
    /**
     * 
     * @type {string}
     * @memberof LorawanCredentialsRequest
     */
    appKey: string;
    /**
     * 
     * @type {string}
     * @memberof LorawanCredentialsRequest
     */
    atPin?: string | null;
    /**
     * 
     * @type {object}
     * @memberof LorawanCredentialsRequest
     */
    config?: object | null;
    /**
     * 
     * @type {string}
     * @memberof LorawanCredentialsRequest
     */
    devEui: string;
    /**
     * 
     * @type {string}
     * @memberof LorawanCredentialsRequest
     */
    otaPin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LorawanCredentialsRequest
     */
    serialNumber: string;
}

/**
 * Check if a given object implements the LorawanCredentialsRequest interface.
 */
export function instanceOfLorawanCredentialsRequest(value: object): value is LorawanCredentialsRequest {
    if (!('appEui' in value) || value['appEui'] === undefined) return false;
    if (!('appKey' in value) || value['appKey'] === undefined) return false;
    if (!('devEui' in value) || value['devEui'] === undefined) return false;
    if (!('serialNumber' in value) || value['serialNumber'] === undefined) return false;
    return true;
}

export function LorawanCredentialsRequestFromJSON(json: any): LorawanCredentialsRequest {
    return LorawanCredentialsRequestFromJSONTyped(json, false);
}

export function LorawanCredentialsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LorawanCredentialsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appEui': json['app_eui'],
        'appKey': json['app_key'],
        'atPin': json['at_pin'] == null ? undefined : json['at_pin'],
        'config': json['config'] == null ? undefined : json['config'],
        'devEui': json['dev_eui'],
        'otaPin': json['ota_pin'] == null ? undefined : json['ota_pin'],
        'serialNumber': json['serial_number'],
    };
}

export function LorawanCredentialsRequestToJSON(json: any): LorawanCredentialsRequest {
    return LorawanCredentialsRequestToJSONTyped(json, false);
}

export function LorawanCredentialsRequestToJSONTyped(value?: LorawanCredentialsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_eui': value['appEui'],
        'app_key': value['appKey'],
        'at_pin': value['atPin'],
        'config': value['config'],
        'dev_eui': value['devEui'],
        'ota_pin': value['otaPin'],
        'serial_number': value['serialNumber'],
    };
}

