/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapInfoResponse
 */
export interface MapInfoResponse {
    /**
     * 
     * @type {Array<number>}
     * @memberof MapInfoResponse
     */
    bbox: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof MapInfoResponse
     */
    center: Array<number>;
}

/**
 * Check if a given object implements the MapInfoResponse interface.
 */
export function instanceOfMapInfoResponse(value: object): value is MapInfoResponse {
    if (!('bbox' in value) || value['bbox'] === undefined) return false;
    if (!('center' in value) || value['center'] === undefined) return false;
    return true;
}

export function MapInfoResponseFromJSON(json: any): MapInfoResponse {
    return MapInfoResponseFromJSONTyped(json, false);
}

export function MapInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'],
        'center': json['center'],
    };
}

export function MapInfoResponseToJSON(json: any): MapInfoResponse {
    return MapInfoResponseToJSONTyped(json, false);
}

export function MapInfoResponseToJSONTyped(value?: MapInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': value['bbox'],
        'center': value['center'],
    };
}

