/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDto } from './AddressDto';
import {
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    AddressDtoToJSONTyped,
} from './AddressDto';

/**
 * Request body for updating an organization. Replaces the whole editable set —
 * an omitted field clears the stored value.
 * @export
 * @interface OrganizationUpdateRequest
 */
export interface OrganizationUpdateRequest {
    /**
     * 
     * @type {AddressDto}
     * @memberof OrganizationUpdateRequest
     */
    address?: AddressDto | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateRequest
     */
    contactPersonId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the OrganizationUpdateRequest interface.
 */
export function instanceOfOrganizationUpdateRequest(value: object): value is OrganizationUpdateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationUpdateRequestFromJSON(json: any): OrganizationUpdateRequest {
    return OrganizationUpdateRequestFromJSONTyped(json, false);
}

export function OrganizationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : AddressDtoFromJSON(json['address']),
        'contactPersonId': json['contact_person_id'] == null ? undefined : json['contact_person_id'],
        'name': json['name'],
    };
}

export function OrganizationUpdateRequestToJSON(json: any): OrganizationUpdateRequest {
    return OrganizationUpdateRequestToJSONTyped(json, false);
}

export function OrganizationUpdateRequestToJSONTyped(value?: OrganizationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': AddressDtoToJSON(value['address']),
        'contact_person_id': value['contactPersonId'],
        'name': value['name'],
    };
}

