/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDto } from './AddressDto';
import {
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    AddressDtoToJSONTyped,
} from './AddressDto';

/**
 * A node in the organization tree.
 * @export
 * @interface OrganizationResponse
 */
export interface OrganizationResponse {
    /**
     * Postal address; null when the organization has none.
     * @type {AddressDto}
     * @memberof OrganizationResponse
     */
    address?: AddressDto | null;
    /**
     * Contact person id; resolve via the detail endpoint for name and email.
     * @type {string}
     * @memberof OrganizationResponse
     */
    contactPersonId?: string | null;
    /**
     * Creation time derived from the UUID v7 id (null for seeded ids without a real timestamp).
     * @type {string}
     * @memberof OrganizationResponse
     */
    createdAt?: string | null;
    /**
     * Unique organization identifier (UUID v7).
     * @type {string}
     * @memberof OrganizationResponse
     */
    id: string;
    /**
     * Directly assigned users, excluding sub-organizations.
     * @type {number}
     * @memberof OrganizationResponse
     */
    memberCount: number;
    /**
     * Display name, unique among siblings.
     * @type {string}
     * @memberof OrganizationResponse
     */
    name: string;
    /**
     * Parent organization; null only for the single root.
     * @type {string}
     * @memberof OrganizationResponse
     */
    parentId?: string | null;
}

/**
 * Check if a given object implements the OrganizationResponse interface.
 */
export function instanceOfOrganizationResponse(value: object): value is OrganizationResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationResponseFromJSON(json: any): OrganizationResponse {
    return OrganizationResponseFromJSONTyped(json, false);
}

export function OrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : AddressDtoFromJSON(json['address']),
        'contactPersonId': json['contact_person_id'] == null ? undefined : json['contact_person_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'],
        'memberCount': json['member_count'],
        'name': json['name'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function OrganizationResponseToJSON(json: any): OrganizationResponse {
    return OrganizationResponseToJSONTyped(json, false);
}

export function OrganizationResponseToJSONTyped(value?: OrganizationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': AddressDtoToJSON(value['address']),
        'contact_person_id': value['contactPersonId'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'member_count': value['memberCount'],
        'name': value['name'],
        'parent_id': value['parentId'],
    };
}

