/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination metadata returned in list responses.
 * @export
 * @interface PaginationResponse
 */
export interface PaginationResponse {
    /**
     * Current page number (1-based).
     * @type {number}
     * @memberof PaginationResponse
     */
    currentPage: number;
    /**
     * Next page number, if available.
     * @type {number}
     * @memberof PaginationResponse
     */
    nextPage?: number | null;
    /**
     * Page size used for this response.
     * @type {number}
     * @memberof PaginationResponse
     */
    perPage: number;
    /**
     * Previous page number, if available.
     * @type {number}
     * @memberof PaginationResponse
     */
    prevPage?: number | null;
    /**
     * Total number of pages available.
     * @type {number}
     * @memberof PaginationResponse
     */
    totalPages: number;
    /**
     * Total number of records matching the query.
     * @type {number}
     * @memberof PaginationResponse
     */
    totalRecords: number;
}

/**
 * Check if a given object implements the PaginationResponse interface.
 */
export function instanceOfPaginationResponse(value: object): value is PaginationResponse {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalRecords' in value) || value['totalRecords'] === undefined) return false;
    return true;
}

export function PaginationResponseFromJSON(json: any): PaginationResponse {
    return PaginationResponseFromJSONTyped(json, false);
}

export function PaginationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'],
        'nextPage': json['next_page'] == null ? undefined : json['next_page'],
        'perPage': json['per_page'],
        'prevPage': json['prev_page'] == null ? undefined : json['prev_page'],
        'totalPages': json['total_pages'],
        'totalRecords': json['total_records'],
    };
}

export function PaginationResponseToJSON(json: any): PaginationResponse {
    return PaginationResponseToJSONTyped(json, false);
}

export function PaginationResponseToJSONTyped(value?: PaginationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'next_page': value['nextPage'],
        'per_page': value['perPage'],
        'prev_page': value['prevPage'],
        'total_pages': value['totalPages'],
        'total_records': value['totalRecords'],
    };
}

