/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginFrontendDtoOneOf1
 */
export interface PluginFrontendDtoOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof PluginFrontendDtoOneOf1
     */
    mode: PluginFrontendDtoOneOf1ModeEnum;
    /**
     * 
     * @type {string}
     * @memberof PluginFrontendDtoOneOf1
     */
    target: string;
}


/**
 * @export
 */
export const PluginFrontendDtoOneOf1ModeEnum = {
    Proxied: 'proxied'
} as const;
export type PluginFrontendDtoOneOf1ModeEnum = typeof PluginFrontendDtoOneOf1ModeEnum[keyof typeof PluginFrontendDtoOneOf1ModeEnum];


/**
 * Check if a given object implements the PluginFrontendDtoOneOf1 interface.
 */
export function instanceOfPluginFrontendDtoOneOf1(value: object): value is PluginFrontendDtoOneOf1 {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function PluginFrontendDtoOneOf1FromJSON(json: any): PluginFrontendDtoOneOf1 {
    return PluginFrontendDtoOneOf1FromJSONTyped(json, false);
}

export function PluginFrontendDtoOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginFrontendDtoOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'target': json['target'],
    };
}

export function PluginFrontendDtoOneOf1ToJSON(json: any): PluginFrontendDtoOneOf1 {
    return PluginFrontendDtoOneOf1ToJSONTyped(json, false);
}

export function PluginFrontendDtoOneOf1ToJSONTyped(value?: PluginFrontendDtoOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'target': value['target'],
    };
}

