/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an installed plugin, mirroring `PluginView` flat: no hash, no
 * key. A later task reads `frontend_target` directly off this response.
 * @export
 * @interface PluginResponse
 */
export interface PluginResponse {
    /**
     * 
     * @type {Date}
     * @memberof PluginResponse
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PluginResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    frontendMode: string;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    frontendTarget?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PluginResponse
     */
    hasCredential: boolean;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof PluginResponse
     */
    lastSeenAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    organizationId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PluginResponse
     */
    permissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PluginResponse
     */
    requiredPermissions: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PluginResponse
     */
    slug: string;
}

/**
 * Check if a given object implements the PluginResponse interface.
 */
export function instanceOfPluginResponse(value: object): value is PluginResponse {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('frontendMode' in value) || value['frontendMode'] === undefined) return false;
    if (!('hasCredential' in value) || value['hasCredential'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('requiredPermissions' in value) || value['requiredPermissions'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PluginResponseFromJSON(json: any): PluginResponse {
    return PluginResponseFromJSONTyped(json, false);
}

export function PluginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'],
        'frontendMode': json['frontend_mode'],
        'frontendTarget': json['frontend_target'] == null ? undefined : json['frontend_target'],
        'hasCredential': json['has_credential'],
        'id': json['id'],
        'lastSeenAt': json['last_seen_at'] == null ? undefined : (new Date(json['last_seen_at'])),
        'name': json['name'],
        'organizationId': json['organization_id'],
        'permissions': json['permissions'],
        'requiredPermissions': json['required_permissions'],
        'slug': json['slug'],
    };
}

export function PluginResponseToJSON(json: any): PluginResponse {
    return PluginResponseToJSONTyped(json, false);
}

export function PluginResponseToJSONTyped(value?: PluginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'description': value['description'],
        'enabled': value['enabled'],
        'frontend_mode': value['frontendMode'],
        'frontend_target': value['frontendTarget'],
        'has_credential': value['hasCredential'],
        'id': value['id'],
        'last_seen_at': value['lastSeenAt'] === null ? null : ((value['lastSeenAt'] as any)?.toISOString()),
        'name': value['name'],
        'organization_id': value['organizationId'],
        'permissions': value['permissions'],
        'required_permissions': value['requiredPermissions'],
        'slug': value['slug'],
    };
}

