/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginFrontendDto } from './PluginFrontendDto';
import {
    PluginFrontendDtoFromJSON,
    PluginFrontendDtoFromJSONTyped,
    PluginFrontendDtoToJSON,
    PluginFrontendDtoToJSONTyped,
} from './PluginFrontendDto';

/**
 * Request body for updating an installed plugin. Every field is optional; an
 * omitted field leaves it untouched. `description` is a double-option so
 * "omitted" and "set to null" (clear it) stay distinguishable, matching
 * `PluginChange`.
 * @export
 * @interface PluginUpdateRequest
 */
export interface PluginUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof PluginUpdateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PluginUpdateRequest
     */
    enabled?: boolean | null;
    /**
     * 
     * @type {PluginFrontendDto}
     * @memberof PluginUpdateRequest
     */
    frontend?: PluginFrontendDto | null;
    /**
     * 
     * @type {string}
     * @memberof PluginUpdateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PluginUpdateRequest
     */
    permissions?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PluginUpdateRequest
     */
    requiredPermissions?: Array<string> | null;
}

/**
 * Check if a given object implements the PluginUpdateRequest interface.
 */
export function instanceOfPluginUpdateRequest(value: object): value is PluginUpdateRequest {
    return true;
}

export function PluginUpdateRequestFromJSON(json: any): PluginUpdateRequest {
    return PluginUpdateRequestFromJSONTyped(json, false);
}

export function PluginUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'frontend': json['frontend'] == null ? undefined : PluginFrontendDtoFromJSON(json['frontend']),
        'name': json['name'] == null ? undefined : json['name'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
        'requiredPermissions': json['required_permissions'] == null ? undefined : json['required_permissions'],
    };
}

export function PluginUpdateRequestToJSON(json: any): PluginUpdateRequest {
    return PluginUpdateRequestToJSONTyped(json, false);
}

export function PluginUpdateRequestToJSONTyped(value?: PluginUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'enabled': value['enabled'],
        'frontend': PluginFrontendDtoToJSON(value['frontend']),
        'name': value['name'],
        'permissions': value['permissions'],
        'required_permissions': value['requiredPermissions'],
    };
}

