/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * What the plugin viewer needs to render a frame, and nothing else. Its
 * reader holds the plugin's `required_permissions`, not `plugin:read`, so it
 * deliberately omits the administrative facts of [`PluginResponse`] — the
 * plugin's own permissions, its credential state and its last sign of life.
 * @export
 * @interface PluginViewResponse
 */
export interface PluginViewResponse {
    /**
     * 
     * @type {string}
     * @memberof PluginViewResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PluginViewResponse
     */
    frontendMode: string;
    /**
     * 
     * @type {string}
     * @memberof PluginViewResponse
     */
    frontendTarget?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PluginViewResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PluginViewResponse
     */
    slug: string;
}

/**
 * Check if a given object implements the PluginViewResponse interface.
 */
export function instanceOfPluginViewResponse(value: object): value is PluginViewResponse {
    if (!('frontendMode' in value) || value['frontendMode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PluginViewResponseFromJSON(json: any): PluginViewResponse {
    return PluginViewResponseFromJSONTyped(json, false);
}

export function PluginViewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginViewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'frontendMode': json['frontend_mode'],
        'frontendTarget': json['frontend_target'] == null ? undefined : json['frontend_target'],
        'name': json['name'],
        'slug': json['slug'],
    };
}

export function PluginViewResponseToJSON(json: any): PluginViewResponse {
    return PluginViewResponseToJSONTyped(json, false);
}

export function PluginViewResponseToJSONTyped(value?: PluginViewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'frontend_mode': value['frontendMode'],
        'frontend_target': value['frontendTarget'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

