/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PluginFrontendDtoOneOf } from './PluginFrontendDtoOneOf';
import {
    instanceOfPluginFrontendDtoOneOf,
    PluginFrontendDtoOneOfFromJSON,
    PluginFrontendDtoOneOfFromJSONTyped,
    PluginFrontendDtoOneOfToJSON,
} from './PluginFrontendDtoOneOf';
import type { PluginFrontendDtoOneOf1 } from './PluginFrontendDtoOneOf1';
import {
    instanceOfPluginFrontendDtoOneOf1,
    PluginFrontendDtoOneOf1FromJSON,
    PluginFrontendDtoOneOf1FromJSONTyped,
    PluginFrontendDtoOneOf1ToJSON,
} from './PluginFrontendDtoOneOf1';
import type { PluginFrontendDtoOneOf2 } from './PluginFrontendDtoOneOf2';
import {
    instanceOfPluginFrontendDtoOneOf2,
    PluginFrontendDtoOneOf2FromJSON,
    PluginFrontendDtoOneOf2FromJSONTyped,
    PluginFrontendDtoOneOf2ToJSON,
} from './PluginFrontendDtoOneOf2';

/**
 * @type PluginFrontendDto
 * Frontend wiring for a plugin, tagged so mode and target cannot be set
 * inconsistently.
 * @export
 */
export type PluginFrontendDto = PluginFrontendDtoOneOf | PluginFrontendDtoOneOf1 | PluginFrontendDtoOneOf2;

export function PluginFrontendDtoFromJSON(json: any): PluginFrontendDto {
    return PluginFrontendDtoFromJSONTyped(json, false);
}

export function PluginFrontendDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginFrontendDto {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPluginFrontendDtoOneOf(json)) {
        return PluginFrontendDtoOneOfFromJSONTyped(json, true);
    }
    if (instanceOfPluginFrontendDtoOneOf1(json)) {
        return PluginFrontendDtoOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfPluginFrontendDtoOneOf2(json)) {
        return PluginFrontendDtoOneOf2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function PluginFrontendDtoToJSON(json: any): any {
    return PluginFrontendDtoToJSONTyped(json, false);
}

export function PluginFrontendDtoToJSONTyped(value?: PluginFrontendDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPluginFrontendDtoOneOf(value)) {
        return PluginFrontendDtoOneOfToJSON(value as PluginFrontendDtoOneOf);
    }
    if (instanceOfPluginFrontendDtoOneOf1(value)) {
        return PluginFrontendDtoOneOf1ToJSON(value as PluginFrontendDtoOneOf1);
    }
    if (instanceOfPluginFrontendDtoOneOf2(value)) {
        return PluginFrontendDtoOneOf2ToJSON(value as PluginFrontendDtoOneOf2);
    }

    return {};
}

