/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginFrontendDtoOneOf
 */
export interface PluginFrontendDtoOneOf {
    /**
     * 
     * @type {string}
     * @memberof PluginFrontendDtoOneOf
     */
    mode: PluginFrontendDtoOneOfModeEnum;
    /**
     * 
     * @type {string}
     * @memberof PluginFrontendDtoOneOf
     */
    target: string;
}


/**
 * @export
 */
export const PluginFrontendDtoOneOfModeEnum = {
    External: 'external'
} as const;
export type PluginFrontendDtoOneOfModeEnum = typeof PluginFrontendDtoOneOfModeEnum[keyof typeof PluginFrontendDtoOneOfModeEnum];


/**
 * Check if a given object implements the PluginFrontendDtoOneOf interface.
 */
export function instanceOfPluginFrontendDtoOneOf(value: object): value is PluginFrontendDtoOneOf {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function PluginFrontendDtoOneOfFromJSON(json: any): PluginFrontendDtoOneOf {
    return PluginFrontendDtoOneOfFromJSONTyped(json, false);
}

export function PluginFrontendDtoOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginFrontendDtoOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'target': json['target'],
    };
}

export function PluginFrontendDtoOneOfToJSON(json: any): PluginFrontendDtoOneOf {
    return PluginFrontendDtoOneOfToJSONTyped(json, false);
}

export function PluginFrontendDtoOneOfToJSONTyped(value?: PluginFrontendDtoOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'target': value['target'],
    };
}

