/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginResponse } from './PluginResponse';
import {
    PluginResponseFromJSON,
    PluginResponseFromJSONTyped,
    PluginResponseToJSON,
    PluginResponseToJSONTyped,
} from './PluginResponse';

/**
 * Response containing a list of registered plugins.
 * @export
 * @interface PluginListResponse
 */
export interface PluginListResponse {
    /**
     * List of registered plugins.
     * @type {Array<PluginResponse>}
     * @memberof PluginListResponse
     */
    data: Array<PluginResponse>;
}

/**
 * Check if a given object implements the PluginListResponse interface.
 */
export function instanceOfPluginListResponse(value: object): value is PluginListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PluginListResponseFromJSON(json: any): PluginListResponse {
    return PluginListResponseFromJSONTyped(json, false);
}

export function PluginListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PluginResponseFromJSON)),
    };
}

export function PluginListResponseToJSON(json: any): PluginListResponse {
    return PluginListResponseToJSONTyped(json, false);
}

export function PluginListResponseToJSONTyped(value?: PluginListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PluginResponseToJSON)),
    };
}

