/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginFrontendDto } from './PluginFrontendDto';
import {
    PluginFrontendDtoFromJSON,
    PluginFrontendDtoFromJSONTyped,
    PluginFrontendDtoToJSON,
    PluginFrontendDtoToJSONTyped,
} from './PluginFrontendDto';

/**
 * Request body for installing a new plugin.
 * @export
 * @interface PluginCreateRequest
 */
export interface PluginCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof PluginCreateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {PluginFrontendDto}
     * @memberof PluginCreateRequest
     */
    frontend: PluginFrontendDto;
    /**
     * 
     * @type {string}
     * @memberof PluginCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PluginCreateRequest
     */
    organizationId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PluginCreateRequest
     */
    permissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PluginCreateRequest
     */
    requiredPermissions: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PluginCreateRequest
     */
    slug: string;
}

/**
 * Check if a given object implements the PluginCreateRequest interface.
 */
export function instanceOfPluginCreateRequest(value: object): value is PluginCreateRequest {
    if (!('frontend' in value) || value['frontend'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('requiredPermissions' in value) || value['requiredPermissions'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function PluginCreateRequestFromJSON(json: any): PluginCreateRequest {
    return PluginCreateRequestFromJSONTyped(json, false);
}

export function PluginCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'frontend': PluginFrontendDtoFromJSON(json['frontend']),
        'name': json['name'],
        'organizationId': json['organization_id'],
        'permissions': json['permissions'],
        'requiredPermissions': json['required_permissions'],
        'slug': json['slug'],
    };
}

export function PluginCreateRequestToJSON(json: any): PluginCreateRequest {
    return PluginCreateRequestToJSONTyped(json, false);
}

export function PluginCreateRequestToJSONTyped(value?: PluginCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'frontend': PluginFrontendDtoToJSON(value['frontend']),
        'name': value['name'],
        'organization_id': value['organizationId'],
        'permissions': value['permissions'],
        'required_permissions': value['requiredPermissions'],
        'slug': value['slug'],
    };
}

