/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginAuthRequest } from './PluginAuthRequest';
import {
    PluginAuthRequestFromJSON,
    PluginAuthRequestFromJSONTyped,
    PluginAuthRequestToJSON,
    PluginAuthRequestToJSONTyped,
} from './PluginAuthRequest';

/**
 * Request body for registering a new plugin.
 * @export
 * @interface PluginRegisterRequest
 */
export interface PluginRegisterRequest {
    /**
     * Authentication credentials for the plugin.
     * @type {PluginAuthRequest}
     * @memberof PluginRegisterRequest
     */
    auth: PluginAuthRequest;
    /**
     * Short description of the plugin's purpose.
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    description: string;
    /**
     * Human-readable plugin name.
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    name: string;
    /**
     * Base URL where the plugin is hosted.
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    path: string;
    /**
     * Unique slug identifier for the plugin.
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    slug: string;
    /**
     * Semantic version of the plugin.
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    version: string;
}

/**
 * Check if a given object implements the PluginRegisterRequest interface.
 */
export function instanceOfPluginRegisterRequest(value: object): value is PluginRegisterRequest {
    if (!('auth' in value) || value['auth'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PluginRegisterRequestFromJSON(json: any): PluginRegisterRequest {
    return PluginRegisterRequestFromJSONTyped(json, false);
}

export function PluginRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'auth': PluginAuthRequestFromJSON(json['auth']),
        'description': json['description'],
        'name': json['name'],
        'path': json['path'],
        'slug': json['slug'],
        'version': json['version'],
    };
}

export function PluginRegisterRequestToJSON(json: any): PluginRegisterRequest {
    return PluginRegisterRequestToJSONTyped(json, false);
}

export function PluginRegisterRequestToJSONTyped(value?: PluginRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth': PluginAuthRequestToJSON(value['auth']),
        'description': value['description'],
        'name': value['name'],
        'path': value['path'],
        'slug': value['slug'],
        'version': value['version'],
    };
}

