/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Water refill station an optimized route visits.
 * @export
 * @interface RefillPointResponse
 */
export interface RefillPointResponse {
    /**
     * Latitude of the station (WGS84).
     * @type {number}
     * @memberof RefillPointResponse
     */
    lat: number;
    /**
     * Longitude of the station (WGS84).
     * @type {number}
     * @memberof RefillPointResponse
     */
    lon: number;
    /**
     * Name of the refill station at route computation time.
     * @type {string}
     * @memberof RefillPointResponse
     */
    name: string;
}

/**
 * Check if a given object implements the RefillPointResponse interface.
 */
export function instanceOfRefillPointResponse(value: object): value is RefillPointResponse {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lon' in value) || value['lon'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RefillPointResponseFromJSON(json: any): RefillPointResponse {
    return RefillPointResponseFromJSONTyped(json, false);
}

export function RefillPointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefillPointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lon': json['lon'],
        'name': json['name'],
    };
}

export function RefillPointResponseToJSON(json: any): RefillPointResponse {
    return RefillPointResponseToJSONTyped(json, false);
}

export function RefillPointResponseToJSONTyped(value?: RefillPointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lon': value['lon'],
        'name': value['name'],
    };
}

