/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Evaluation metrics for a single region.
 * @export
 * @interface RegionEvaluationResponse
 */
export interface RegionEvaluationResponse {
    /**
     * Name of the region.
     * @type {string}
     * @memberof RegionEvaluationResponse
     */
    name: string;
    /**
     * Number of watering plans associated with this region.
     * @type {number}
     * @memberof RegionEvaluationResponse
     */
    wateringPlanCount: number;
}

/**
 * Check if a given object implements the RegionEvaluationResponse interface.
 */
export function instanceOfRegionEvaluationResponse(value: object): value is RegionEvaluationResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('wateringPlanCount' in value) || value['wateringPlanCount'] === undefined) return false;
    return true;
}

export function RegionEvaluationResponseFromJSON(json: any): RegionEvaluationResponse {
    return RegionEvaluationResponseFromJSONTyped(json, false);
}

export function RegionEvaluationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionEvaluationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'wateringPlanCount': json['watering_plan_count'],
    };
}

export function RegionEvaluationResponseToJSON(json: any): RegionEvaluationResponse {
    return RegionEvaluationResponseToJSONTyped(json, false);
}

export function RegionEvaluationResponseToJSONTyped(value?: RegionEvaluationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'watering_plan_count': value['wateringPlanCount'],
    };
}

