/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for creating a role, either from scratch or as a copy of an existing role/template.
 * @export
 * @interface RoleCreateRequest
 */
export interface RoleCreateRequest {
    /**
     * Source role or template to copy the permission set from.
     * @type {string}
     * @memberof RoleCreateRequest
     */
    copyFromRoleId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleCreateRequest
     */
    description?: string | null;
    /**
     * Required unless `copy_from_role_id` is set (in which case it renames the copy).
     * @type {string}
     * @memberof RoleCreateRequest
     */
    name?: string | null;
    /**
     * Required unless `copy_from_role_id` is set.
     * @type {Array<string>}
     * @memberof RoleCreateRequest
     */
    permissions?: Array<string> | null;
}

/**
 * Check if a given object implements the RoleCreateRequest interface.
 */
export function instanceOfRoleCreateRequest(value: object): value is RoleCreateRequest {
    return true;
}

export function RoleCreateRequestFromJSON(json: any): RoleCreateRequest {
    return RoleCreateRequestFromJSONTyped(json, false);
}

export function RoleCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'copyFromRoleId': json['copy_from_role_id'] == null ? undefined : json['copy_from_role_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function RoleCreateRequestToJSON(json: any): RoleCreateRequest {
    return RoleCreateRequestToJSONTyped(json, false);
}

export function RoleCreateRequestToJSONTyped(value?: RoleCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'copy_from_role_id': value['copyFromRoleId'],
        'description': value['description'],
        'name': value['name'],
        'permissions': value['permissions'],
    };
}

