/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for calculating a watering route.
 * @export
 * @interface RouteRequest
 */
export interface RouteRequest {
    /**
     * List of tree cluster identifiers to include in the route.
     * @type {Array<string>}
     * @memberof RouteRequest
     */
    clusterIds: Array<string>;
    /**
     * Name of the configured start point to depart from and return to. Unknown names fall back to the default depot.
     * @type {string}
     * @memberof RouteRequest
     */
    startPointName?: string | null;
    /**
     * Identifier of the trailer vehicle to use, if any.
     * @type {string}
     * @memberof RouteRequest
     */
    trailerId?: string | null;
    /**
     * Identifier of the transporter vehicle to use.
     * @type {string}
     * @memberof RouteRequest
     */
    transporterId: string;
}

/**
 * Check if a given object implements the RouteRequest interface.
 */
export function instanceOfRouteRequest(value: object): value is RouteRequest {
    if (!('clusterIds' in value) || value['clusterIds'] === undefined) return false;
    if (!('transporterId' in value) || value['transporterId'] === undefined) return false;
    return true;
}

export function RouteRequestFromJSON(json: any): RouteRequest {
    return RouteRequestFromJSONTyped(json, false);
}

export function RouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterIds': json['cluster_ids'],
        'startPointName': json['start_point_name'] == null ? undefined : json['start_point_name'],
        'trailerId': json['trailer_id'] == null ? undefined : json['trailer_id'],
        'transporterId': json['transporter_id'],
    };
}

export function RouteRequestToJSON(json: any): RouteRequest {
    return RouteRequestToJSONTyped(json, false);
}

export function RouteRequestToJSONTyped(value?: RouteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cluster_ids': value['clusterIds'],
        'start_point_name': value['startPointName'],
        'trailer_id': value['trailerId'],
        'transporter_id': value['transporterId'],
    };
}

