/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sensor type (currently only LoRaWAN).
 * @export
 */
export const SensorTypeResponse = {
    Lorawan: 'lorawan'
} as const;
export type SensorTypeResponse = typeof SensorTypeResponse[keyof typeof SensorTypeResponse];


export function instanceOfSensorTypeResponse(value: any): boolean {
    for (const key in SensorTypeResponse) {
        if (Object.prototype.hasOwnProperty.call(SensorTypeResponse, key)) {
            if (SensorTypeResponse[key as keyof typeof SensorTypeResponse] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SensorTypeResponseFromJSON(json: any): SensorTypeResponse {
    return SensorTypeResponseFromJSONTyped(json, false);
}

export function SensorTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorTypeResponse {
    return json as SensorTypeResponse;
}

export function SensorTypeResponseToJSON(value?: SensorTypeResponse | null): any {
    return value as any;
}

export function SensorTypeResponseToJSONTyped(value: any, ignoreDiscriminator: boolean): SensorTypeResponse {
    return value as SensorTypeResponse;
}

