/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorModelAbilityResponse } from './SensorModelAbilityResponse';
import {
    SensorModelAbilityResponseFromJSON,
    SensorModelAbilityResponseFromJSONTyped,
    SensorModelAbilityResponseToJSON,
    SensorModelAbilityResponseToJSONTyped,
} from './SensorModelAbilityResponse';

/**
 * Summary view of the [`SensorModel`] this sensor belongs to.
 * @export
 * @interface SensorModelSummaryResponse
 */
export interface SensorModelSummaryResponse {
    /**
     * 
     * @type {Array<SensorModelAbilityResponse>}
     * @memberof SensorModelSummaryResponse
     */
    abilities: Array<SensorModelAbilityResponse>;
    /**
     * 
     * @type {string}
     * @memberof SensorModelSummaryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SensorModelSummaryResponse
     */
    name: string;
}

/**
 * Check if a given object implements the SensorModelSummaryResponse interface.
 */
export function instanceOfSensorModelSummaryResponse(value: object): value is SensorModelSummaryResponse {
    if (!('abilities' in value) || value['abilities'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SensorModelSummaryResponseFromJSON(json: any): SensorModelSummaryResponse {
    return SensorModelSummaryResponseFromJSONTyped(json, false);
}

export function SensorModelSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorModelSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'abilities': ((json['abilities'] as Array<any>).map(SensorModelAbilityResponseFromJSON)),
        'id': json['id'],
        'name': json['name'],
    };
}

export function SensorModelSummaryResponseToJSON(json: any): SensorModelSummaryResponse {
    return SensorModelSummaryResponseToJSONTyped(json, false);
}

export function SensorModelSummaryResponseToJSONTyped(value?: SensorModelSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abilities': ((value['abilities'] as Array<any>).map(SensorModelAbilityResponseToJSON)),
        'id': value['id'],
        'name': value['name'],
    };
}

