/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Physical quantity reported by a sensor ability.
 * @export
 */
export const SensorAbilityUnitDto = {
    Percent: 'percent',
    Centibar: 'centibar',
    Ohm: 'ohm',
    Celsius: 'celsius',
    Volt: 'volt'
} as const;
export type SensorAbilityUnitDto = typeof SensorAbilityUnitDto[keyof typeof SensorAbilityUnitDto];


export function instanceOfSensorAbilityUnitDto(value: any): boolean {
    for (const key in SensorAbilityUnitDto) {
        if (Object.prototype.hasOwnProperty.call(SensorAbilityUnitDto, key)) {
            if (SensorAbilityUnitDto[key as keyof typeof SensorAbilityUnitDto] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SensorAbilityUnitDtoFromJSON(json: any): SensorAbilityUnitDto {
    return SensorAbilityUnitDtoFromJSONTyped(json, false);
}

export function SensorAbilityUnitDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorAbilityUnitDto {
    return json as SensorAbilityUnitDto;
}

export function SensorAbilityUnitDtoToJSON(value?: SensorAbilityUnitDto | null): any {
    return value as any;
}

export function SensorAbilityUnitDtoToJSONTyped(value: any, ignoreDiscriminator: boolean): SensorAbilityUnitDto {
    return value as SensorAbilityUnitDto;
}

