/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignalResponse } from './SignalResponse';
import {
    SignalResponseFromJSON,
    SignalResponseFromJSONTyped,
    SignalResponseToJSON,
    SignalResponseToJSONTyped,
} from './SignalResponse';

/**
 * A single data payload received from a LoRaWAN sensor.
 * @export
 * @interface SensorDataResponse
 */
export interface SensorDataResponse {
    /**
     * Timestamp when the data was first recorded (RFC 3339).
     * @type {string}
     * @memberof SensorDataResponse
     */
    createdAt: string;
    /**
     * Raw sensor payload as a JSON object (structure depends on the sensor type).
     * @type {object}
     * @memberof SensorDataResponse
     */
    data: object;
    /**
     * Unique identifier of the reading.
     * @type {string}
     * @memberof SensorDataResponse
     */
    id: string;
    /**
     * LoRaWAN radio quality of the strongest gateway for this reading, if present.
     * @type {SignalResponse}
     * @memberof SensorDataResponse
     */
    signal?: SignalResponse | null;
    /**
     * Timestamp when the data was last modified (RFC 3339).
     * @type {string}
     * @memberof SensorDataResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the SensorDataResponse interface.
 */
export function instanceOfSensorDataResponse(value: object): value is SensorDataResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SensorDataResponseFromJSON(json: any): SensorDataResponse {
    return SensorDataResponseFromJSONTyped(json, false);
}

export function SensorDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'data': json['data'],
        'id': json['id'],
        'signal': json['signal'] == null ? undefined : SignalResponseFromJSON(json['signal']),
        'updatedAt': json['updated_at'],
    };
}

export function SensorDataResponseToJSON(json: any): SensorDataResponse {
    return SensorDataResponseToJSONTyped(json, false);
}

export function SensorDataResponseToJSONTyped(value?: SensorDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'data': value['data'],
        'id': value['id'],
        'signal': SignalResponseToJSON(value['signal']),
        'updated_at': value['updatedAt'],
    };
}

