/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * WGS-84 coordinate exposed in sensor responses (derived from the linked tree).
 * @export
 * @interface SensorCoordinate
 */
export interface SensorCoordinate {
    /**
     * 
     * @type {number}
     * @memberof SensorCoordinate
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof SensorCoordinate
     */
    longitude: number;
}

/**
 * Check if a given object implements the SensorCoordinate interface.
 */
export function instanceOfSensorCoordinate(value: object): value is SensorCoordinate {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function SensorCoordinateFromJSON(json: any): SensorCoordinate {
    return SensorCoordinateFromJSONTyped(json, false);
}

export function SensorCoordinateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorCoordinate {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function SensorCoordinateToJSON(json: any): SensorCoordinate {
    return SensorCoordinateToJSONTyped(json, false);
}

export function SensorCoordinateToJSONTyped(value?: SensorCoordinate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

