/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorModelAbilityResponse } from './SensorModelAbilityResponse';
import {
    SensorModelAbilityResponseFromJSON,
    SensorModelAbilityResponseFromJSONTyped,
    SensorModelAbilityResponseToJSON,
    SensorModelAbilityResponseToJSONTyped,
} from './SensorModelAbilityResponse';

/**
 * Full description of a supported sensor model and its abilities.
 * @export
 * @interface SensorModelResponse
 */
export interface SensorModelResponse {
    /**
     * 
     * @type {Array<SensorModelAbilityResponse>}
     * @memberof SensorModelResponse
     */
    abilities: Array<SensorModelAbilityResponse>;
    /**
     * 
     * @type {string}
     * @memberof SensorModelResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SensorModelResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SensorModelResponse
     */
    name: string;
}

/**
 * Check if a given object implements the SensorModelResponse interface.
 */
export function instanceOfSensorModelResponse(value: object): value is SensorModelResponse {
    if (!('abilities' in value) || value['abilities'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SensorModelResponseFromJSON(json: any): SensorModelResponse {
    return SensorModelResponseFromJSONTyped(json, false);
}

export function SensorModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorModelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'abilities': ((json['abilities'] as Array<any>).map(SensorModelAbilityResponseFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function SensorModelResponseToJSON(json: any): SensorModelResponse {
    return SensorModelResponseToJSONTyped(json, false);
}

export function SensorModelResponseToJSONTyped(value?: SensorModelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abilities': ((value['abilities'] as Array<any>).map(SensorModelAbilityResponseToJSON)),
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
    };
}

