/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceStatusResponse
 */
export interface ServiceStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceStatusResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceStatusResponse
     */
    healthy: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceStatusResponse
     */
    lastChecked: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceStatusResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceStatusResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceStatusResponse
     */
    responseTimeMs: number;
}

/**
 * Check if a given object implements the ServiceStatusResponse interface.
 */
export function instanceOfServiceStatusResponse(value: object): value is ServiceStatusResponse {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('healthy' in value) || value['healthy'] === undefined) return false;
    if (!('lastChecked' in value) || value['lastChecked'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('responseTimeMs' in value) || value['responseTimeMs'] === undefined) return false;
    return true;
}

export function ServiceStatusResponseFromJSON(json: any): ServiceStatusResponse {
    return ServiceStatusResponseFromJSONTyped(json, false);
}

export function ServiceStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'healthy': json['healthy'],
        'lastChecked': json['lastChecked'],
        'message': json['message'],
        'name': json['name'],
        'responseTimeMs': json['responseTimeMs'],
    };
}

export function ServiceStatusResponseToJSON(json: any): ServiceStatusResponse {
    return ServiceStatusResponseToJSONTyped(json, false);
}

export function ServiceStatusResponseToJSONTyped(value?: ServiceStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'healthy': value['healthy'],
        'lastChecked': value['lastChecked'],
        'message': value['message'],
        'name': value['name'],
        'responseTimeMs': value['responseTimeMs'],
    };
}

