/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceStatusResponse } from './ServiceStatusResponse';
import {
    ServiceStatusResponseFromJSON,
    ServiceStatusResponseFromJSONTyped,
    ServiceStatusResponseToJSON,
    ServiceStatusResponseToJSONTyped,
} from './ServiceStatusResponse';

/**
 * 
 * @export
 * @interface ServicesInfoResponse
 */
export interface ServicesInfoResponse {
    /**
     * 
     * @type {Array<ServiceStatusResponse>}
     * @memberof ServicesInfoResponse
     */
    items: Array<ServiceStatusResponse>;
}

/**
 * Check if a given object implements the ServicesInfoResponse interface.
 */
export function instanceOfServicesInfoResponse(value: object): value is ServicesInfoResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ServicesInfoResponseFromJSON(json: any): ServicesInfoResponse {
    return ServicesInfoResponseFromJSONTyped(json, false);
}

export function ServicesInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ServiceStatusResponseFromJSON)),
    };
}

export function ServicesInfoResponseToJSON(json: any): ServicesInfoResponse {
    return ServicesInfoResponseToJSONTyped(json, false);
}

export function ServicesInfoResponseToJSONTyped(value?: ServicesInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ServiceStatusResponseToJSON)),
    };
}

