/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for changing a user's organization.
 * @export
 * @interface SetOrganizationRequest
 */
export interface SetOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof SetOrganizationRequest
     */
    organizationId: string;
}

/**
 * Check if a given object implements the SetOrganizationRequest interface.
 */
export function instanceOfSetOrganizationRequest(value: object): value is SetOrganizationRequest {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function SetOrganizationRequestFromJSON(json: any): SetOrganizationRequest {
    return SetOrganizationRequestFromJSONTyped(json, false);
}

export function SetOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organization_id'],
    };
}

export function SetOrganizationRequestToJSON(json: any): SetOrganizationRequest {
    return SetOrganizationRequestToJSONTyped(json, false);
}

export function SetOrganizationRequestToJSONTyped(value?: SetOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organizationId'],
    };
}

