/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for `PUT /sensors/{sensor_id}/tree` - links an activated
 * sensor to (or moves it to) the given tree.
 * @export
 * @interface SetSensorTreeRequest
 */
export interface SetSensorTreeRequest {
    /**
     * 
     * @type {string}
     * @memberof SetSensorTreeRequest
     */
    treeId: string;
}

/**
 * Check if a given object implements the SetSensorTreeRequest interface.
 */
export function instanceOfSetSensorTreeRequest(value: object): value is SetSensorTreeRequest {
    if (!('treeId' in value) || value['treeId'] === undefined) return false;
    return true;
}

export function SetSensorTreeRequestFromJSON(json: any): SetSensorTreeRequest {
    return SetSensorTreeRequestFromJSONTyped(json, false);
}

export function SetSensorTreeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetSensorTreeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'treeId': json['tree_id'],
    };
}

export function SetSensorTreeRequestToJSON(json: any): SetSensorTreeRequest {
    return SetSensorTreeRequestToJSONTyped(json, false);
}

export function SetSensorTreeRequestToJSONTyped(value?: SetSensorTreeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tree_id': value['treeId'],
    };
}

