/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LoRaWAN radio quality of the strongest receiving gateway for a reading.
 * @export
 * @interface SignalResponse
 */
export interface SignalResponse {
    /**
     * Number of gateways that received this uplink.
     * @type {number}
     * @memberof SignalResponse
     */
    gatewayCount: number;
    /**
     * Received signal strength indicator in dBm (higher/less-negative is better).
     * @type {number}
     * @memberof SignalResponse
     */
    rssiDbm: number;
    /**
     * Signal-to-noise ratio in dB.
     * @type {number}
     * @memberof SignalResponse
     */
    snrDb: number;
}

/**
 * Check if a given object implements the SignalResponse interface.
 */
export function instanceOfSignalResponse(value: object): value is SignalResponse {
    if (!('gatewayCount' in value) || value['gatewayCount'] === undefined) return false;
    if (!('rssiDbm' in value) || value['rssiDbm'] === undefined) return false;
    if (!('snrDb' in value) || value['snrDb'] === undefined) return false;
    return true;
}

export function SignalResponseFromJSON(json: any): SignalResponse {
    return SignalResponseFromJSONTyped(json, false);
}

export function SignalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'gatewayCount': json['gateway_count'],
        'rssiDbm': json['rssi_dbm'],
        'snrDb': json['snr_db'],
    };
}

export function SignalResponseToJSON(json: any): SignalResponse {
    return SignalResponseToJSONTyped(json, false);
}

export function SignalResponseToJSONTyped(value?: SignalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gateway_count': value['gatewayCount'],
        'rssi_dbm': value['rssiDbm'],
        'snr_db': value['snrDb'],
    };
}

