/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One bucket of the tree-condition series, as % plant-available water
 * (REW × 100), clamped to 0–100: wetter than field capacity or drier than
 * the wilting point carries no extra meaning for the dashboard and reads
 * as a bug ("129 %"). The depth with the lowest mean REW wins per bucket.
 * @export
 * @interface SoilMoistureConditionPointResponse
 */
export interface SoilMoistureConditionPointResponse {
    /**
     * 
     * @type {number}
     * @memberof SoilMoistureConditionPointResponse
     */
    max: number;
    /**
     * 
     * @type {number}
     * @memberof SoilMoistureConditionPointResponse
     */
    mean: number;
    /**
     * 
     * @type {number}
     * @memberof SoilMoistureConditionPointResponse
     */
    min: number;
    /**
     * Bucket start (RFC 3339).
     * @type {Date}
     * @memberof SoilMoistureConditionPointResponse
     */
    timestamp: Date;
    /**
     * Depth whose mean REW was lowest in this bucket.
     * @type {number}
     * @memberof SoilMoistureConditionPointResponse
     */
    worstDepthCm: number;
}

/**
 * Check if a given object implements the SoilMoistureConditionPointResponse interface.
 */
export function instanceOfSoilMoistureConditionPointResponse(value: object): value is SoilMoistureConditionPointResponse {
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('mean' in value) || value['mean'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('worstDepthCm' in value) || value['worstDepthCm'] === undefined) return false;
    return true;
}

export function SoilMoistureConditionPointResponseFromJSON(json: any): SoilMoistureConditionPointResponse {
    return SoilMoistureConditionPointResponseFromJSONTyped(json, false);
}

export function SoilMoistureConditionPointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoilMoistureConditionPointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'max': json['max'],
        'mean': json['mean'],
        'min': json['min'],
        'timestamp': (new Date(json['timestamp'])),
        'worstDepthCm': json['worst_depth_cm'],
    };
}

export function SoilMoistureConditionPointResponseToJSON(json: any): SoilMoistureConditionPointResponse {
    return SoilMoistureConditionPointResponseToJSONTyped(json, false);
}

export function SoilMoistureConditionPointResponseToJSONTyped(value?: SoilMoistureConditionPointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max': value['max'],
        'mean': value['mean'],
        'min': value['min'],
        'timestamp': ((value['timestamp']).toISOString()),
        'worst_depth_cm': value['worstDepthCm'],
    };
}

