/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SoilMoisturePointResponse } from './SoilMoisturePointResponse';
import {
    SoilMoisturePointResponseFromJSON,
    SoilMoisturePointResponseFromJSONTyped,
    SoilMoisturePointResponseToJSON,
    SoilMoisturePointResponseToJSONTyped,
} from './SoilMoisturePointResponse';

/**
 * 
 * @export
 * @interface SoilMoistureDepthSeriesResponse
 */
export interface SoilMoistureDepthSeriesResponse {
    /**
     * 
     * @type {number}
     * @memberof SoilMoistureDepthSeriesResponse
     */
    depthCm: number;
    /**
     * 
     * @type {Array<SoilMoisturePointResponse>}
     * @memberof SoilMoistureDepthSeriesResponse
     */
    points: Array<SoilMoisturePointResponse>;
}

/**
 * Check if a given object implements the SoilMoistureDepthSeriesResponse interface.
 */
export function instanceOfSoilMoistureDepthSeriesResponse(value: object): value is SoilMoistureDepthSeriesResponse {
    if (!('depthCm' in value) || value['depthCm'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function SoilMoistureDepthSeriesResponseFromJSON(json: any): SoilMoistureDepthSeriesResponse {
    return SoilMoistureDepthSeriesResponseFromJSONTyped(json, false);
}

export function SoilMoistureDepthSeriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoilMoistureDepthSeriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'depthCm': json['depth_cm'],
        'points': ((json['points'] as Array<any>).map(SoilMoisturePointResponseFromJSON)),
    };
}

export function SoilMoistureDepthSeriesResponseToJSON(json: any): SoilMoistureDepthSeriesResponse {
    return SoilMoistureDepthSeriesResponseToJSONTyped(json, false);
}

export function SoilMoistureDepthSeriesResponseToJSONTyped(value?: SoilMoistureDepthSeriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'depth_cm': value['depthCm'],
        'points': ((value['points'] as Array<any>).map(SoilMoisturePointResponseToJSON)),
    };
}

