/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create/replace payload for a start point.
 * @export
 * @interface StartPointRequest
 */
export interface StartPointRequest {
    /**
     * 
     * @type {number}
     * @memberof StartPointRequest
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof StartPointRequest
     */
    lon: number;
    /**
     * 
     * @type {string}
     * @memberof StartPointRequest
     */
    name: string;
    /**
     * Organization this start point belongs to. Defaults to the acting
     * user's own organization (or the root organization in the demo bypass).
     * @type {string}
     * @memberof StartPointRequest
     */
    organizationId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StartPointRequest
     */
    wateringPoint?: boolean;
}

/**
 * Check if a given object implements the StartPointRequest interface.
 */
export function instanceOfStartPointRequest(value: object): value is StartPointRequest {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lon' in value) || value['lon'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StartPointRequestFromJSON(json: any): StartPointRequest {
    return StartPointRequestFromJSONTyped(json, false);
}

export function StartPointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartPointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lon': json['lon'],
        'name': json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'wateringPoint': json['watering_point'] == null ? undefined : json['watering_point'],
    };
}

export function StartPointRequestToJSON(json: any): StartPointRequest {
    return StartPointRequestToJSONTyped(json, false);
}

export function StartPointRequestToJSONTyped(value?: StartPointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lon': value['lon'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'watering_point': value['wateringPoint'],
    };
}

