/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for transferring a resource's ownership to another
 * organization.
 * @export
 * @interface TransferRequest
 */
export interface TransferRequest {
    /**
     * 
     * @type {string}
     * @memberof TransferRequest
     */
    organizationId: string;
}

/**
 * Check if a given object implements the TransferRequest interface.
 */
export function instanceOfTransferRequest(value: object): value is TransferRequest {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function TransferRequestFromJSON(json: any): TransferRequest {
    return TransferRequestFromJSONTyped(json, false);
}

export function TransferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organization_id'],
    };
}

export function TransferRequestToJSON(json: any): TransferRequest {
    return TransferRequestToJSONTyped(json, false);
}

export function TransferRequestToJSONTyped(value?: TransferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organizationId'],
    };
}

