/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TreeRefResponse } from './TreeRefResponse';
import {
    TreeRefResponseFromJSON,
    TreeRefResponseFromJSONTyped,
    TreeRefResponseToJSON,
    TreeRefResponseToJSONTyped,
} from './TreeRefResponse';

/**
 * Keyset page over a plugin's own tree references, ordered by external_id.
 * No `total`: the adapter walks this to the end anyway, and a cursor stays
 * stable while imports run concurrently.
 * @export
 * @interface TreeRefPageResponse
 */
export interface TreeRefPageResponse {
    /**
     * 
     * @type {Array<TreeRefResponse>}
     * @memberof TreeRefPageResponse
     */
    items: Array<TreeRefResponse>;
    /**
     * 
     * @type {string}
     * @memberof TreeRefPageResponse
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the TreeRefPageResponse interface.
 */
export function instanceOfTreeRefPageResponse(value: object): value is TreeRefPageResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TreeRefPageResponseFromJSON(json: any): TreeRefPageResponse {
    return TreeRefPageResponseFromJSONTyped(json, false);
}

export function TreeRefPageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeRefPageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TreeRefResponseFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function TreeRefPageResponseToJSON(json: any): TreeRefPageResponse {
    return TreeRefPageResponseToJSONTyped(json, false);
}

export function TreeRefPageResponseToJSONTyped(value?: TreeRefPageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TreeRefResponseToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

