/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SoilCondition } from './SoilCondition';
import {
    SoilConditionFromJSON,
    SoilConditionFromJSONTyped,
    SoilConditionToJSON,
    SoilConditionToJSONTyped,
} from './SoilCondition';

/**
 * Request body for updating an existing tree cluster.
 * @export
 * @interface TreeClusterUpdateRequest
 */
export interface TreeClusterUpdateRequest {
    /**
     * 
     * @type {object}
     * @memberof TreeClusterUpdateRequest
     */
    additionalInformation?: object | null;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterUpdateRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterUpdateRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterUpdateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterUpdateRequest
     */
    provider?: string | null;
    /**
     * 
     * @type {SoilCondition}
     * @memberof TreeClusterUpdateRequest
     */
    soilCondition: SoilCondition;
    /**
     * 
     * @type {Array<string>}
     * @memberof TreeClusterUpdateRequest
     */
    treeIds: Array<string>;
}



/**
 * Check if a given object implements the TreeClusterUpdateRequest interface.
 */
export function instanceOfTreeClusterUpdateRequest(value: object): value is TreeClusterUpdateRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('soilCondition' in value) || value['soilCondition'] === undefined) return false;
    if (!('treeIds' in value) || value['treeIds'] === undefined) return false;
    return true;
}

export function TreeClusterUpdateRequestFromJSON(json: any): TreeClusterUpdateRequest {
    return TreeClusterUpdateRequestFromJSONTyped(json, false);
}

export function TreeClusterUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeClusterUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'address': json['address'],
        'description': json['description'],
        'name': json['name'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'soilCondition': SoilConditionFromJSON(json['soil_condition']),
        'treeIds': json['tree_ids'],
    };
}

export function TreeClusterUpdateRequestToJSON(json: any): TreeClusterUpdateRequest {
    return TreeClusterUpdateRequestToJSONTyped(json, false);
}

export function TreeClusterUpdateRequestToJSONTyped(value?: TreeClusterUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'address': value['address'],
        'description': value['description'],
        'name': value['name'],
        'provider': value['provider'],
        'soil_condition': SoilConditionToJSON(value['soilCondition']),
        'tree_ids': value['treeIds'],
    };
}

