/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TreeMarkerResponse } from './TreeMarkerResponse';
import {
    TreeMarkerResponseFromJSON,
    TreeMarkerResponseFromJSONTyped,
    TreeMarkerResponseToJSON,
    TreeMarkerResponseToJSONTyped,
} from './TreeMarkerResponse';

/**
 * 
 * @export
 * @interface TreeMarkerListResponse
 */
export interface TreeMarkerListResponse {
    /**
     * 
     * @type {Array<TreeMarkerResponse>}
     * @memberof TreeMarkerListResponse
     */
    data: Array<TreeMarkerResponse>;
}

/**
 * Check if a given object implements the TreeMarkerListResponse interface.
 */
export function instanceOfTreeMarkerListResponse(value: object): value is TreeMarkerListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TreeMarkerListResponseFromJSON(json: any): TreeMarkerListResponse {
    return TreeMarkerListResponseFromJSONTyped(json, false);
}

export function TreeMarkerListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeMarkerListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TreeMarkerResponseFromJSON)),
    };
}

export function TreeMarkerListResponseToJSON(json: any): TreeMarkerListResponse {
    return TreeMarkerListResponseToJSONTyped(json, false);
}

export function TreeMarkerListResponseToJSONTyped(value?: TreeMarkerListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TreeMarkerResponseToJSON)),
    };
}

