/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SoilCondition } from './SoilCondition';
import {
    SoilConditionFromJSON,
    SoilConditionFromJSONTyped,
    SoilConditionToJSON,
    SoilConditionToJSONTyped,
} from './SoilCondition';

/**
 * Request body for creating a new tree cluster.
 * @export
 * @interface TreeClusterCreateRequest
 */
export interface TreeClusterCreateRequest {
    /**
     * 
     * @type {object}
     * @memberof TreeClusterCreateRequest
     */
    additionalInformation?: object | null;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterCreateRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterCreateRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterCreateRequest
     */
    organizationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TreeClusterCreateRequest
     */
    provider?: string | null;
    /**
     * 
     * @type {SoilCondition}
     * @memberof TreeClusterCreateRequest
     */
    soilCondition: SoilCondition;
    /**
     * 
     * @type {Array<string>}
     * @memberof TreeClusterCreateRequest
     */
    treeIds: Array<string>;
}



/**
 * Check if a given object implements the TreeClusterCreateRequest interface.
 */
export function instanceOfTreeClusterCreateRequest(value: object): value is TreeClusterCreateRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('soilCondition' in value) || value['soilCondition'] === undefined) return false;
    if (!('treeIds' in value) || value['treeIds'] === undefined) return false;
    return true;
}

export function TreeClusterCreateRequestFromJSON(json: any): TreeClusterCreateRequest {
    return TreeClusterCreateRequestFromJSONTyped(json, false);
}

export function TreeClusterCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeClusterCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'address': json['address'],
        'description': json['description'],
        'name': json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'soilCondition': SoilConditionFromJSON(json['soil_condition']),
        'treeIds': json['tree_ids'],
    };
}

export function TreeClusterCreateRequestToJSON(json: any): TreeClusterCreateRequest {
    return TreeClusterCreateRequestToJSONTyped(json, false);
}

export function TreeClusterCreateRequestToJSONTyped(value?: TreeClusterCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'address': value['address'],
        'description': value['description'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'provider': value['provider'],
        'soil_condition': SoilConditionToJSON(value['soilCondition']),
        'tree_ids': value['treeIds'],
    };
}

