/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TreeIngestItemRequest } from './TreeIngestItemRequest';
import {
    TreeIngestItemRequestFromJSON,
    TreeIngestItemRequestFromJSONTyped,
    TreeIngestItemRequestToJSON,
    TreeIngestItemRequestToJSONTyped,
} from './TreeIngestItemRequest';

/**
 * Request body for the tree ingest batch endpoint. Capped at
 * `plugin_ingest_service::MAX_INGEST_ITEMS` entries; a larger batch is
 * rejected wholesale (413) before any entry is processed.
 * @export
 * @interface TreeIngestBatchRequest
 */
export interface TreeIngestBatchRequest {
    /**
     * 
     * @type {Array<TreeIngestItemRequest>}
     * @memberof TreeIngestBatchRequest
     */
    items: Array<TreeIngestItemRequest>;
}

/**
 * Check if a given object implements the TreeIngestBatchRequest interface.
 */
export function instanceOfTreeIngestBatchRequest(value: object): value is TreeIngestBatchRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TreeIngestBatchRequestFromJSON(json: any): TreeIngestBatchRequest {
    return TreeIngestBatchRequestFromJSONTyped(json, false);
}

export function TreeIngestBatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeIngestBatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TreeIngestItemRequestFromJSON)),
    };
}

export function TreeIngestBatchRequestToJSON(json: any): TreeIngestBatchRequest {
    return TreeIngestBatchRequestToJSONTyped(json, false);
}

export function TreeIngestBatchRequestToJSONTyped(value?: TreeIngestBatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TreeIngestItemRequestToJSON)),
    };
}

