/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TreeResponse } from './TreeResponse';
import {
    TreeResponseFromJSON,
    TreeResponseFromJSONTyped,
    TreeResponseToJSON,
    TreeResponseToJSONTyped,
} from './TreeResponse';

/**
 * A tree with its distance from a reference point.
 * @export
 * @interface TreeWithDistanceResponse
 */
export interface TreeWithDistanceResponse {
    /**
     * 
     * @type {number}
     * @memberof TreeWithDistanceResponse
     */
    distanceMeters: number;
    /**
     * 
     * @type {TreeResponse}
     * @memberof TreeWithDistanceResponse
     */
    tree: TreeResponse;
}

/**
 * Check if a given object implements the TreeWithDistanceResponse interface.
 */
export function instanceOfTreeWithDistanceResponse(value: object): value is TreeWithDistanceResponse {
    if (!('distanceMeters' in value) || value['distanceMeters'] === undefined) return false;
    if (!('tree' in value) || value['tree'] === undefined) return false;
    return true;
}

export function TreeWithDistanceResponseFromJSON(json: any): TreeWithDistanceResponse {
    return TreeWithDistanceResponseFromJSONTyped(json, false);
}

export function TreeWithDistanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeWithDistanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'distanceMeters': json['distance_meters'],
        'tree': TreeResponseFromJSON(json['tree']),
    };
}

export function TreeWithDistanceResponseToJSON(json: any): TreeWithDistanceResponse {
    return TreeWithDistanceResponseToJSONTyped(json, false);
}

export function TreeWithDistanceResponseToJSONTyped(value?: TreeWithDistanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'distance_meters': value['distanceMeters'],
        'tree': TreeResponseToJSON(value['tree']),
    };
}

