/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * Request body for replacing a user's profile data.
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {
    /**
     * Avatar URL; empty or absent clears the value.
     * @type {string}
     * @memberof UserUpdateRequest
     */
    avatarUrl?: string | null;
    /**
     * Full replacement set of driving licenses.
     * @type {Array<DrivingLicense>}
     * @memberof UserUpdateRequest
     */
    drivingLicenses: Array<DrivingLicense>;
    /**
     * Internal employee identifier; empty or absent clears the value.
     * @type {string}
     * @memberof UserUpdateRequest
     */
    employeeId?: string | null;
    /**
     * Contact phone number; empty or absent clears the value.
     * @type {string}
     * @memberof UserUpdateRequest
     */
    phoneNumber?: string | null;
    /**
     * New availability status.
     * @type {UserStatus}
     * @memberof UserUpdateRequest
     */
    status: UserStatus;
    /**
     * Whether the user may be assigned to watering plans.
     * @type {boolean}
     * @memberof UserUpdateRequest
     */
    wateringPlanSelectable: boolean;
}



/**
 * Check if a given object implements the UserUpdateRequest interface.
 */
export function instanceOfUserUpdateRequest(value: object): value is UserUpdateRequest {
    if (!('drivingLicenses' in value) || value['drivingLicenses'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('wateringPlanSelectable' in value) || value['wateringPlanSelectable'] === undefined) return false;
    return true;
}

export function UserUpdateRequestFromJSON(json: any): UserUpdateRequest {
    return UserUpdateRequestFromJSONTyped(json, false);
}

export function UserUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'drivingLicenses': ((json['driving_licenses'] as Array<any>).map(DrivingLicenseFromJSON)),
        'employeeId': json['employee_id'] == null ? undefined : json['employee_id'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'status': UserStatusFromJSON(json['status']),
        'wateringPlanSelectable': json['watering_plan_selectable'],
    };
}

export function UserUpdateRequestToJSON(json: any): UserUpdateRequest {
    return UserUpdateRequestToJSONTyped(json, false);
}

export function UserUpdateRequestToJSONTyped(value?: UserUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'driving_licenses': ((value['drivingLicenses'] as Array<any>).map(DrivingLicenseToJSON)),
        'employee_id': value['employeeId'],
        'phone_number': value['phoneNumber'],
        'status': UserStatusToJSON(value['status']),
        'watering_plan_selectable': value['wateringPlanSelectable'],
    };
}

