/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * Request body for registering a new user.
 * @export
 * @interface UserRegisterRequest
 */
export interface UserRegisterRequest {
    /**
     * Optional URL to the user's avatar image.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    avatarUrl?: string | null;
    /**
     * Initial driving licenses.
     * @type {Array<DrivingLicense>}
     * @memberof UserRegisterRequest
     */
    drivingLicenses?: Array<DrivingLicense>;
    /**
     * Email address.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    email: string;
    /**
     * Optional internal employee identifier.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    employeeId?: string | null;
    /**
     * User's first name.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    firstName: string;
    /**
     * User's last name.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    lastName: string;
    /**
     * Organization the new user belongs to.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    organizationId: string;
    /**
     * Password for the new account.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    password: string;
    /**
     * Optional contact phone number.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    phoneNumber?: string | null;
    /**
     * Roles to assign to the user (must be org-owned, not templates).
     * @type {Array<string>}
     * @memberof UserRegisterRequest
     */
    roleIds?: Array<string>;
    /**
     * Initial availability status (defaults to Available).
     * @type {UserStatus}
     * @memberof UserRegisterRequest
     */
    status?: UserStatus | null;
    /**
     * Desired login username.
     * @type {string}
     * @memberof UserRegisterRequest
     */
    username: string;
    /**
     * Whether the new user may be assigned to watering plans (defaults to true).
     * @type {boolean}
     * @memberof UserRegisterRequest
     */
    wateringPlanSelectable?: boolean | null;
}



/**
 * Check if a given object implements the UserRegisterRequest interface.
 */
export function instanceOfUserRegisterRequest(value: object): value is UserRegisterRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserRegisterRequestFromJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestFromJSONTyped(json, false);
}

export function UserRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'drivingLicenses': json['driving_licenses'] == null ? undefined : ((json['driving_licenses'] as Array<any>).map(DrivingLicenseFromJSON)),
        'email': json['email'],
        'employeeId': json['employee_id'] == null ? undefined : json['employee_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'organizationId': json['organization_id'],
        'password': json['password'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'roleIds': json['role_ids'] == null ? undefined : json['role_ids'],
        'status': json['status'] == null ? undefined : UserStatusFromJSON(json['status']),
        'username': json['username'],
        'wateringPlanSelectable': json['watering_plan_selectable'] == null ? undefined : json['watering_plan_selectable'],
    };
}

export function UserRegisterRequestToJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestToJSONTyped(json, false);
}

export function UserRegisterRequestToJSONTyped(value?: UserRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'driving_licenses': value['drivingLicenses'] == null ? undefined : ((value['drivingLicenses'] as Array<any>).map(DrivingLicenseToJSON)),
        'email': value['email'],
        'employee_id': value['employeeId'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'organization_id': value['organizationId'],
        'password': value['password'],
        'phone_number': value['phoneNumber'],
        'role_ids': value['roleIds'],
        'status': UserStatusToJSON(value['status']),
        'username': value['username'],
        'watering_plan_selectable': value['wateringPlanSelectable'],
    };
}

