/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * OpenAPI shape of [`ValidationIssue`].
 * 
 * A mirror rather than a derive on the domain type: the domain crate must
 * build without utoipa, so the schema cannot live next to the struct. Keep the
 * fields in step with `domain::shared::error::ValidationIssue`.
 * @export
 * @interface ValidationIssue
 */
export interface ValidationIssue {
    /**
     * Namespaced domain field label.
     * @type {string}
     * @memberof ValidationIssue
     */
    field: string;
    /**
     * Translation key, `{field}.{violated rule}`.
     * @type {string}
     * @memberof ValidationIssue
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof ValidationIssue
     */
    params: any | null;
}

/**
 * Check if a given object implements the ValidationIssue interface.
 */
export function instanceOfValidationIssue(value: object): value is ValidationIssue {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    return true;
}

export function ValidationIssueFromJSON(json: any): ValidationIssue {
    return ValidationIssueFromJSONTyped(json, false);
}

export function ValidationIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'key': json['key'],
        'params': json['params'],
    };
}

export function ValidationIssueToJSON(json: any): ValidationIssue {
    return ValidationIssueToJSONTyped(json, false);
}

export function ValidationIssueToJSONTyped(value?: ValidationIssue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'key': value['key'],
        'params': value['params'],
    };
}

