/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Evaluation metrics for a single vehicle.
 * @export
 * @interface VehicleEvaluationResponse
 */
export interface VehicleEvaluationResponse {
    /**
     * License plate number of the vehicle.
     * @type {string}
     * @memberof VehicleEvaluationResponse
     */
    numberPlate: string;
    /**
     * Number of watering plans this vehicle has been assigned to.
     * @type {number}
     * @memberof VehicleEvaluationResponse
     */
    wateringPlanCount: number;
}

/**
 * Check if a given object implements the VehicleEvaluationResponse interface.
 */
export function instanceOfVehicleEvaluationResponse(value: object): value is VehicleEvaluationResponse {
    if (!('numberPlate' in value) || value['numberPlate'] === undefined) return false;
    if (!('wateringPlanCount' in value) || value['wateringPlanCount'] === undefined) return false;
    return true;
}

export function VehicleEvaluationResponseFromJSON(json: any): VehicleEvaluationResponse {
    return VehicleEvaluationResponseFromJSONTyped(json, false);
}

export function VehicleEvaluationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleEvaluationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'numberPlate': json['number_plate'],
        'wateringPlanCount': json['watering_plan_count'],
    };
}

export function VehicleEvaluationResponseToJSON(json: any): VehicleEvaluationResponse {
    return VehicleEvaluationResponseToJSONTyped(json, false);
}

export function VehicleEvaluationResponseToJSONTyped(value?: VehicleEvaluationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number_plate': value['numberPlate'],
        'watering_plan_count': value['wateringPlanCount'],
    };
}

