/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Operational status of a watering vehicle. Read-only: derived from the
 * vehicle's availability and the watering plans it is assigned to.
 * @export
 */
export const VehicleStatus = {
    Active: 'active',
    Available: 'available',
    NotAvailable: 'not_available'
} as const;
export type VehicleStatus = typeof VehicleStatus[keyof typeof VehicleStatus];


export function instanceOfVehicleStatus(value: any): boolean {
    for (const key in VehicleStatus) {
        if (Object.prototype.hasOwnProperty.call(VehicleStatus, key)) {
            if (VehicleStatus[key as keyof typeof VehicleStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VehicleStatusFromJSON(json: any): VehicleStatus {
    return VehicleStatusFromJSONTyped(json, false);
}

export function VehicleStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleStatus {
    return json as VehicleStatus;
}

export function VehicleStatusToJSON(value?: VehicleStatus | null): any {
    return value as any;
}

export function VehicleStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): VehicleStatus {
    return value as VehicleStatus;
}

