/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
    VehicleTypeToJSONTyped,
} from './VehicleType';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { VehicleAvailability } from './VehicleAvailability';
import {
    VehicleAvailabilityFromJSON,
    VehicleAvailabilityFromJSONTyped,
    VehicleAvailabilityToJSON,
    VehicleAvailabilityToJSONTyped,
} from './VehicleAvailability';
import type { VehicleStatus } from './VehicleStatus';
import {
    VehicleStatusFromJSON,
    VehicleStatusFromJSONTyped,
    VehicleStatusToJSON,
    VehicleStatusToJSONTyped,
} from './VehicleStatus';

/**
 * Represents a watering vehicle used for urban green-space irrigation.
 * @export
 * @interface VehicleResponse
 */
export interface VehicleResponse {
    /**
     * Arbitrary additional metadata from the provider.
     * @type {object}
     * @memberof VehicleResponse
     */
    additionalInformation?: object | null;
    /**
     * Timestamp when the vehicle was archived, if applicable (RFC 3339).
     * @type {string}
     * @memberof VehicleResponse
     */
    archivedAt?: string | null;
    /**
     * Whether the vehicle may be assigned to a watering plan.
     * @type {VehicleAvailability}
     * @memberof VehicleResponse
     */
    availability: VehicleAvailability;
    /**
     * Timestamp when the vehicle was created (RFC 3339).
     * @type {string}
     * @memberof VehicleResponse
     */
    createdAt: string;
    /**
     * Human-readable description of the vehicle.
     * @type {string}
     * @memberof VehicleResponse
     */
    description: string;
    /**
     * Required driving license class to operate this vehicle.
     * @type {DrivingLicense}
     * @memberof VehicleResponse
     */
    drivingLicense: DrivingLicense;
    /**
     * Vehicle height in meters.
     * @type {number}
     * @memberof VehicleResponse
     */
    height: number;
    /**
     * Unique identifier of the vehicle.
     * @type {string}
     * @memberof VehicleResponse
     */
    id: string;
    /**
     * Vehicle length in meters.
     * @type {number}
     * @memberof VehicleResponse
     */
    length: number;
    /**
     * Manufacturer and model name.
     * @type {string}
     * @memberof VehicleResponse
     */
    model: string;
    /**
     * Official license plate number of the vehicle.
     * @type {string}
     * @memberof VehicleResponse
     */
    numberPlate: string;
    /**
     * Organization this vehicle belongs to.
     * @type {string}
     * @memberof VehicleResponse
     */
    organizationId: string;
    /**
     * Name of the external data provider that supplied this vehicle record.
     * @type {string}
     * @memberof VehicleResponse
     */
    provider?: string | null;
    /**
     * Operational status. Read-only: derived from `availability` and the
     * watering plans the vehicle is assigned to.
     * @type {VehicleStatus}
     * @memberof VehicleResponse
     */
    status: VehicleStatus;
    /**
     * Type/category of the vehicle.
     * @type {VehicleType}
     * @memberof VehicleResponse
     */
    type: VehicleType;
    /**
     * Timestamp when the vehicle was last updated (RFC 3339).
     * @type {string}
     * @memberof VehicleResponse
     */
    updatedAt: string;
    /**
     * Water tank capacity in liters.
     * @type {number}
     * @memberof VehicleResponse
     */
    waterCapacity: number;
    /**
     * Vehicle weight in kilograms.
     * @type {number}
     * @memberof VehicleResponse
     */
    weight: number;
    /**
     * Vehicle width in meters.
     * @type {number}
     * @memberof VehicleResponse
     */
    width: number;
}



/**
 * Check if a given object implements the VehicleResponse interface.
 */
export function instanceOfVehicleResponse(value: object): value is VehicleResponse {
    if (!('availability' in value) || value['availability'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('drivingLicense' in value) || value['drivingLicense'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('numberPlate' in value) || value['numberPlate'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('waterCapacity' in value) || value['waterCapacity'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function VehicleResponseFromJSON(json: any): VehicleResponse {
    return VehicleResponseFromJSONTyped(json, false);
}

export function VehicleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'archivedAt': json['archived_at'] == null ? undefined : json['archived_at'],
        'availability': VehicleAvailabilityFromJSON(json['availability']),
        'createdAt': json['created_at'],
        'description': json['description'],
        'drivingLicense': DrivingLicenseFromJSON(json['driving_license']),
        'height': json['height'],
        'id': json['id'],
        'length': json['length'],
        'model': json['model'],
        'numberPlate': json['number_plate'],
        'organizationId': json['organization_id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': VehicleStatusFromJSON(json['status']),
        'type': VehicleTypeFromJSON(json['type']),
        'updatedAt': json['updated_at'],
        'waterCapacity': json['water_capacity'],
        'weight': json['weight'],
        'width': json['width'],
    };
}

export function VehicleResponseToJSON(json: any): VehicleResponse {
    return VehicleResponseToJSONTyped(json, false);
}

export function VehicleResponseToJSONTyped(value?: VehicleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'archived_at': value['archivedAt'],
        'availability': VehicleAvailabilityToJSON(value['availability']),
        'created_at': value['createdAt'],
        'description': value['description'],
        'driving_license': DrivingLicenseToJSON(value['drivingLicense']),
        'height': value['height'],
        'id': value['id'],
        'length': value['length'],
        'model': value['model'],
        'number_plate': value['numberPlate'],
        'organization_id': value['organizationId'],
        'provider': value['provider'],
        'status': VehicleStatusToJSON(value['status']),
        'type': VehicleTypeToJSON(value['type']),
        'updated_at': value['updatedAt'],
        'water_capacity': value['waterCapacity'],
        'weight': value['weight'],
        'width': value['width'],
    };
}

