/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
    VehicleTypeToJSONTyped,
} from './VehicleType';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { VehicleAvailability } from './VehicleAvailability';
import {
    VehicleAvailabilityFromJSON,
    VehicleAvailabilityFromJSONTyped,
    VehicleAvailabilityToJSON,
    VehicleAvailabilityToJSONTyped,
} from './VehicleAvailability';

/**
 * Request body for updating an existing watering vehicle.
 * @export
 * @interface VehicleUpdateRequest
 */
export interface VehicleUpdateRequest {
    /**
     * Arbitrary additional metadata from the provider.
     * @type {object}
     * @memberof VehicleUpdateRequest
     */
    additionalInformation?: object | null;
    /**
     * Whether the vehicle may be assigned to a watering plan.
     * @type {VehicleAvailability}
     * @memberof VehicleUpdateRequest
     */
    availability: VehicleAvailability;
    /**
     * Human-readable description of the vehicle.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    description?: string | null;
    /**
     * Required driving license class to operate this vehicle.
     * @type {DrivingLicense}
     * @memberof VehicleUpdateRequest
     */
    drivingLicense: DrivingLicense;
    /**
     * Vehicle height in meters.
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    height: number;
    /**
     * Vehicle length in meters.
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    length: number;
    /**
     * Manufacturer and model name.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    model: string;
    /**
     * Official license plate number of the vehicle.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    numberPlate: string;
    /**
     * Name of the external data provider that supplied this vehicle record.
     * @type {string}
     * @memberof VehicleUpdateRequest
     */
    provider?: string | null;
    /**
     * Type/category of the vehicle.
     * @type {VehicleType}
     * @memberof VehicleUpdateRequest
     */
    type: VehicleType;
    /**
     * Water tank capacity in liters.
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    waterCapacity: number;
    /**
     * Vehicle weight in kilograms.
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    weight: number;
    /**
     * Vehicle width in meters.
     * @type {number}
     * @memberof VehicleUpdateRequest
     */
    width: number;
}



/**
 * Check if a given object implements the VehicleUpdateRequest interface.
 */
export function instanceOfVehicleUpdateRequest(value: object): value is VehicleUpdateRequest {
    if (!('availability' in value) || value['availability'] === undefined) return false;
    if (!('drivingLicense' in value) || value['drivingLicense'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('numberPlate' in value) || value['numberPlate'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('waterCapacity' in value) || value['waterCapacity'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function VehicleUpdateRequestFromJSON(json: any): VehicleUpdateRequest {
    return VehicleUpdateRequestFromJSONTyped(json, false);
}

export function VehicleUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'availability': VehicleAvailabilityFromJSON(json['availability']),
        'description': json['description'] == null ? undefined : json['description'],
        'drivingLicense': DrivingLicenseFromJSON(json['driving_license']),
        'height': json['height'],
        'length': json['length'],
        'model': json['model'],
        'numberPlate': json['number_plate'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'type': VehicleTypeFromJSON(json['type']),
        'waterCapacity': json['water_capacity'],
        'weight': json['weight'],
        'width': json['width'],
    };
}

export function VehicleUpdateRequestToJSON(json: any): VehicleUpdateRequest {
    return VehicleUpdateRequestToJSONTyped(json, false);
}

export function VehicleUpdateRequestToJSONTyped(value?: VehicleUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'availability': VehicleAvailabilityToJSON(value['availability']),
        'description': value['description'],
        'driving_license': DrivingLicenseToJSON(value['drivingLicense']),
        'height': value['height'],
        'length': value['length'],
        'model': value['model'],
        'number_plate': value['numberPlate'],
        'provider': value['provider'],
        'type': VehicleTypeToJSON(value['type']),
        'water_capacity': value['waterCapacity'],
        'weight': value['weight'],
        'width': value['width'],
    };
}

