/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
    VehicleTypeToJSONTyped,
} from './VehicleType';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { VehicleAvailability } from './VehicleAvailability';
import {
    VehicleAvailabilityFromJSON,
    VehicleAvailabilityFromJSONTyped,
    VehicleAvailabilityToJSON,
    VehicleAvailabilityToJSONTyped,
} from './VehicleAvailability';

/**
 * Request body for creating a new watering vehicle.
 * @export
 * @interface VehicleCreateRequest
 */
export interface VehicleCreateRequest {
    /**
     * Arbitrary additional metadata from the provider.
     * @type {object}
     * @memberof VehicleCreateRequest
     */
    additionalInformation?: object | null;
    /**
     * Whether the vehicle may be assigned to a watering plan.
     * @type {VehicleAvailability}
     * @memberof VehicleCreateRequest
     */
    availability: VehicleAvailability;
    /**
     * Human-readable description of the vehicle.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    description?: string | null;
    /**
     * Required driving license class to operate this vehicle.
     * @type {DrivingLicense}
     * @memberof VehicleCreateRequest
     */
    drivingLicense: DrivingLicense;
    /**
     * Vehicle height in meters.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    height: number;
    /**
     * Vehicle length in meters.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    length: number;
    /**
     * Manufacturer and model name.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    model: string;
    /**
     * Official license plate number of the vehicle.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    numberPlate: string;
    /**
     * Organization this vehicle belongs to. Defaults to the acting user's
     * own organization (or the root organization in the demo bypass).
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    organizationId?: string | null;
    /**
     * Name of the external data provider that supplied this vehicle record.
     * @type {string}
     * @memberof VehicleCreateRequest
     */
    provider?: string | null;
    /**
     * Type/category of the vehicle.
     * @type {VehicleType}
     * @memberof VehicleCreateRequest
     */
    type: VehicleType;
    /**
     * Water tank capacity in liters.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    waterCapacity: number;
    /**
     * Vehicle weight in kilograms.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    weight: number;
    /**
     * Vehicle width in meters.
     * @type {number}
     * @memberof VehicleCreateRequest
     */
    width: number;
}



/**
 * Check if a given object implements the VehicleCreateRequest interface.
 */
export function instanceOfVehicleCreateRequest(value: object): value is VehicleCreateRequest {
    if (!('availability' in value) || value['availability'] === undefined) return false;
    if (!('drivingLicense' in value) || value['drivingLicense'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('numberPlate' in value) || value['numberPlate'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('waterCapacity' in value) || value['waterCapacity'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function VehicleCreateRequestFromJSON(json: any): VehicleCreateRequest {
    return VehicleCreateRequestFromJSONTyped(json, false);
}

export function VehicleCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'availability': VehicleAvailabilityFromJSON(json['availability']),
        'description': json['description'] == null ? undefined : json['description'],
        'drivingLicense': DrivingLicenseFromJSON(json['driving_license']),
        'height': json['height'],
        'length': json['length'],
        'model': json['model'],
        'numberPlate': json['number_plate'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'type': VehicleTypeFromJSON(json['type']),
        'waterCapacity': json['water_capacity'],
        'weight': json['weight'],
        'width': json['width'],
    };
}

export function VehicleCreateRequestToJSON(json: any): VehicleCreateRequest {
    return VehicleCreateRequestToJSONTyped(json, false);
}

export function VehicleCreateRequestToJSONTyped(value?: VehicleCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'availability': VehicleAvailabilityToJSON(value['availability']),
        'description': value['description'],
        'driving_license': DrivingLicenseToJSON(value['drivingLicense']),
        'height': value['height'],
        'length': value['length'],
        'model': value['model'],
        'number_plate': value['numberPlate'],
        'organization_id': value['organizationId'],
        'provider': value['provider'],
        'type': VehicleTypeToJSON(value['type']),
        'water_capacity': value['waterCapacity'],
        'weight': value['weight'],
        'width': value['width'],
    };
}

