/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for creating a new watering plan.
 * @export
 * @interface WateringPlanCreateRequest
 */
export interface WateringPlanCreateRequest {
    /**
     * Arbitrary additional metadata from the provider.
     * @type {object}
     * @memberof WateringPlanCreateRequest
     */
    additionalInformation?: object | null;
    /**
     * Scheduled date and time of the watering run (RFC 3339).
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    date: string;
    /**
     * Human-readable description of the watering plan.
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    description: string;
    /**
     * Organization this watering plan belongs to. Defaults to the acting
     * user's own organization when omitted.
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    organizationId?: string | null;
    /**
     * Name of the external data provider that supplied this record.
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    provider?: string | null;
    /**
     * Name of the configured start point to depart from and return to. Unknown names fall back to the default depot.
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    startPointName?: string | null;
    /**
     * Identifier of the trailer vehicle to use, if any.
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    trailerId?: string | null;
    /**
     * Identifier of the transporter vehicle to use.
     * @type {string}
     * @memberof WateringPlanCreateRequest
     */
    transporterId: string;
    /**
     * List of tree cluster identifiers to include in the plan.
     * @type {Array<string>}
     * @memberof WateringPlanCreateRequest
     */
    treeClusterIds: Array<string>;
    /**
     * List of user identifiers assigned to execute this plan.
     * @type {Array<string>}
     * @memberof WateringPlanCreateRequest
     */
    userIds: Array<string>;
}

/**
 * Check if a given object implements the WateringPlanCreateRequest interface.
 */
export function instanceOfWateringPlanCreateRequest(value: object): value is WateringPlanCreateRequest {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('transporterId' in value) || value['transporterId'] === undefined) return false;
    if (!('treeClusterIds' in value) || value['treeClusterIds'] === undefined) return false;
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function WateringPlanCreateRequestFromJSON(json: any): WateringPlanCreateRequest {
    return WateringPlanCreateRequestFromJSONTyped(json, false);
}

export function WateringPlanCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WateringPlanCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'date': json['date'],
        'description': json['description'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'startPointName': json['start_point_name'] == null ? undefined : json['start_point_name'],
        'trailerId': json['trailer_id'] == null ? undefined : json['trailer_id'],
        'transporterId': json['transporter_id'],
        'treeClusterIds': json['tree_cluster_ids'],
        'userIds': json['user_ids'],
    };
}

export function WateringPlanCreateRequestToJSON(json: any): WateringPlanCreateRequest {
    return WateringPlanCreateRequestToJSONTyped(json, false);
}

export function WateringPlanCreateRequestToJSONTyped(value?: WateringPlanCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'date': value['date'],
        'description': value['description'],
        'organization_id': value['organizationId'],
        'provider': value['provider'],
        'start_point_name': value['startPointName'],
        'trailer_id': value['trailerId'],
        'transporter_id': value['transporterId'],
        'tree_cluster_ids': value['treeClusterIds'],
        'user_ids': value['userIds'],
    };
}

