/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lifecycle status of a watering plan.
 * @export
 */
export const WateringPlanStatus = {
    Planned: 'planned',
    Active: 'active',
    Canceled: 'canceled',
    Finished: 'finished',
    NotCompleted: 'not_completed'
} as const;
export type WateringPlanStatus = typeof WateringPlanStatus[keyof typeof WateringPlanStatus];


export function instanceOfWateringPlanStatus(value: any): boolean {
    for (const key in WateringPlanStatus) {
        if (Object.prototype.hasOwnProperty.call(WateringPlanStatus, key)) {
            if (WateringPlanStatus[key as keyof typeof WateringPlanStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WateringPlanStatusFromJSON(json: any): WateringPlanStatus {
    return WateringPlanStatusFromJSONTyped(json, false);
}

export function WateringPlanStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WateringPlanStatus {
    return json as WateringPlanStatus;
}

export function WateringPlanStatusToJSON(value?: WateringPlanStatus | null): any {
    return value as any;
}

export function WateringPlanStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WateringPlanStatus {
    return value as WateringPlanStatus;
}

