/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TreeClusterInListResponse } from './TreeClusterInListResponse';
import {
    TreeClusterInListResponseFromJSON,
    TreeClusterInListResponseFromJSONTyped,
    TreeClusterInListResponseToJSON,
    TreeClusterInListResponseToJSONTyped,
} from './TreeClusterInListResponse';
import type { VehicleResponse } from './VehicleResponse';
import {
    VehicleResponseFromJSON,
    VehicleResponseFromJSONTyped,
    VehicleResponseToJSON,
    VehicleResponseToJSONTyped,
} from './VehicleResponse';
import type { WateringPlanStatus } from './WateringPlanStatus';
import {
    WateringPlanStatusFromJSON,
    WateringPlanStatusFromJSONTyped,
    WateringPlanStatusToJSON,
    WateringPlanStatusToJSONTyped,
} from './WateringPlanStatus';

/**
 * Compact representation of a watering plan used in list endpoints.
 * @export
 * @interface WateringPlanInListResponse
 */
export interface WateringPlanInListResponse {
    /**
     * Arbitrary additional metadata from the provider.
     * @type {object}
     * @memberof WateringPlanInListResponse
     */
    additionalInformation?: object | null;
    /**
     * Reason for cancellation, empty if not cancelled.
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    cancellationNote: string;
    /**
     * Timestamp when the watering plan was created (RFC 3339).
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    createdAt: string;
    /**
     * Scheduled date and time of the watering run (RFC 3339).
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    date: string;
    /**
     * Human-readable description of the watering plan.
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    description: string;
    /**
     * Total route distance in meters.
     * @type {number}
     * @memberof WateringPlanInListResponse
     */
    distance: number;
    /**
     * Unique identifier of the watering plan.
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    id: string;
    /**
     * Name of the external data provider that supplied this record.
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    provider?: string | null;
    /**
     * Current status of the watering plan.
     * @type {WateringPlanStatus}
     * @memberof WateringPlanInListResponse
     */
    status: WateringPlanStatus;
    /**
     * Total amount of water required for all clusters in liters.
     * @type {number}
     * @memberof WateringPlanInListResponse
     */
    totalWaterRequired: number;
    /**
     * The trailer vehicle assigned to this plan, if any.
     * @type {VehicleResponse}
     * @memberof WateringPlanInListResponse
     */
    trailer?: VehicleResponse | null;
    /**
     * The transporter vehicle assigned to this plan.
     * @type {VehicleResponse}
     * @memberof WateringPlanInListResponse
     */
    transporter: VehicleResponse;
    /**
     * Tree clusters included in this watering plan.
     * @type {Array<TreeClusterInListResponse>}
     * @memberof WateringPlanInListResponse
     */
    treeclusters: Array<TreeClusterInListResponse>;
    /**
     * Timestamp when the watering plan was last updated (RFC 3339).
     * @type {string}
     * @memberof WateringPlanInListResponse
     */
    updatedAt: string;
    /**
     * List of user identifiers assigned to execute this plan.
     * @type {Array<string>}
     * @memberof WateringPlanInListResponse
     */
    userIds: Array<string>;
}



/**
 * Check if a given object implements the WateringPlanInListResponse interface.
 */
export function instanceOfWateringPlanInListResponse(value: object): value is WateringPlanInListResponse {
    if (!('cancellationNote' in value) || value['cancellationNote'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalWaterRequired' in value) || value['totalWaterRequired'] === undefined) return false;
    if (!('transporter' in value) || value['transporter'] === undefined) return false;
    if (!('treeclusters' in value) || value['treeclusters'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function WateringPlanInListResponseFromJSON(json: any): WateringPlanInListResponse {
    return WateringPlanInListResponseFromJSONTyped(json, false);
}

export function WateringPlanInListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WateringPlanInListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'cancellationNote': json['cancellation_note'],
        'createdAt': json['created_at'],
        'date': json['date'],
        'description': json['description'],
        'distance': json['distance'],
        'id': json['id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': WateringPlanStatusFromJSON(json['status']),
        'totalWaterRequired': json['total_water_required'],
        'trailer': json['trailer'] == null ? undefined : VehicleResponseFromJSON(json['trailer']),
        'transporter': VehicleResponseFromJSON(json['transporter']),
        'treeclusters': ((json['treeclusters'] as Array<any>).map(TreeClusterInListResponseFromJSON)),
        'updatedAt': json['updated_at'],
        'userIds': json['user_ids'],
    };
}

export function WateringPlanInListResponseToJSON(json: any): WateringPlanInListResponse {
    return WateringPlanInListResponseToJSONTyped(json, false);
}

export function WateringPlanInListResponseToJSONTyped(value?: WateringPlanInListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'cancellation_note': value['cancellationNote'],
        'created_at': value['createdAt'],
        'date': value['date'],
        'description': value['description'],
        'distance': value['distance'],
        'id': value['id'],
        'provider': value['provider'],
        'status': WateringPlanStatusToJSON(value['status']),
        'total_water_required': value['totalWaterRequired'],
        'trailer': VehicleResponseToJSON(value['trailer']),
        'transporter': VehicleResponseToJSON(value['transporter']),
        'treeclusters': ((value['treeclusters'] as Array<any>).map(TreeClusterInListResponseToJSON)),
        'updated_at': value['updatedAt'],
        'user_ids': value['userIds'],
    };
}

