FROM alpine:3.18

RUN apk add --no-cache bash curl
RUN curl -fsSL \
    https://raw.githubusercontent.com/pressly/goose/master/install.sh |\
    sh

COPY ./green-ecolution-backend/internal/storage/postgres/migrations /migrations
COPY ./.docker/migrations/migration.sh /migrations/entrypoint.sh

RUN chmod +x /migrations/entrypoint.sh

CMD ["/migrations/entrypoint.sh"]
