/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedDebugRouteRouteImport } from './routes/_protected/debug/route'
import { Route as ProtectedEvaluationsRouteRouteImport } from './routes/_protected/evaluations/route'
import { Route as ProtectedInfoRouteImport } from './routes/_protected/info'
import { Route as ProtectedMapRouteRouteImport } from './routes/_protected/map/route'
import { Route as ProtectedSensorsRouteRouteImport } from './routes/_protected/sensors/route'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as ProtectedTreeclusterRouteRouteImport } from './routes/_protected/treecluster/route'
import { Route as ProtectedTreesRouteRouteImport } from './routes/_protected/trees/route'
import { Route as ProtectedVehiclesRouteRouteImport } from './routes/_protected/vehicles/route'
import { Route as ProtectedWateringPlansRouteRouteImport } from './routes/_protected/watering-plans/route'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as HelpSlugRouteImport } from './routes/help/$slug'
import { Route as ProtectedDebugIndexRouteImport } from './routes/_protected/debug/index'
import { Route as ProtectedEvaluationsIndexRouteImport } from './routes/_protected/evaluations/index'
import { Route as ProtectedMapIndexRouteImport } from './routes/_protected/map/index'
import { Route as ProtectedSensorsIndexRouteImport } from './routes/_protected/sensors/index'
import { Route as ProtectedSensorsSensorIdRouteRouteImport } from './routes/_protected/sensors/$sensorId/route'
import { Route as ProtectedSensorsNewRouteRouteImport } from './routes/_protected/sensors/new/route'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSettingsPluginRouteRouteImport } from './routes/_protected/settings/plugin/route'
import { Route as ProtectedSettingsTeamRouteRouteImport } from './routes/_protected/settings/team/route'
import { Route as ProtectedTreeclusterIndexRouteImport } from './routes/_protected/treecluster/index'
import { Route as ProtectedTreeclusterTreeclusterIdRouteRouteImport } from './routes/_protected/treecluster/$treeclusterId/route'
import { Route as ProtectedTreesIndexRouteImport } from './routes/_protected/trees/index'
import { Route as ProtectedTreesTreeIdRouteRouteImport } from './routes/_protected/trees/$treeId/route'
import { Route as ProtectedVehiclesIndexRouteImport } from './routes/_protected/vehicles/index'
import { Route as ProtectedVehiclesVehicleIdRouteRouteImport } from './routes/_protected/vehicles/$vehicleId/route'
import { Route as ProtectedWateringPlansIndexRouteImport } from './routes/_protected/watering-plans/index'
import { Route as ProtectedWateringPlansWateringPlanIdRouteRouteImport } from './routes/_protected/watering-plans/$wateringPlanId/route'
import { Route as ProtectedDebugGeolocationIndexRouteImport } from './routes/_protected/debug/geolocation/index'
import { Route as ProtectedDebugQrScannerIndexRouteImport } from './routes/_protected/debug/qr-scanner/index'
import { Route as ProtectedMapTreeNewRouteRouteImport } from './routes/_protected/map/tree/new/route'
import { Route as ProtectedSensorsSensorIdIndexRouteImport } from './routes/_protected/sensors/$sensorId/index'
import { Route as ProtectedSensorsNewIndexRouteImport } from './routes/_protected/sensors/new/index'
import { Route as ProtectedSettingsIrrigationIndexRouteImport } from './routes/_protected/settings/irrigation/index'
import { Route as ProtectedSettingsMapIndexRouteImport } from './routes/_protected/settings/map/index'
import { Route as ProtectedSettingsNotificationsIndexRouteImport } from './routes/_protected/settings/notifications/index'
import { Route as ProtectedSettingsOrganizationIndexRouteImport } from './routes/_protected/settings/organization/index'
import { Route as ProtectedSettingsPluginIndexRouteImport } from './routes/_protected/settings/plugin/index'
import { Route as ProtectedSettingsPluginPluginNameRouteRouteImport } from './routes/_protected/settings/plugin/$pluginName/route'
import { Route as ProtectedSettingsProfileIndexRouteImport } from './routes/_protected/settings/profile/index'
import { Route as ProtectedSettingsSensorsIndexRouteImport } from './routes/_protected/settings/sensors/index'
import { Route as ProtectedSettingsTeamIndexRouteImport } from './routes/_protected/settings/team/index'
import { Route as ProtectedTreeclusterTreeclusterIdIndexRouteImport } from './routes/_protected/treecluster/$treeclusterId/index'
import { Route as ProtectedTreesTreeIdIndexRouteImport } from './routes/_protected/trees/$treeId/index'
import { Route as ProtectedVehiclesVehicleIdIndexRouteImport } from './routes/_protected/vehicles/$vehicleId/index'
import { Route as ProtectedVehiclesFormularVehicleIdRouteRouteImport } from './routes/_protected/vehicles/_formular/$vehicleId/route'
import { Route as ProtectedVehiclesFormularNewRouteRouteImport } from './routes/_protected/vehicles/_formular/new/route'
import { Route as ProtectedWateringPlansWateringPlanIdIndexRouteImport } from './routes/_protected/watering-plans/$wateringPlanId/index'
import { Route as ProtectedWateringPlansFormularWateringPlanIdRouteRouteImport } from './routes/_protected/watering-plans/_formular/$wateringPlanId/route'
import { Route as ProtectedWateringPlansFormularNewRouteRouteImport } from './routes/_protected/watering-plans/_formular/new/route'
import { Route as ProtectedMapTreeNewIndexRouteImport } from './routes/_protected/map/tree/new/index'
import { Route as ProtectedMapTreeclusterNewIndexRouteImport } from './routes/_protected/map/treecluster/new/index'
import { Route as ProtectedMapWateringPlanSelectClusterRouteRouteImport } from './routes/_protected/map/watering-plan/select/cluster/route'
import { Route as ProtectedSettingsPluginPluginNameIndexRouteImport } from './routes/_protected/settings/plugin/$pluginName/index'
import { Route as ProtectedSettingsTeamMembersIndexRouteImport } from './routes/_protected/settings/team/members/index'
import { Route as ProtectedSettingsTeamRolesIndexRouteImport } from './routes/_protected/settings/team/roles/index'
import { Route as ProtectedVehiclesFormularVehicleIdEditRouteRouteImport } from './routes/_protected/vehicles/_formular/$vehicleId/edit/route'
import { Route as ProtectedVehiclesFormularNewIndexRouteImport } from './routes/_protected/vehicles/_formular/new/index'
import { Route as ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteImport } from './routes/_protected/watering-plans/_formular/$wateringPlanId/edit/route'
import { Route as ProtectedWateringPlansFormularNewIndexRouteImport } from './routes/_protected/watering-plans/_formular/new/index'
import { Route as ProtectedMapTreeEditTreeIdIndexRouteImport } from './routes/_protected/map/tree/edit/$treeId/index'
import { Route as ProtectedMapTreeclusterEditTreeclusterIdIndexRouteImport } from './routes/_protected/map/treecluster/edit/$treeclusterId/index'
import { Route as ProtectedMapWateringPlanSelectClusterIndexRouteImport } from './routes/_protected/map/watering-plan/select/cluster/index'
import { Route as ProtectedVehiclesFormularVehicleIdEditIndexRouteImport } from './routes/_protected/vehicles/_formular/$vehicleId/edit/index'
import { Route as ProtectedWateringPlansFormularWateringPlanIdEditIndexRouteImport } from './routes/_protected/watering-plans/_formular/$wateringPlanId/edit/index'
import { Route as ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteImport } from './routes/_protected/watering-plans/_formular/$wateringPlanId/status/edit/route'
import { Route as ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRouteImport } from './routes/_protected/watering-plans/_formular/$wateringPlanId/status/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebugRouteRoute = ProtectedDebugRouteRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEvaluationsRouteRoute =
  ProtectedEvaluationsRouteRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInfoRoute = ProtectedInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMapRouteRoute = ProtectedMapRouteRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSensorsRouteRoute = ProtectedSensorsRouteRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTreeclusterRouteRoute =
  ProtectedTreeclusterRouteRouteImport.update({
    id: '/treecluster',
    path: '/treecluster',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTreesRouteRoute = ProtectedTreesRouteRouteImport.update({
  id: '/trees',
  path: '/trees',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVehiclesRouteRoute = ProtectedVehiclesRouteRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWateringPlansRouteRoute =
  ProtectedWateringPlansRouteRouteImport.update({
    id: '/watering-plans',
    path: '/watering-plans',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSlugRoute = HelpSlugRouteImport.update({
  id: '/help/$slug',
  path: '/help/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDebugIndexRoute = ProtectedDebugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDebugRouteRoute,
} as any)
const ProtectedEvaluationsIndexRoute =
  ProtectedEvaluationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedEvaluationsRouteRoute,
  } as any)
const ProtectedMapIndexRoute = ProtectedMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedMapRouteRoute,
} as any)
const ProtectedSensorsIndexRoute = ProtectedSensorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSensorsRouteRoute,
} as any)
const ProtectedSensorsSensorIdRouteRoute =
  ProtectedSensorsSensorIdRouteRouteImport.update({
    id: '/$sensorId',
    path: '/$sensorId',
    getParentRoute: () => ProtectedSensorsRouteRoute,
  } as any)
const ProtectedSensorsNewRouteRoute =
  ProtectedSensorsNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedSensorsRouteRoute,
  } as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSettingsPluginRouteRoute =
  ProtectedSettingsPluginRouteRouteImport.update({
    id: '/plugin',
    path: '/plugin',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsTeamRouteRoute =
  ProtectedSettingsTeamRouteRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedTreeclusterIndexRoute =
  ProtectedTreeclusterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedTreeclusterRouteRoute,
  } as any)
const ProtectedTreeclusterTreeclusterIdRouteRoute =
  ProtectedTreeclusterTreeclusterIdRouteRouteImport.update({
    id: '/$treeclusterId',
    path: '/$treeclusterId',
    getParentRoute: () => ProtectedTreeclusterRouteRoute,
  } as any)
const ProtectedTreesIndexRoute = ProtectedTreesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedTreesRouteRoute,
} as any)
const ProtectedTreesTreeIdRouteRoute =
  ProtectedTreesTreeIdRouteRouteImport.update({
    id: '/$treeId',
    path: '/$treeId',
    getParentRoute: () => ProtectedTreesRouteRoute,
  } as any)
const ProtectedVehiclesIndexRoute = ProtectedVehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedVehiclesRouteRoute,
} as any)
const ProtectedVehiclesVehicleIdRouteRoute =
  ProtectedVehiclesVehicleIdRouteRouteImport.update({
    id: '/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => ProtectedVehiclesRouteRoute,
  } as any)
const ProtectedWateringPlansIndexRoute =
  ProtectedWateringPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWateringPlansRouteRoute,
  } as any)
const ProtectedWateringPlansWateringPlanIdRouteRoute =
  ProtectedWateringPlansWateringPlanIdRouteRouteImport.update({
    id: '/$wateringPlanId',
    path: '/$wateringPlanId',
    getParentRoute: () => ProtectedWateringPlansRouteRoute,
  } as any)
const ProtectedDebugGeolocationIndexRoute =
  ProtectedDebugGeolocationIndexRouteImport.update({
    id: '/geolocation/',
    path: '/geolocation/',
    getParentRoute: () => ProtectedDebugRouteRoute,
  } as any)
const ProtectedDebugQrScannerIndexRoute =
  ProtectedDebugQrScannerIndexRouteImport.update({
    id: '/qr-scanner/',
    path: '/qr-scanner/',
    getParentRoute: () => ProtectedDebugRouteRoute,
  } as any)
const ProtectedMapTreeNewRouteRoute =
  ProtectedMapTreeNewRouteRouteImport.update({
    id: '/tree/new',
    path: '/tree/new',
    getParentRoute: () => ProtectedMapRouteRoute,
  } as any)
const ProtectedSensorsSensorIdIndexRoute =
  ProtectedSensorsSensorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSensorsSensorIdRouteRoute,
  } as any)
const ProtectedSensorsNewIndexRoute =
  ProtectedSensorsNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSensorsNewRouteRoute,
  } as any)
const ProtectedSettingsIrrigationIndexRoute =
  ProtectedSettingsIrrigationIndexRouteImport.update({
    id: '/irrigation/',
    path: '/irrigation/',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsMapIndexRoute =
  ProtectedSettingsMapIndexRouteImport.update({
    id: '/map/',
    path: '/map/',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsNotificationsIndexRoute =
  ProtectedSettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsOrganizationIndexRoute =
  ProtectedSettingsOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsPluginIndexRoute =
  ProtectedSettingsPluginIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsPluginRouteRoute,
  } as any)
const ProtectedSettingsPluginPluginNameRouteRoute =
  ProtectedSettingsPluginPluginNameRouteRouteImport.update({
    id: '/$pluginName',
    path: '/$pluginName',
    getParentRoute: () => ProtectedSettingsPluginRouteRoute,
  } as any)
const ProtectedSettingsProfileIndexRoute =
  ProtectedSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsSensorsIndexRoute =
  ProtectedSettingsSensorsIndexRouteImport.update({
    id: '/sensors/',
    path: '/sensors/',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsTeamIndexRoute =
  ProtectedSettingsTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsTeamRouteRoute,
  } as any)
const ProtectedTreeclusterTreeclusterIdIndexRoute =
  ProtectedTreeclusterTreeclusterIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedTreeclusterTreeclusterIdRouteRoute,
  } as any)
const ProtectedTreesTreeIdIndexRoute =
  ProtectedTreesTreeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedTreesTreeIdRouteRoute,
  } as any)
const ProtectedVehiclesVehicleIdIndexRoute =
  ProtectedVehiclesVehicleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedVehiclesVehicleIdRouteRoute,
  } as any)
const ProtectedVehiclesFormularVehicleIdRouteRoute =
  ProtectedVehiclesFormularVehicleIdRouteRouteImport.update({
    id: '/_formular/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => ProtectedVehiclesRouteRoute,
  } as any)
const ProtectedVehiclesFormularNewRouteRoute =
  ProtectedVehiclesFormularNewRouteRouteImport.update({
    id: '/_formular/new',
    path: '/new',
    getParentRoute: () => ProtectedVehiclesRouteRoute,
  } as any)
const ProtectedWateringPlansWateringPlanIdIndexRoute =
  ProtectedWateringPlansWateringPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWateringPlansWateringPlanIdRouteRoute,
  } as any)
const ProtectedWateringPlansFormularWateringPlanIdRouteRoute =
  ProtectedWateringPlansFormularWateringPlanIdRouteRouteImport.update({
    id: '/_formular/$wateringPlanId',
    path: '/$wateringPlanId',
    getParentRoute: () => ProtectedWateringPlansRouteRoute,
  } as any)
const ProtectedWateringPlansFormularNewRouteRoute =
  ProtectedWateringPlansFormularNewRouteRouteImport.update({
    id: '/_formular/new',
    path: '/new',
    getParentRoute: () => ProtectedWateringPlansRouteRoute,
  } as any)
const ProtectedMapTreeNewIndexRoute =
  ProtectedMapTreeNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMapTreeNewRouteRoute,
  } as any)
const ProtectedMapTreeclusterNewIndexRoute =
  ProtectedMapTreeclusterNewIndexRouteImport.update({
    id: '/treecluster/new/',
    path: '/treecluster/new/',
    getParentRoute: () => ProtectedMapRouteRoute,
  } as any)
const ProtectedMapWateringPlanSelectClusterRouteRoute =
  ProtectedMapWateringPlanSelectClusterRouteRouteImport.update({
    id: '/watering-plan/select/cluster',
    path: '/watering-plan/select/cluster',
    getParentRoute: () => ProtectedMapRouteRoute,
  } as any)
const ProtectedSettingsPluginPluginNameIndexRoute =
  ProtectedSettingsPluginPluginNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsPluginPluginNameRouteRoute,
  } as any)
const ProtectedSettingsTeamMembersIndexRoute =
  ProtectedSettingsTeamMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => ProtectedSettingsTeamRouteRoute,
  } as any)
const ProtectedSettingsTeamRolesIndexRoute =
  ProtectedSettingsTeamRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => ProtectedSettingsTeamRouteRoute,
  } as any)
const ProtectedVehiclesFormularVehicleIdEditRouteRoute =
  ProtectedVehiclesFormularVehicleIdEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedVehiclesFormularVehicleIdRouteRoute,
  } as any)
const ProtectedVehiclesFormularNewIndexRoute =
  ProtectedVehiclesFormularNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedVehiclesFormularNewRouteRoute,
  } as any)
const ProtectedWateringPlansFormularWateringPlanIdEditRouteRoute =
  ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      ProtectedWateringPlansFormularWateringPlanIdRouteRoute,
  } as any)
const ProtectedWateringPlansFormularNewIndexRoute =
  ProtectedWateringPlansFormularNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWateringPlansFormularNewRouteRoute,
  } as any)
const ProtectedMapTreeEditTreeIdIndexRoute =
  ProtectedMapTreeEditTreeIdIndexRouteImport.update({
    id: '/tree/edit/$treeId/',
    path: '/tree/edit/$treeId/',
    getParentRoute: () => ProtectedMapRouteRoute,
  } as any)
const ProtectedMapTreeclusterEditTreeclusterIdIndexRoute =
  ProtectedMapTreeclusterEditTreeclusterIdIndexRouteImport.update({
    id: '/treecluster/edit/$treeclusterId/',
    path: '/treecluster/edit/$treeclusterId/',
    getParentRoute: () => ProtectedMapRouteRoute,
  } as any)
const ProtectedMapWateringPlanSelectClusterIndexRoute =
  ProtectedMapWateringPlanSelectClusterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMapWateringPlanSelectClusterRouteRoute,
  } as any)
const ProtectedVehiclesFormularVehicleIdEditIndexRoute =
  ProtectedVehiclesFormularVehicleIdEditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedVehiclesFormularVehicleIdEditRouteRoute,
  } as any)
const ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute =
  ProtectedWateringPlansFormularWateringPlanIdEditIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedWateringPlansFormularWateringPlanIdEditRouteRoute,
  } as any)
const ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRoute =
  ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteImport.update(
    {
      id: '/status/edit',
      path: '/status/edit',
      getParentRoute: () =>
        ProtectedWateringPlansFormularWateringPlanIdRouteRoute,
    } as any,
  )
const ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute =
  ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/debug': typeof ProtectedDebugRouteRouteWithChildren
  '/evaluations': typeof ProtectedEvaluationsRouteRouteWithChildren
  '/map': typeof ProtectedMapRouteRouteWithChildren
  '/sensors': typeof ProtectedSensorsRouteRouteWithChildren
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/treecluster': typeof ProtectedTreeclusterRouteRouteWithChildren
  '/trees': typeof ProtectedTreesRouteRouteWithChildren
  '/vehicles': typeof ProtectedVehiclesRouteRouteWithChildren
  '/watering-plans': typeof ProtectedWateringPlansRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/info': typeof ProtectedInfoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/help/$slug': typeof HelpSlugRoute
  '/help/': typeof HelpIndexRoute
  '/sensors/$sensorId': typeof ProtectedSensorsSensorIdRouteRouteWithChildren
  '/sensors/new': typeof ProtectedSensorsNewRouteRouteWithChildren
  '/settings/plugin': typeof ProtectedSettingsPluginRouteRouteWithChildren
  '/settings/team': typeof ProtectedSettingsTeamRouteRouteWithChildren
  '/treecluster/$treeclusterId': typeof ProtectedTreeclusterTreeclusterIdRouteRouteWithChildren
  '/trees/$treeId': typeof ProtectedTreesTreeIdRouteRouteWithChildren
  '/vehicles/$vehicleId': typeof ProtectedVehiclesFormularVehicleIdRouteRouteWithChildren
  '/watering-plans/$wateringPlanId': typeof ProtectedWateringPlansFormularWateringPlanIdRouteRouteWithChildren
  '/debug/': typeof ProtectedDebugIndexRoute
  '/evaluations/': typeof ProtectedEvaluationsIndexRoute
  '/map/': typeof ProtectedMapIndexRoute
  '/sensors/': typeof ProtectedSensorsIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/treecluster/': typeof ProtectedTreeclusterIndexRoute
  '/trees/': typeof ProtectedTreesIndexRoute
  '/vehicles/': typeof ProtectedVehiclesIndexRoute
  '/watering-plans/': typeof ProtectedWateringPlansIndexRoute
  '/map/tree/new': typeof ProtectedMapTreeNewRouteRouteWithChildren
  '/settings/plugin/$pluginName': typeof ProtectedSettingsPluginPluginNameRouteRouteWithChildren
  '/vehicles/new': typeof ProtectedVehiclesFormularNewRouteRouteWithChildren
  '/watering-plans/new': typeof ProtectedWateringPlansFormularNewRouteRouteWithChildren
  '/debug/geolocation/': typeof ProtectedDebugGeolocationIndexRoute
  '/debug/qr-scanner/': typeof ProtectedDebugQrScannerIndexRoute
  '/sensors/$sensorId/': typeof ProtectedSensorsSensorIdIndexRoute
  '/sensors/new/': typeof ProtectedSensorsNewIndexRoute
  '/settings/irrigation/': typeof ProtectedSettingsIrrigationIndexRoute
  '/settings/map/': typeof ProtectedSettingsMapIndexRoute
  '/settings/notifications/': typeof ProtectedSettingsNotificationsIndexRoute
  '/settings/organization/': typeof ProtectedSettingsOrganizationIndexRoute
  '/settings/plugin/': typeof ProtectedSettingsPluginIndexRoute
  '/settings/profile/': typeof ProtectedSettingsProfileIndexRoute
  '/settings/sensors/': typeof ProtectedSettingsSensorsIndexRoute
  '/settings/team/': typeof ProtectedSettingsTeamIndexRoute
  '/treecluster/$treeclusterId/': typeof ProtectedTreeclusterTreeclusterIdIndexRoute
  '/trees/$treeId/': typeof ProtectedTreesTreeIdIndexRoute
  '/vehicles/$vehicleId/': typeof ProtectedVehiclesVehicleIdIndexRoute
  '/watering-plans/$wateringPlanId/': typeof ProtectedWateringPlansWateringPlanIdIndexRoute
  '/map/watering-plan/select/cluster': typeof ProtectedMapWateringPlanSelectClusterRouteRouteWithChildren
  '/vehicles/$vehicleId/edit': typeof ProtectedVehiclesFormularVehicleIdEditRouteRouteWithChildren
  '/watering-plans/$wateringPlanId/edit': typeof ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteWithChildren
  '/map/tree/new/': typeof ProtectedMapTreeNewIndexRoute
  '/map/treecluster/new/': typeof ProtectedMapTreeclusterNewIndexRoute
  '/settings/plugin/$pluginName/': typeof ProtectedSettingsPluginPluginNameIndexRoute
  '/settings/team/members/': typeof ProtectedSettingsTeamMembersIndexRoute
  '/settings/team/roles/': typeof ProtectedSettingsTeamRolesIndexRoute
  '/vehicles/new/': typeof ProtectedVehiclesFormularNewIndexRoute
  '/watering-plans/new/': typeof ProtectedWateringPlansFormularNewIndexRoute
  '/watering-plans/$wateringPlanId/status/edit': typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteWithChildren
  '/map/tree/edit/$treeId/': typeof ProtectedMapTreeEditTreeIdIndexRoute
  '/map/treecluster/edit/$treeclusterId/': typeof ProtectedMapTreeclusterEditTreeclusterIdIndexRoute
  '/map/watering-plan/select/cluster/': typeof ProtectedMapWateringPlanSelectClusterIndexRoute
  '/vehicles/$vehicleId/edit/': typeof ProtectedVehiclesFormularVehicleIdEditIndexRoute
  '/watering-plans/$wateringPlanId/edit/': typeof ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute
  '/watering-plans/$wateringPlanId/status/edit/': typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/info': typeof ProtectedInfoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/help/$slug': typeof HelpSlugRoute
  '/help': typeof HelpIndexRoute
  '/debug': typeof ProtectedDebugIndexRoute
  '/evaluations': typeof ProtectedEvaluationsIndexRoute
  '/map': typeof ProtectedMapIndexRoute
  '/sensors': typeof ProtectedSensorsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/treecluster': typeof ProtectedTreeclusterIndexRoute
  '/trees': typeof ProtectedTreesIndexRoute
  '/vehicles': typeof ProtectedVehiclesIndexRoute
  '/watering-plans': typeof ProtectedWateringPlansIndexRoute
  '/vehicles/$vehicleId': typeof ProtectedVehiclesVehicleIdIndexRoute
  '/watering-plans/$wateringPlanId': typeof ProtectedWateringPlansWateringPlanIdIndexRoute
  '/debug/geolocation': typeof ProtectedDebugGeolocationIndexRoute
  '/debug/qr-scanner': typeof ProtectedDebugQrScannerIndexRoute
  '/sensors/$sensorId': typeof ProtectedSensorsSensorIdIndexRoute
  '/sensors/new': typeof ProtectedSensorsNewIndexRoute
  '/settings/irrigation': typeof ProtectedSettingsIrrigationIndexRoute
  '/settings/map': typeof ProtectedSettingsMapIndexRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsIndexRoute
  '/settings/organization': typeof ProtectedSettingsOrganizationIndexRoute
  '/settings/plugin': typeof ProtectedSettingsPluginIndexRoute
  '/settings/profile': typeof ProtectedSettingsProfileIndexRoute
  '/settings/sensors': typeof ProtectedSettingsSensorsIndexRoute
  '/settings/team': typeof ProtectedSettingsTeamIndexRoute
  '/treecluster/$treeclusterId': typeof ProtectedTreeclusterTreeclusterIdIndexRoute
  '/trees/$treeId': typeof ProtectedTreesTreeIdIndexRoute
  '/map/tree/new': typeof ProtectedMapTreeNewIndexRoute
  '/map/treecluster/new': typeof ProtectedMapTreeclusterNewIndexRoute
  '/settings/plugin/$pluginName': typeof ProtectedSettingsPluginPluginNameIndexRoute
  '/settings/team/members': typeof ProtectedSettingsTeamMembersIndexRoute
  '/settings/team/roles': typeof ProtectedSettingsTeamRolesIndexRoute
  '/vehicles/new': typeof ProtectedVehiclesFormularNewIndexRoute
  '/watering-plans/new': typeof ProtectedWateringPlansFormularNewIndexRoute
  '/map/tree/edit/$treeId': typeof ProtectedMapTreeEditTreeIdIndexRoute
  '/map/treecluster/edit/$treeclusterId': typeof ProtectedMapTreeclusterEditTreeclusterIdIndexRoute
  '/map/watering-plan/select/cluster': typeof ProtectedMapWateringPlanSelectClusterIndexRoute
  '/vehicles/$vehicleId/edit': typeof ProtectedVehiclesFormularVehicleIdEditIndexRoute
  '/watering-plans/$wateringPlanId/edit': typeof ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute
  '/watering-plans/$wateringPlanId/status/edit': typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_protected/debug': typeof ProtectedDebugRouteRouteWithChildren
  '/_protected/evaluations': typeof ProtectedEvaluationsRouteRouteWithChildren
  '/_protected/map': typeof ProtectedMapRouteRouteWithChildren
  '/_protected/sensors': typeof ProtectedSensorsRouteRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/treecluster': typeof ProtectedTreeclusterRouteRouteWithChildren
  '/_protected/trees': typeof ProtectedTreesRouteRouteWithChildren
  '/_protected/vehicles': typeof ProtectedVehiclesRouteRouteWithChildren
  '/_protected/watering-plans': typeof ProtectedWateringPlansRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/info': typeof ProtectedInfoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/help/$slug': typeof HelpSlugRoute
  '/help/': typeof HelpIndexRoute
  '/_protected/sensors/$sensorId': typeof ProtectedSensorsSensorIdRouteRouteWithChildren
  '/_protected/sensors/new': typeof ProtectedSensorsNewRouteRouteWithChildren
  '/_protected/settings/plugin': typeof ProtectedSettingsPluginRouteRouteWithChildren
  '/_protected/settings/team': typeof ProtectedSettingsTeamRouteRouteWithChildren
  '/_protected/treecluster/$treeclusterId': typeof ProtectedTreeclusterTreeclusterIdRouteRouteWithChildren
  '/_protected/trees/$treeId': typeof ProtectedTreesTreeIdRouteRouteWithChildren
  '/_protected/vehicles/$vehicleId': typeof ProtectedVehiclesVehicleIdRouteRouteWithChildren
  '/_protected/watering-plans/$wateringPlanId': typeof ProtectedWateringPlansWateringPlanIdRouteRouteWithChildren
  '/_protected/debug/': typeof ProtectedDebugIndexRoute
  '/_protected/evaluations/': typeof ProtectedEvaluationsIndexRoute
  '/_protected/map/': typeof ProtectedMapIndexRoute
  '/_protected/sensors/': typeof ProtectedSensorsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/treecluster/': typeof ProtectedTreeclusterIndexRoute
  '/_protected/trees/': typeof ProtectedTreesIndexRoute
  '/_protected/vehicles/': typeof ProtectedVehiclesIndexRoute
  '/_protected/watering-plans/': typeof ProtectedWateringPlansIndexRoute
  '/_protected/map/tree/new': typeof ProtectedMapTreeNewRouteRouteWithChildren
  '/_protected/settings/plugin/$pluginName': typeof ProtectedSettingsPluginPluginNameRouteRouteWithChildren
  '/_protected/vehicles/_formular/$vehicleId': typeof ProtectedVehiclesFormularVehicleIdRouteRouteWithChildren
  '/_protected/vehicles/_formular/new': typeof ProtectedVehiclesFormularNewRouteRouteWithChildren
  '/_protected/watering-plans/_formular/$wateringPlanId': typeof ProtectedWateringPlansFormularWateringPlanIdRouteRouteWithChildren
  '/_protected/watering-plans/_formular/new': typeof ProtectedWateringPlansFormularNewRouteRouteWithChildren
  '/_protected/debug/geolocation/': typeof ProtectedDebugGeolocationIndexRoute
  '/_protected/debug/qr-scanner/': typeof ProtectedDebugQrScannerIndexRoute
  '/_protected/sensors/$sensorId/': typeof ProtectedSensorsSensorIdIndexRoute
  '/_protected/sensors/new/': typeof ProtectedSensorsNewIndexRoute
  '/_protected/settings/irrigation/': typeof ProtectedSettingsIrrigationIndexRoute
  '/_protected/settings/map/': typeof ProtectedSettingsMapIndexRoute
  '/_protected/settings/notifications/': typeof ProtectedSettingsNotificationsIndexRoute
  '/_protected/settings/organization/': typeof ProtectedSettingsOrganizationIndexRoute
  '/_protected/settings/plugin/': typeof ProtectedSettingsPluginIndexRoute
  '/_protected/settings/profile/': typeof ProtectedSettingsProfileIndexRoute
  '/_protected/settings/sensors/': typeof ProtectedSettingsSensorsIndexRoute
  '/_protected/settings/team/': typeof ProtectedSettingsTeamIndexRoute
  '/_protected/treecluster/$treeclusterId/': typeof ProtectedTreeclusterTreeclusterIdIndexRoute
  '/_protected/trees/$treeId/': typeof ProtectedTreesTreeIdIndexRoute
  '/_protected/vehicles/$vehicleId/': typeof ProtectedVehiclesVehicleIdIndexRoute
  '/_protected/watering-plans/$wateringPlanId/': typeof ProtectedWateringPlansWateringPlanIdIndexRoute
  '/_protected/map/watering-plan/select/cluster': typeof ProtectedMapWateringPlanSelectClusterRouteRouteWithChildren
  '/_protected/vehicles/_formular/$vehicleId/edit': typeof ProtectedVehiclesFormularVehicleIdEditRouteRouteWithChildren
  '/_protected/watering-plans/_formular/$wateringPlanId/edit': typeof ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteWithChildren
  '/_protected/map/tree/new/': typeof ProtectedMapTreeNewIndexRoute
  '/_protected/map/treecluster/new/': typeof ProtectedMapTreeclusterNewIndexRoute
  '/_protected/settings/plugin/$pluginName/': typeof ProtectedSettingsPluginPluginNameIndexRoute
  '/_protected/settings/team/members/': typeof ProtectedSettingsTeamMembersIndexRoute
  '/_protected/settings/team/roles/': typeof ProtectedSettingsTeamRolesIndexRoute
  '/_protected/vehicles/_formular/new/': typeof ProtectedVehiclesFormularNewIndexRoute
  '/_protected/watering-plans/_formular/new/': typeof ProtectedWateringPlansFormularNewIndexRoute
  '/_protected/watering-plans/_formular/$wateringPlanId/status/edit': typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteWithChildren
  '/_protected/map/tree/edit/$treeId/': typeof ProtectedMapTreeEditTreeIdIndexRoute
  '/_protected/map/treecluster/edit/$treeclusterId/': typeof ProtectedMapTreeclusterEditTreeclusterIdIndexRoute
  '/_protected/map/watering-plan/select/cluster/': typeof ProtectedMapWateringPlanSelectClusterIndexRoute
  '/_protected/vehicles/_formular/$vehicleId/edit/': typeof ProtectedVehiclesFormularVehicleIdEditIndexRoute
  '/_protected/watering-plans/_formular/$wateringPlanId/edit/': typeof ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute
  '/_protected/watering-plans/_formular/$wateringPlanId/status/edit/': typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/debug'
    | '/evaluations'
    | '/map'
    | '/sensors'
    | '/settings'
    | '/treecluster'
    | '/trees'
    | '/vehicles'
    | '/watering-plans'
    | '/dashboard'
    | '/info'
    | '/auth/callback'
    | '/help/$slug'
    | '/help/'
    | '/sensors/$sensorId'
    | '/sensors/new'
    | '/settings/plugin'
    | '/settings/team'
    | '/treecluster/$treeclusterId'
    | '/trees/$treeId'
    | '/vehicles/$vehicleId'
    | '/watering-plans/$wateringPlanId'
    | '/debug/'
    | '/evaluations/'
    | '/map/'
    | '/sensors/'
    | '/settings/'
    | '/treecluster/'
    | '/trees/'
    | '/vehicles/'
    | '/watering-plans/'
    | '/map/tree/new'
    | '/settings/plugin/$pluginName'
    | '/vehicles/new'
    | '/watering-plans/new'
    | '/debug/geolocation/'
    | '/debug/qr-scanner/'
    | '/sensors/$sensorId/'
    | '/sensors/new/'
    | '/settings/irrigation/'
    | '/settings/map/'
    | '/settings/notifications/'
    | '/settings/organization/'
    | '/settings/plugin/'
    | '/settings/profile/'
    | '/settings/sensors/'
    | '/settings/team/'
    | '/treecluster/$treeclusterId/'
    | '/trees/$treeId/'
    | '/vehicles/$vehicleId/'
    | '/watering-plans/$wateringPlanId/'
    | '/map/watering-plan/select/cluster'
    | '/vehicles/$vehicleId/edit'
    | '/watering-plans/$wateringPlanId/edit'
    | '/map/tree/new/'
    | '/map/treecluster/new/'
    | '/settings/plugin/$pluginName/'
    | '/settings/team/members/'
    | '/settings/team/roles/'
    | '/vehicles/new/'
    | '/watering-plans/new/'
    | '/watering-plans/$wateringPlanId/status/edit'
    | '/map/tree/edit/$treeId/'
    | '/map/treecluster/edit/$treeclusterId/'
    | '/map/watering-plan/select/cluster/'
    | '/vehicles/$vehicleId/edit/'
    | '/watering-plans/$wateringPlanId/edit/'
    | '/watering-plans/$wateringPlanId/status/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/info'
    | '/auth/callback'
    | '/help/$slug'
    | '/help'
    | '/debug'
    | '/evaluations'
    | '/map'
    | '/sensors'
    | '/settings'
    | '/treecluster'
    | '/trees'
    | '/vehicles'
    | '/watering-plans'
    | '/vehicles/$vehicleId'
    | '/watering-plans/$wateringPlanId'
    | '/debug/geolocation'
    | '/debug/qr-scanner'
    | '/sensors/$sensorId'
    | '/sensors/new'
    | '/settings/irrigation'
    | '/settings/map'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/plugin'
    | '/settings/profile'
    | '/settings/sensors'
    | '/settings/team'
    | '/treecluster/$treeclusterId'
    | '/trees/$treeId'
    | '/map/tree/new'
    | '/map/treecluster/new'
    | '/settings/plugin/$pluginName'
    | '/settings/team/members'
    | '/settings/team/roles'
    | '/vehicles/new'
    | '/watering-plans/new'
    | '/map/tree/edit/$treeId'
    | '/map/treecluster/edit/$treeclusterId'
    | '/map/watering-plan/select/cluster'
    | '/vehicles/$vehicleId/edit'
    | '/watering-plans/$wateringPlanId/edit'
    | '/watering-plans/$wateringPlanId/status/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/logout'
    | '/_protected/debug'
    | '/_protected/evaluations'
    | '/_protected/map'
    | '/_protected/sensors'
    | '/_protected/settings'
    | '/_protected/treecluster'
    | '/_protected/trees'
    | '/_protected/vehicles'
    | '/_protected/watering-plans'
    | '/_protected/dashboard'
    | '/_protected/info'
    | '/auth/callback'
    | '/help/$slug'
    | '/help/'
    | '/_protected/sensors/$sensorId'
    | '/_protected/sensors/new'
    | '/_protected/settings/plugin'
    | '/_protected/settings/team'
    | '/_protected/treecluster/$treeclusterId'
    | '/_protected/trees/$treeId'
    | '/_protected/vehicles/$vehicleId'
    | '/_protected/watering-plans/$wateringPlanId'
    | '/_protected/debug/'
    | '/_protected/evaluations/'
    | '/_protected/map/'
    | '/_protected/sensors/'
    | '/_protected/settings/'
    | '/_protected/treecluster/'
    | '/_protected/trees/'
    | '/_protected/vehicles/'
    | '/_protected/watering-plans/'
    | '/_protected/map/tree/new'
    | '/_protected/settings/plugin/$pluginName'
    | '/_protected/vehicles/_formular/$vehicleId'
    | '/_protected/vehicles/_formular/new'
    | '/_protected/watering-plans/_formular/$wateringPlanId'
    | '/_protected/watering-plans/_formular/new'
    | '/_protected/debug/geolocation/'
    | '/_protected/debug/qr-scanner/'
    | '/_protected/sensors/$sensorId/'
    | '/_protected/sensors/new/'
    | '/_protected/settings/irrigation/'
    | '/_protected/settings/map/'
    | '/_protected/settings/notifications/'
    | '/_protected/settings/organization/'
    | '/_protected/settings/plugin/'
    | '/_protected/settings/profile/'
    | '/_protected/settings/sensors/'
    | '/_protected/settings/team/'
    | '/_protected/treecluster/$treeclusterId/'
    | '/_protected/trees/$treeId/'
    | '/_protected/vehicles/$vehicleId/'
    | '/_protected/watering-plans/$wateringPlanId/'
    | '/_protected/map/watering-plan/select/cluster'
    | '/_protected/vehicles/_formular/$vehicleId/edit'
    | '/_protected/watering-plans/_formular/$wateringPlanId/edit'
    | '/_protected/map/tree/new/'
    | '/_protected/map/treecluster/new/'
    | '/_protected/settings/plugin/$pluginName/'
    | '/_protected/settings/team/members/'
    | '/_protected/settings/team/roles/'
    | '/_protected/vehicles/_formular/new/'
    | '/_protected/watering-plans/_formular/new/'
    | '/_protected/watering-plans/_formular/$wateringPlanId/status/edit'
    | '/_protected/map/tree/edit/$treeId/'
    | '/_protected/map/treecluster/edit/$treeclusterId/'
    | '/_protected/map/watering-plan/select/cluster/'
    | '/_protected/vehicles/_formular/$vehicleId/edit/'
    | '/_protected/watering-plans/_formular/$wateringPlanId/edit/'
    | '/_protected/watering-plans/_formular/$wateringPlanId/status/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  HelpSlugRoute: typeof HelpSlugRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debug': {
      id: '/_protected/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof ProtectedDebugRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/evaluations': {
      id: '/_protected/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof ProtectedEvaluationsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/info': {
      id: '/_protected/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof ProtectedInfoRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/map': {
      id: '/_protected/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof ProtectedMapRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sensors': {
      id: '/_protected/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof ProtectedSensorsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/treecluster': {
      id: '/_protected/treecluster'
      path: '/treecluster'
      fullPath: '/treecluster'
      preLoaderRoute: typeof ProtectedTreeclusterRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/trees': {
      id: '/_protected/trees'
      path: '/trees'
      fullPath: '/trees'
      preLoaderRoute: typeof ProtectedTreesRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/vehicles': {
      id: '/_protected/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof ProtectedVehiclesRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/watering-plans': {
      id: '/_protected/watering-plans'
      path: '/watering-plans'
      fullPath: '/watering-plans'
      preLoaderRoute: typeof ProtectedWateringPlansRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$slug': {
      id: '/help/$slug'
      path: '/help/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof HelpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/debug/': {
      id: '/_protected/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof ProtectedDebugIndexRouteImport
      parentRoute: typeof ProtectedDebugRouteRoute
    }
    '/_protected/evaluations/': {
      id: '/_protected/evaluations/'
      path: '/'
      fullPath: '/evaluations/'
      preLoaderRoute: typeof ProtectedEvaluationsIndexRouteImport
      parentRoute: typeof ProtectedEvaluationsRouteRoute
    }
    '/_protected/map/': {
      id: '/_protected/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof ProtectedMapIndexRouteImport
      parentRoute: typeof ProtectedMapRouteRoute
    }
    '/_protected/sensors/': {
      id: '/_protected/sensors/'
      path: '/'
      fullPath: '/sensors/'
      preLoaderRoute: typeof ProtectedSensorsIndexRouteImport
      parentRoute: typeof ProtectedSensorsRouteRoute
    }
    '/_protected/sensors/$sensorId': {
      id: '/_protected/sensors/$sensorId'
      path: '/$sensorId'
      fullPath: '/sensors/$sensorId'
      preLoaderRoute: typeof ProtectedSensorsSensorIdRouteRouteImport
      parentRoute: typeof ProtectedSensorsRouteRoute
    }
    '/_protected/sensors/new': {
      id: '/_protected/sensors/new'
      path: '/new'
      fullPath: '/sensors/new'
      preLoaderRoute: typeof ProtectedSensorsNewRouteRouteImport
      parentRoute: typeof ProtectedSensorsRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/plugin': {
      id: '/_protected/settings/plugin'
      path: '/plugin'
      fullPath: '/settings/plugin'
      preLoaderRoute: typeof ProtectedSettingsPluginRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/team': {
      id: '/_protected/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof ProtectedSettingsTeamRouteRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/treecluster/': {
      id: '/_protected/treecluster/'
      path: '/'
      fullPath: '/treecluster/'
      preLoaderRoute: typeof ProtectedTreeclusterIndexRouteImport
      parentRoute: typeof ProtectedTreeclusterRouteRoute
    }
    '/_protected/treecluster/$treeclusterId': {
      id: '/_protected/treecluster/$treeclusterId'
      path: '/$treeclusterId'
      fullPath: '/treecluster/$treeclusterId'
      preLoaderRoute: typeof ProtectedTreeclusterTreeclusterIdRouteRouteImport
      parentRoute: typeof ProtectedTreeclusterRouteRoute
    }
    '/_protected/trees/': {
      id: '/_protected/trees/'
      path: '/'
      fullPath: '/trees/'
      preLoaderRoute: typeof ProtectedTreesIndexRouteImport
      parentRoute: typeof ProtectedTreesRouteRoute
    }
    '/_protected/trees/$treeId': {
      id: '/_protected/trees/$treeId'
      path: '/$treeId'
      fullPath: '/trees/$treeId'
      preLoaderRoute: typeof ProtectedTreesTreeIdRouteRouteImport
      parentRoute: typeof ProtectedTreesRouteRoute
    }
    '/_protected/vehicles/': {
      id: '/_protected/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof ProtectedVehiclesIndexRouteImport
      parentRoute: typeof ProtectedVehiclesRouteRoute
    }
    '/_protected/vehicles/$vehicleId': {
      id: '/_protected/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof ProtectedVehiclesVehicleIdRouteRouteImport
      parentRoute: typeof ProtectedVehiclesRouteRoute
    }
    '/_protected/watering-plans/': {
      id: '/_protected/watering-plans/'
      path: '/'
      fullPath: '/watering-plans/'
      preLoaderRoute: typeof ProtectedWateringPlansIndexRouteImport
      parentRoute: typeof ProtectedWateringPlansRouteRoute
    }
    '/_protected/watering-plans/$wateringPlanId': {
      id: '/_protected/watering-plans/$wateringPlanId'
      path: '/$wateringPlanId'
      fullPath: '/watering-plans/$wateringPlanId'
      preLoaderRoute: typeof ProtectedWateringPlansWateringPlanIdRouteRouteImport
      parentRoute: typeof ProtectedWateringPlansRouteRoute
    }
    '/_protected/debug/geolocation/': {
      id: '/_protected/debug/geolocation/'
      path: '/geolocation'
      fullPath: '/debug/geolocation/'
      preLoaderRoute: typeof ProtectedDebugGeolocationIndexRouteImport
      parentRoute: typeof ProtectedDebugRouteRoute
    }
    '/_protected/debug/qr-scanner/': {
      id: '/_protected/debug/qr-scanner/'
      path: '/qr-scanner'
      fullPath: '/debug/qr-scanner/'
      preLoaderRoute: typeof ProtectedDebugQrScannerIndexRouteImport
      parentRoute: typeof ProtectedDebugRouteRoute
    }
    '/_protected/map/tree/new': {
      id: '/_protected/map/tree/new'
      path: '/tree/new'
      fullPath: '/map/tree/new'
      preLoaderRoute: typeof ProtectedMapTreeNewRouteRouteImport
      parentRoute: typeof ProtectedMapRouteRoute
    }
    '/_protected/sensors/$sensorId/': {
      id: '/_protected/sensors/$sensorId/'
      path: '/'
      fullPath: '/sensors/$sensorId/'
      preLoaderRoute: typeof ProtectedSensorsSensorIdIndexRouteImport
      parentRoute: typeof ProtectedSensorsSensorIdRouteRoute
    }
    '/_protected/sensors/new/': {
      id: '/_protected/sensors/new/'
      path: '/'
      fullPath: '/sensors/new/'
      preLoaderRoute: typeof ProtectedSensorsNewIndexRouteImport
      parentRoute: typeof ProtectedSensorsNewRouteRoute
    }
    '/_protected/settings/irrigation/': {
      id: '/_protected/settings/irrigation/'
      path: '/irrigation'
      fullPath: '/settings/irrigation/'
      preLoaderRoute: typeof ProtectedSettingsIrrigationIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/map/': {
      id: '/_protected/settings/map/'
      path: '/map'
      fullPath: '/settings/map/'
      preLoaderRoute: typeof ProtectedSettingsMapIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/notifications/': {
      id: '/_protected/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof ProtectedSettingsNotificationsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/organization/': {
      id: '/_protected/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof ProtectedSettingsOrganizationIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/plugin/': {
      id: '/_protected/settings/plugin/'
      path: '/'
      fullPath: '/settings/plugin/'
      preLoaderRoute: typeof ProtectedSettingsPluginIndexRouteImport
      parentRoute: typeof ProtectedSettingsPluginRouteRoute
    }
    '/_protected/settings/plugin/$pluginName': {
      id: '/_protected/settings/plugin/$pluginName'
      path: '/$pluginName'
      fullPath: '/settings/plugin/$pluginName'
      preLoaderRoute: typeof ProtectedSettingsPluginPluginNameRouteRouteImport
      parentRoute: typeof ProtectedSettingsPluginRouteRoute
    }
    '/_protected/settings/profile/': {
      id: '/_protected/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof ProtectedSettingsProfileIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/sensors/': {
      id: '/_protected/settings/sensors/'
      path: '/sensors'
      fullPath: '/settings/sensors/'
      preLoaderRoute: typeof ProtectedSettingsSensorsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/team/': {
      id: '/_protected/settings/team/'
      path: '/'
      fullPath: '/settings/team/'
      preLoaderRoute: typeof ProtectedSettingsTeamIndexRouteImport
      parentRoute: typeof ProtectedSettingsTeamRouteRoute
    }
    '/_protected/treecluster/$treeclusterId/': {
      id: '/_protected/treecluster/$treeclusterId/'
      path: '/'
      fullPath: '/treecluster/$treeclusterId/'
      preLoaderRoute: typeof ProtectedTreeclusterTreeclusterIdIndexRouteImport
      parentRoute: typeof ProtectedTreeclusterTreeclusterIdRouteRoute
    }
    '/_protected/trees/$treeId/': {
      id: '/_protected/trees/$treeId/'
      path: '/'
      fullPath: '/trees/$treeId/'
      preLoaderRoute: typeof ProtectedTreesTreeIdIndexRouteImport
      parentRoute: typeof ProtectedTreesTreeIdRouteRoute
    }
    '/_protected/vehicles/$vehicleId/': {
      id: '/_protected/vehicles/$vehicleId/'
      path: '/'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof ProtectedVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof ProtectedVehiclesVehicleIdRouteRoute
    }
    '/_protected/vehicles/_formular/$vehicleId': {
      id: '/_protected/vehicles/_formular/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof ProtectedVehiclesFormularVehicleIdRouteRouteImport
      parentRoute: typeof ProtectedVehiclesRouteRoute
    }
    '/_protected/vehicles/_formular/new': {
      id: '/_protected/vehicles/_formular/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof ProtectedVehiclesFormularNewRouteRouteImport
      parentRoute: typeof ProtectedVehiclesRouteRoute
    }
    '/_protected/watering-plans/$wateringPlanId/': {
      id: '/_protected/watering-plans/$wateringPlanId/'
      path: '/'
      fullPath: '/watering-plans/$wateringPlanId/'
      preLoaderRoute: typeof ProtectedWateringPlansWateringPlanIdIndexRouteImport
      parentRoute: typeof ProtectedWateringPlansWateringPlanIdRouteRoute
    }
    '/_protected/watering-plans/_formular/$wateringPlanId': {
      id: '/_protected/watering-plans/_formular/$wateringPlanId'
      path: '/$wateringPlanId'
      fullPath: '/watering-plans/$wateringPlanId'
      preLoaderRoute: typeof ProtectedWateringPlansFormularWateringPlanIdRouteRouteImport
      parentRoute: typeof ProtectedWateringPlansRouteRoute
    }
    '/_protected/watering-plans/_formular/new': {
      id: '/_protected/watering-plans/_formular/new'
      path: '/new'
      fullPath: '/watering-plans/new'
      preLoaderRoute: typeof ProtectedWateringPlansFormularNewRouteRouteImport
      parentRoute: typeof ProtectedWateringPlansRouteRoute
    }
    '/_protected/map/tree/new/': {
      id: '/_protected/map/tree/new/'
      path: '/'
      fullPath: '/map/tree/new/'
      preLoaderRoute: typeof ProtectedMapTreeNewIndexRouteImport
      parentRoute: typeof ProtectedMapTreeNewRouteRoute
    }
    '/_protected/map/treecluster/new/': {
      id: '/_protected/map/treecluster/new/'
      path: '/treecluster/new'
      fullPath: '/map/treecluster/new/'
      preLoaderRoute: typeof ProtectedMapTreeclusterNewIndexRouteImport
      parentRoute: typeof ProtectedMapRouteRoute
    }
    '/_protected/map/watering-plan/select/cluster': {
      id: '/_protected/map/watering-plan/select/cluster'
      path: '/watering-plan/select/cluster'
      fullPath: '/map/watering-plan/select/cluster'
      preLoaderRoute: typeof ProtectedMapWateringPlanSelectClusterRouteRouteImport
      parentRoute: typeof ProtectedMapRouteRoute
    }
    '/_protected/settings/plugin/$pluginName/': {
      id: '/_protected/settings/plugin/$pluginName/'
      path: '/'
      fullPath: '/settings/plugin/$pluginName/'
      preLoaderRoute: typeof ProtectedSettingsPluginPluginNameIndexRouteImport
      parentRoute: typeof ProtectedSettingsPluginPluginNameRouteRoute
    }
    '/_protected/settings/team/members/': {
      id: '/_protected/settings/team/members/'
      path: '/members'
      fullPath: '/settings/team/members/'
      preLoaderRoute: typeof ProtectedSettingsTeamMembersIndexRouteImport
      parentRoute: typeof ProtectedSettingsTeamRouteRoute
    }
    '/_protected/settings/team/roles/': {
      id: '/_protected/settings/team/roles/'
      path: '/roles'
      fullPath: '/settings/team/roles/'
      preLoaderRoute: typeof ProtectedSettingsTeamRolesIndexRouteImport
      parentRoute: typeof ProtectedSettingsTeamRouteRoute
    }
    '/_protected/vehicles/_formular/$vehicleId/edit': {
      id: '/_protected/vehicles/_formular/$vehicleId/edit'
      path: '/edit'
      fullPath: '/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof ProtectedVehiclesFormularVehicleIdEditRouteRouteImport
      parentRoute: typeof ProtectedVehiclesFormularVehicleIdRouteRoute
    }
    '/_protected/vehicles/_formular/new/': {
      id: '/_protected/vehicles/_formular/new/'
      path: '/'
      fullPath: '/vehicles/new/'
      preLoaderRoute: typeof ProtectedVehiclesFormularNewIndexRouteImport
      parentRoute: typeof ProtectedVehiclesFormularNewRouteRoute
    }
    '/_protected/watering-plans/_formular/$wateringPlanId/edit': {
      id: '/_protected/watering-plans/_formular/$wateringPlanId/edit'
      path: '/edit'
      fullPath: '/watering-plans/$wateringPlanId/edit'
      preLoaderRoute: typeof ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteImport
      parentRoute: typeof ProtectedWateringPlansFormularWateringPlanIdRouteRoute
    }
    '/_protected/watering-plans/_formular/new/': {
      id: '/_protected/watering-plans/_formular/new/'
      path: '/'
      fullPath: '/watering-plans/new/'
      preLoaderRoute: typeof ProtectedWateringPlansFormularNewIndexRouteImport
      parentRoute: typeof ProtectedWateringPlansFormularNewRouteRoute
    }
    '/_protected/map/tree/edit/$treeId/': {
      id: '/_protected/map/tree/edit/$treeId/'
      path: '/tree/edit/$treeId'
      fullPath: '/map/tree/edit/$treeId/'
      preLoaderRoute: typeof ProtectedMapTreeEditTreeIdIndexRouteImport
      parentRoute: typeof ProtectedMapRouteRoute
    }
    '/_protected/map/treecluster/edit/$treeclusterId/': {
      id: '/_protected/map/treecluster/edit/$treeclusterId/'
      path: '/treecluster/edit/$treeclusterId'
      fullPath: '/map/treecluster/edit/$treeclusterId/'
      preLoaderRoute: typeof ProtectedMapTreeclusterEditTreeclusterIdIndexRouteImport
      parentRoute: typeof ProtectedMapRouteRoute
    }
    '/_protected/map/watering-plan/select/cluster/': {
      id: '/_protected/map/watering-plan/select/cluster/'
      path: '/'
      fullPath: '/map/watering-plan/select/cluster/'
      preLoaderRoute: typeof ProtectedMapWateringPlanSelectClusterIndexRouteImport
      parentRoute: typeof ProtectedMapWateringPlanSelectClusterRouteRoute
    }
    '/_protected/vehicles/_formular/$vehicleId/edit/': {
      id: '/_protected/vehicles/_formular/$vehicleId/edit/'
      path: '/'
      fullPath: '/vehicles/$vehicleId/edit/'
      preLoaderRoute: typeof ProtectedVehiclesFormularVehicleIdEditIndexRouteImport
      parentRoute: typeof ProtectedVehiclesFormularVehicleIdEditRouteRoute
    }
    '/_protected/watering-plans/_formular/$wateringPlanId/edit/': {
      id: '/_protected/watering-plans/_formular/$wateringPlanId/edit/'
      path: '/'
      fullPath: '/watering-plans/$wateringPlanId/edit/'
      preLoaderRoute: typeof ProtectedWateringPlansFormularWateringPlanIdEditIndexRouteImport
      parentRoute: typeof ProtectedWateringPlansFormularWateringPlanIdEditRouteRoute
    }
    '/_protected/watering-plans/_formular/$wateringPlanId/status/edit': {
      id: '/_protected/watering-plans/_formular/$wateringPlanId/status/edit'
      path: '/status/edit'
      fullPath: '/watering-plans/$wateringPlanId/status/edit'
      preLoaderRoute: typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteImport
      parentRoute: typeof ProtectedWateringPlansFormularWateringPlanIdRouteRoute
    }
    '/_protected/watering-plans/_formular/$wateringPlanId/status/edit/': {
      id: '/_protected/watering-plans/_formular/$wateringPlanId/status/edit/'
      path: '/'
      fullPath: '/watering-plans/$wateringPlanId/status/edit/'
      preLoaderRoute: typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRouteImport
      parentRoute: typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRoute
    }
  }
}

interface ProtectedDebugRouteRouteChildren {
  ProtectedDebugIndexRoute: typeof ProtectedDebugIndexRoute
  ProtectedDebugGeolocationIndexRoute: typeof ProtectedDebugGeolocationIndexRoute
  ProtectedDebugQrScannerIndexRoute: typeof ProtectedDebugQrScannerIndexRoute
}

const ProtectedDebugRouteRouteChildren: ProtectedDebugRouteRouteChildren = {
  ProtectedDebugIndexRoute: ProtectedDebugIndexRoute,
  ProtectedDebugGeolocationIndexRoute: ProtectedDebugGeolocationIndexRoute,
  ProtectedDebugQrScannerIndexRoute: ProtectedDebugQrScannerIndexRoute,
}

const ProtectedDebugRouteRouteWithChildren =
  ProtectedDebugRouteRoute._addFileChildren(ProtectedDebugRouteRouteChildren)

interface ProtectedEvaluationsRouteRouteChildren {
  ProtectedEvaluationsIndexRoute: typeof ProtectedEvaluationsIndexRoute
}

const ProtectedEvaluationsRouteRouteChildren: ProtectedEvaluationsRouteRouteChildren =
  {
    ProtectedEvaluationsIndexRoute: ProtectedEvaluationsIndexRoute,
  }

const ProtectedEvaluationsRouteRouteWithChildren =
  ProtectedEvaluationsRouteRoute._addFileChildren(
    ProtectedEvaluationsRouteRouteChildren,
  )

interface ProtectedMapTreeNewRouteRouteChildren {
  ProtectedMapTreeNewIndexRoute: typeof ProtectedMapTreeNewIndexRoute
}

const ProtectedMapTreeNewRouteRouteChildren: ProtectedMapTreeNewRouteRouteChildren =
  {
    ProtectedMapTreeNewIndexRoute: ProtectedMapTreeNewIndexRoute,
  }

const ProtectedMapTreeNewRouteRouteWithChildren =
  ProtectedMapTreeNewRouteRoute._addFileChildren(
    ProtectedMapTreeNewRouteRouteChildren,
  )

interface ProtectedMapWateringPlanSelectClusterRouteRouteChildren {
  ProtectedMapWateringPlanSelectClusterIndexRoute: typeof ProtectedMapWateringPlanSelectClusterIndexRoute
}

const ProtectedMapWateringPlanSelectClusterRouteRouteChildren: ProtectedMapWateringPlanSelectClusterRouteRouteChildren =
  {
    ProtectedMapWateringPlanSelectClusterIndexRoute:
      ProtectedMapWateringPlanSelectClusterIndexRoute,
  }

const ProtectedMapWateringPlanSelectClusterRouteRouteWithChildren =
  ProtectedMapWateringPlanSelectClusterRouteRoute._addFileChildren(
    ProtectedMapWateringPlanSelectClusterRouteRouteChildren,
  )

interface ProtectedMapRouteRouteChildren {
  ProtectedMapIndexRoute: typeof ProtectedMapIndexRoute
  ProtectedMapTreeNewRouteRoute: typeof ProtectedMapTreeNewRouteRouteWithChildren
  ProtectedMapWateringPlanSelectClusterRouteRoute: typeof ProtectedMapWateringPlanSelectClusterRouteRouteWithChildren
  ProtectedMapTreeclusterNewIndexRoute: typeof ProtectedMapTreeclusterNewIndexRoute
  ProtectedMapTreeEditTreeIdIndexRoute: typeof ProtectedMapTreeEditTreeIdIndexRoute
  ProtectedMapTreeclusterEditTreeclusterIdIndexRoute: typeof ProtectedMapTreeclusterEditTreeclusterIdIndexRoute
}

const ProtectedMapRouteRouteChildren: ProtectedMapRouteRouteChildren = {
  ProtectedMapIndexRoute: ProtectedMapIndexRoute,
  ProtectedMapTreeNewRouteRoute: ProtectedMapTreeNewRouteRouteWithChildren,
  ProtectedMapWateringPlanSelectClusterRouteRoute:
    ProtectedMapWateringPlanSelectClusterRouteRouteWithChildren,
  ProtectedMapTreeclusterNewIndexRoute: ProtectedMapTreeclusterNewIndexRoute,
  ProtectedMapTreeEditTreeIdIndexRoute: ProtectedMapTreeEditTreeIdIndexRoute,
  ProtectedMapTreeclusterEditTreeclusterIdIndexRoute:
    ProtectedMapTreeclusterEditTreeclusterIdIndexRoute,
}

const ProtectedMapRouteRouteWithChildren =
  ProtectedMapRouteRoute._addFileChildren(ProtectedMapRouteRouteChildren)

interface ProtectedSensorsSensorIdRouteRouteChildren {
  ProtectedSensorsSensorIdIndexRoute: typeof ProtectedSensorsSensorIdIndexRoute
}

const ProtectedSensorsSensorIdRouteRouteChildren: ProtectedSensorsSensorIdRouteRouteChildren =
  {
    ProtectedSensorsSensorIdIndexRoute: ProtectedSensorsSensorIdIndexRoute,
  }

const ProtectedSensorsSensorIdRouteRouteWithChildren =
  ProtectedSensorsSensorIdRouteRoute._addFileChildren(
    ProtectedSensorsSensorIdRouteRouteChildren,
  )

interface ProtectedSensorsNewRouteRouteChildren {
  ProtectedSensorsNewIndexRoute: typeof ProtectedSensorsNewIndexRoute
}

const ProtectedSensorsNewRouteRouteChildren: ProtectedSensorsNewRouteRouteChildren =
  {
    ProtectedSensorsNewIndexRoute: ProtectedSensorsNewIndexRoute,
  }

const ProtectedSensorsNewRouteRouteWithChildren =
  ProtectedSensorsNewRouteRoute._addFileChildren(
    ProtectedSensorsNewRouteRouteChildren,
  )

interface ProtectedSensorsRouteRouteChildren {
  ProtectedSensorsSensorIdRouteRoute: typeof ProtectedSensorsSensorIdRouteRouteWithChildren
  ProtectedSensorsNewRouteRoute: typeof ProtectedSensorsNewRouteRouteWithChildren
  ProtectedSensorsIndexRoute: typeof ProtectedSensorsIndexRoute
}

const ProtectedSensorsRouteRouteChildren: ProtectedSensorsRouteRouteChildren = {
  ProtectedSensorsSensorIdRouteRoute:
    ProtectedSensorsSensorIdRouteRouteWithChildren,
  ProtectedSensorsNewRouteRoute: ProtectedSensorsNewRouteRouteWithChildren,
  ProtectedSensorsIndexRoute: ProtectedSensorsIndexRoute,
}

const ProtectedSensorsRouteRouteWithChildren =
  ProtectedSensorsRouteRoute._addFileChildren(
    ProtectedSensorsRouteRouteChildren,
  )

interface ProtectedSettingsPluginPluginNameRouteRouteChildren {
  ProtectedSettingsPluginPluginNameIndexRoute: typeof ProtectedSettingsPluginPluginNameIndexRoute
}

const ProtectedSettingsPluginPluginNameRouteRouteChildren: ProtectedSettingsPluginPluginNameRouteRouteChildren =
  {
    ProtectedSettingsPluginPluginNameIndexRoute:
      ProtectedSettingsPluginPluginNameIndexRoute,
  }

const ProtectedSettingsPluginPluginNameRouteRouteWithChildren =
  ProtectedSettingsPluginPluginNameRouteRoute._addFileChildren(
    ProtectedSettingsPluginPluginNameRouteRouteChildren,
  )

interface ProtectedSettingsPluginRouteRouteChildren {
  ProtectedSettingsPluginPluginNameRouteRoute: typeof ProtectedSettingsPluginPluginNameRouteRouteWithChildren
  ProtectedSettingsPluginIndexRoute: typeof ProtectedSettingsPluginIndexRoute
}

const ProtectedSettingsPluginRouteRouteChildren: ProtectedSettingsPluginRouteRouteChildren =
  {
    ProtectedSettingsPluginPluginNameRouteRoute:
      ProtectedSettingsPluginPluginNameRouteRouteWithChildren,
    ProtectedSettingsPluginIndexRoute: ProtectedSettingsPluginIndexRoute,
  }

const ProtectedSettingsPluginRouteRouteWithChildren =
  ProtectedSettingsPluginRouteRoute._addFileChildren(
    ProtectedSettingsPluginRouteRouteChildren,
  )

interface ProtectedSettingsTeamRouteRouteChildren {
  ProtectedSettingsTeamIndexRoute: typeof ProtectedSettingsTeamIndexRoute
  ProtectedSettingsTeamMembersIndexRoute: typeof ProtectedSettingsTeamMembersIndexRoute
  ProtectedSettingsTeamRolesIndexRoute: typeof ProtectedSettingsTeamRolesIndexRoute
}

const ProtectedSettingsTeamRouteRouteChildren: ProtectedSettingsTeamRouteRouteChildren =
  {
    ProtectedSettingsTeamIndexRoute: ProtectedSettingsTeamIndexRoute,
    ProtectedSettingsTeamMembersIndexRoute:
      ProtectedSettingsTeamMembersIndexRoute,
    ProtectedSettingsTeamRolesIndexRoute: ProtectedSettingsTeamRolesIndexRoute,
  }

const ProtectedSettingsTeamRouteRouteWithChildren =
  ProtectedSettingsTeamRouteRoute._addFileChildren(
    ProtectedSettingsTeamRouteRouteChildren,
  )

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsPluginRouteRoute: typeof ProtectedSettingsPluginRouteRouteWithChildren
  ProtectedSettingsTeamRouteRoute: typeof ProtectedSettingsTeamRouteRouteWithChildren
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSettingsIrrigationIndexRoute: typeof ProtectedSettingsIrrigationIndexRoute
  ProtectedSettingsMapIndexRoute: typeof ProtectedSettingsMapIndexRoute
  ProtectedSettingsNotificationsIndexRoute: typeof ProtectedSettingsNotificationsIndexRoute
  ProtectedSettingsOrganizationIndexRoute: typeof ProtectedSettingsOrganizationIndexRoute
  ProtectedSettingsProfileIndexRoute: typeof ProtectedSettingsProfileIndexRoute
  ProtectedSettingsSensorsIndexRoute: typeof ProtectedSettingsSensorsIndexRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsPluginRouteRoute:
      ProtectedSettingsPluginRouteRouteWithChildren,
    ProtectedSettingsTeamRouteRoute:
      ProtectedSettingsTeamRouteRouteWithChildren,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
    ProtectedSettingsIrrigationIndexRoute:
      ProtectedSettingsIrrigationIndexRoute,
    ProtectedSettingsMapIndexRoute: ProtectedSettingsMapIndexRoute,
    ProtectedSettingsNotificationsIndexRoute:
      ProtectedSettingsNotificationsIndexRoute,
    ProtectedSettingsOrganizationIndexRoute:
      ProtectedSettingsOrganizationIndexRoute,
    ProtectedSettingsProfileIndexRoute: ProtectedSettingsProfileIndexRoute,
    ProtectedSettingsSensorsIndexRoute: ProtectedSettingsSensorsIndexRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedTreeclusterTreeclusterIdRouteRouteChildren {
  ProtectedTreeclusterTreeclusterIdIndexRoute: typeof ProtectedTreeclusterTreeclusterIdIndexRoute
}

const ProtectedTreeclusterTreeclusterIdRouteRouteChildren: ProtectedTreeclusterTreeclusterIdRouteRouteChildren =
  {
    ProtectedTreeclusterTreeclusterIdIndexRoute:
      ProtectedTreeclusterTreeclusterIdIndexRoute,
  }

const ProtectedTreeclusterTreeclusterIdRouteRouteWithChildren =
  ProtectedTreeclusterTreeclusterIdRouteRoute._addFileChildren(
    ProtectedTreeclusterTreeclusterIdRouteRouteChildren,
  )

interface ProtectedTreeclusterRouteRouteChildren {
  ProtectedTreeclusterTreeclusterIdRouteRoute: typeof ProtectedTreeclusterTreeclusterIdRouteRouteWithChildren
  ProtectedTreeclusterIndexRoute: typeof ProtectedTreeclusterIndexRoute
}

const ProtectedTreeclusterRouteRouteChildren: ProtectedTreeclusterRouteRouteChildren =
  {
    ProtectedTreeclusterTreeclusterIdRouteRoute:
      ProtectedTreeclusterTreeclusterIdRouteRouteWithChildren,
    ProtectedTreeclusterIndexRoute: ProtectedTreeclusterIndexRoute,
  }

const ProtectedTreeclusterRouteRouteWithChildren =
  ProtectedTreeclusterRouteRoute._addFileChildren(
    ProtectedTreeclusterRouteRouteChildren,
  )

interface ProtectedTreesTreeIdRouteRouteChildren {
  ProtectedTreesTreeIdIndexRoute: typeof ProtectedTreesTreeIdIndexRoute
}

const ProtectedTreesTreeIdRouteRouteChildren: ProtectedTreesTreeIdRouteRouteChildren =
  {
    ProtectedTreesTreeIdIndexRoute: ProtectedTreesTreeIdIndexRoute,
  }

const ProtectedTreesTreeIdRouteRouteWithChildren =
  ProtectedTreesTreeIdRouteRoute._addFileChildren(
    ProtectedTreesTreeIdRouteRouteChildren,
  )

interface ProtectedTreesRouteRouteChildren {
  ProtectedTreesTreeIdRouteRoute: typeof ProtectedTreesTreeIdRouteRouteWithChildren
  ProtectedTreesIndexRoute: typeof ProtectedTreesIndexRoute
}

const ProtectedTreesRouteRouteChildren: ProtectedTreesRouteRouteChildren = {
  ProtectedTreesTreeIdRouteRoute: ProtectedTreesTreeIdRouteRouteWithChildren,
  ProtectedTreesIndexRoute: ProtectedTreesIndexRoute,
}

const ProtectedTreesRouteRouteWithChildren =
  ProtectedTreesRouteRoute._addFileChildren(ProtectedTreesRouteRouteChildren)

interface ProtectedVehiclesVehicleIdRouteRouteChildren {
  ProtectedVehiclesVehicleIdIndexRoute: typeof ProtectedVehiclesVehicleIdIndexRoute
}

const ProtectedVehiclesVehicleIdRouteRouteChildren: ProtectedVehiclesVehicleIdRouteRouteChildren =
  {
    ProtectedVehiclesVehicleIdIndexRoute: ProtectedVehiclesVehicleIdIndexRoute,
  }

const ProtectedVehiclesVehicleIdRouteRouteWithChildren =
  ProtectedVehiclesVehicleIdRouteRoute._addFileChildren(
    ProtectedVehiclesVehicleIdRouteRouteChildren,
  )

interface ProtectedVehiclesFormularVehicleIdEditRouteRouteChildren {
  ProtectedVehiclesFormularVehicleIdEditIndexRoute: typeof ProtectedVehiclesFormularVehicleIdEditIndexRoute
}

const ProtectedVehiclesFormularVehicleIdEditRouteRouteChildren: ProtectedVehiclesFormularVehicleIdEditRouteRouteChildren =
  {
    ProtectedVehiclesFormularVehicleIdEditIndexRoute:
      ProtectedVehiclesFormularVehicleIdEditIndexRoute,
  }

const ProtectedVehiclesFormularVehicleIdEditRouteRouteWithChildren =
  ProtectedVehiclesFormularVehicleIdEditRouteRoute._addFileChildren(
    ProtectedVehiclesFormularVehicleIdEditRouteRouteChildren,
  )

interface ProtectedVehiclesFormularVehicleIdRouteRouteChildren {
  ProtectedVehiclesFormularVehicleIdEditRouteRoute: typeof ProtectedVehiclesFormularVehicleIdEditRouteRouteWithChildren
}

const ProtectedVehiclesFormularVehicleIdRouteRouteChildren: ProtectedVehiclesFormularVehicleIdRouteRouteChildren =
  {
    ProtectedVehiclesFormularVehicleIdEditRouteRoute:
      ProtectedVehiclesFormularVehicleIdEditRouteRouteWithChildren,
  }

const ProtectedVehiclesFormularVehicleIdRouteRouteWithChildren =
  ProtectedVehiclesFormularVehicleIdRouteRoute._addFileChildren(
    ProtectedVehiclesFormularVehicleIdRouteRouteChildren,
  )

interface ProtectedVehiclesFormularNewRouteRouteChildren {
  ProtectedVehiclesFormularNewIndexRoute: typeof ProtectedVehiclesFormularNewIndexRoute
}

const ProtectedVehiclesFormularNewRouteRouteChildren: ProtectedVehiclesFormularNewRouteRouteChildren =
  {
    ProtectedVehiclesFormularNewIndexRoute:
      ProtectedVehiclesFormularNewIndexRoute,
  }

const ProtectedVehiclesFormularNewRouteRouteWithChildren =
  ProtectedVehiclesFormularNewRouteRoute._addFileChildren(
    ProtectedVehiclesFormularNewRouteRouteChildren,
  )

interface ProtectedVehiclesRouteRouteChildren {
  ProtectedVehiclesVehicleIdRouteRoute: typeof ProtectedVehiclesVehicleIdRouteRouteWithChildren
  ProtectedVehiclesIndexRoute: typeof ProtectedVehiclesIndexRoute
  ProtectedVehiclesFormularVehicleIdRouteRoute: typeof ProtectedVehiclesFormularVehicleIdRouteRouteWithChildren
  ProtectedVehiclesFormularNewRouteRoute: typeof ProtectedVehiclesFormularNewRouteRouteWithChildren
}

const ProtectedVehiclesRouteRouteChildren: ProtectedVehiclesRouteRouteChildren =
  {
    ProtectedVehiclesVehicleIdRouteRoute:
      ProtectedVehiclesVehicleIdRouteRouteWithChildren,
    ProtectedVehiclesIndexRoute: ProtectedVehiclesIndexRoute,
    ProtectedVehiclesFormularVehicleIdRouteRoute:
      ProtectedVehiclesFormularVehicleIdRouteRouteWithChildren,
    ProtectedVehiclesFormularNewRouteRoute:
      ProtectedVehiclesFormularNewRouteRouteWithChildren,
  }

const ProtectedVehiclesRouteRouteWithChildren =
  ProtectedVehiclesRouteRoute._addFileChildren(
    ProtectedVehiclesRouteRouteChildren,
  )

interface ProtectedWateringPlansWateringPlanIdRouteRouteChildren {
  ProtectedWateringPlansWateringPlanIdIndexRoute: typeof ProtectedWateringPlansWateringPlanIdIndexRoute
}

const ProtectedWateringPlansWateringPlanIdRouteRouteChildren: ProtectedWateringPlansWateringPlanIdRouteRouteChildren =
  {
    ProtectedWateringPlansWateringPlanIdIndexRoute:
      ProtectedWateringPlansWateringPlanIdIndexRoute,
  }

const ProtectedWateringPlansWateringPlanIdRouteRouteWithChildren =
  ProtectedWateringPlansWateringPlanIdRouteRoute._addFileChildren(
    ProtectedWateringPlansWateringPlanIdRouteRouteChildren,
  )

interface ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteChildren {
  ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute: typeof ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute
}

const ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteChildren: ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteChildren =
  {
    ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute:
      ProtectedWateringPlansFormularWateringPlanIdEditIndexRoute,
  }

const ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteWithChildren =
  ProtectedWateringPlansFormularWateringPlanIdEditRouteRoute._addFileChildren(
    ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteChildren,
  )

interface ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteChildren {
  ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute: typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute
}

const ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteChildren: ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteChildren =
  {
    ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute:
      ProtectedWateringPlansFormularWateringPlanIdStatusEditIndexRoute,
  }

const ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteWithChildren =
  ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRoute._addFileChildren(
    ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteChildren,
  )

interface ProtectedWateringPlansFormularWateringPlanIdRouteRouteChildren {
  ProtectedWateringPlansFormularWateringPlanIdEditRouteRoute: typeof ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteWithChildren
  ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRoute: typeof ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteWithChildren
}

const ProtectedWateringPlansFormularWateringPlanIdRouteRouteChildren: ProtectedWateringPlansFormularWateringPlanIdRouteRouteChildren =
  {
    ProtectedWateringPlansFormularWateringPlanIdEditRouteRoute:
      ProtectedWateringPlansFormularWateringPlanIdEditRouteRouteWithChildren,
    ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRoute:
      ProtectedWateringPlansFormularWateringPlanIdStatusEditRouteRouteWithChildren,
  }

const ProtectedWateringPlansFormularWateringPlanIdRouteRouteWithChildren =
  ProtectedWateringPlansFormularWateringPlanIdRouteRoute._addFileChildren(
    ProtectedWateringPlansFormularWateringPlanIdRouteRouteChildren,
  )

interface ProtectedWateringPlansFormularNewRouteRouteChildren {
  ProtectedWateringPlansFormularNewIndexRoute: typeof ProtectedWateringPlansFormularNewIndexRoute
}

const ProtectedWateringPlansFormularNewRouteRouteChildren: ProtectedWateringPlansFormularNewRouteRouteChildren =
  {
    ProtectedWateringPlansFormularNewIndexRoute:
      ProtectedWateringPlansFormularNewIndexRoute,
  }

const ProtectedWateringPlansFormularNewRouteRouteWithChildren =
  ProtectedWateringPlansFormularNewRouteRoute._addFileChildren(
    ProtectedWateringPlansFormularNewRouteRouteChildren,
  )

interface ProtectedWateringPlansRouteRouteChildren {
  ProtectedWateringPlansWateringPlanIdRouteRoute: typeof ProtectedWateringPlansWateringPlanIdRouteRouteWithChildren
  ProtectedWateringPlansIndexRoute: typeof ProtectedWateringPlansIndexRoute
  ProtectedWateringPlansFormularWateringPlanIdRouteRoute: typeof ProtectedWateringPlansFormularWateringPlanIdRouteRouteWithChildren
  ProtectedWateringPlansFormularNewRouteRoute: typeof ProtectedWateringPlansFormularNewRouteRouteWithChildren
}

const ProtectedWateringPlansRouteRouteChildren: ProtectedWateringPlansRouteRouteChildren =
  {
    ProtectedWateringPlansWateringPlanIdRouteRoute:
      ProtectedWateringPlansWateringPlanIdRouteRouteWithChildren,
    ProtectedWateringPlansIndexRoute: ProtectedWateringPlansIndexRoute,
    ProtectedWateringPlansFormularWateringPlanIdRouteRoute:
      ProtectedWateringPlansFormularWateringPlanIdRouteRouteWithChildren,
    ProtectedWateringPlansFormularNewRouteRoute:
      ProtectedWateringPlansFormularNewRouteRouteWithChildren,
  }

const ProtectedWateringPlansRouteRouteWithChildren =
  ProtectedWateringPlansRouteRoute._addFileChildren(
    ProtectedWateringPlansRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedDebugRouteRoute: typeof ProtectedDebugRouteRouteWithChildren
  ProtectedEvaluationsRouteRoute: typeof ProtectedEvaluationsRouteRouteWithChildren
  ProtectedMapRouteRoute: typeof ProtectedMapRouteRouteWithChildren
  ProtectedSensorsRouteRoute: typeof ProtectedSensorsRouteRouteWithChildren
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedTreeclusterRouteRoute: typeof ProtectedTreeclusterRouteRouteWithChildren
  ProtectedTreesRouteRoute: typeof ProtectedTreesRouteRouteWithChildren
  ProtectedVehiclesRouteRoute: typeof ProtectedVehiclesRouteRouteWithChildren
  ProtectedWateringPlansRouteRoute: typeof ProtectedWateringPlansRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedInfoRoute: typeof ProtectedInfoRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDebugRouteRoute: ProtectedDebugRouteRouteWithChildren,
  ProtectedEvaluationsRouteRoute: ProtectedEvaluationsRouteRouteWithChildren,
  ProtectedMapRouteRoute: ProtectedMapRouteRouteWithChildren,
  ProtectedSensorsRouteRoute: ProtectedSensorsRouteRouteWithChildren,
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedTreeclusterRouteRoute: ProtectedTreeclusterRouteRouteWithChildren,
  ProtectedTreesRouteRoute: ProtectedTreesRouteRouteWithChildren,
  ProtectedVehiclesRouteRoute: ProtectedVehiclesRouteRouteWithChildren,
  ProtectedWateringPlansRouteRoute:
    ProtectedWateringPlansRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedInfoRoute: ProtectedInfoRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  HelpSlugRoute: HelpSlugRoute,
  HelpIndexRoute: HelpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
