[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Green Ecolution backend server"
readme = "../../../README.md"
publish.workspace = true
build = "build.rs"
default-run = "green-ecolution"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "green-ecolution"

[[bin]]
path = "src/bin/migrate.rs"
name = "migrate"

[[bin]]
path = "src/bin/dump-openapi.rs"
name = "dump-openapi"

[[bin]]
path = "src/bin/import_kataster_fl.rs"
name = "import-kataster-fl"

[[test]]
name = "api"
path = "test/api/main.rs"

[dependencies]
anyhow = "1.0.102"
async-trait = { workspace = true }
axum = { version = "0.8.9", features = ["json"] }
axum-extra = { version = "0.12", features = ["query"] }
base64 = "0.23"
chrono = { workspace = true }
config = "0.15.23"
domain = { path = "../domain", features = ["sqlx"] }
futures = "0.3"
hostname = "0.4"
include_dir = "0.7"
jsonwebtoken = { version = "11.0", default-features = false, features = ["use_pem", "aws_lc_rs"] }
log = "0.4"
rand = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
rumqttc = "0.25"
rust_decimal = { version = "1.42", default-features = false }
secrecy = { workspace = true }
serde = { workspace = true }
serde-aux = "4.7.0"
serde_json = { workspace = true }
serde_urlencoded = "0.7"
sha2 = { workspace = true }
sqlx = { workspace = true, features = ["macros", "migrate", "runtime-tokio", "tls-rustls", "postgres", "chrono", "uuid", "json", "rust_decimal"] }
thiserror = { workspace = true }
tokio = { version = "1.52.3", features = ["full"] }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.7.0", features = ["catch-panic", "cors", "trace", "request-id"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = { workspace = true }
uuid = { workspace = true }
utoipa = { version = "5", features = ["axum_extras", "uuid", "chrono"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum", "vendored"] }
polyline = "0.11.0"

[dev-dependencies]
claims = "0.8"
domain = { path = "../domain", features = ["sqlx"] }
geo-types = "0.7.19"
libc = "0.2"
quickcheck = "1"
quickcheck_macros = "1"
rsa = { version = "0.9", features = ["sha2"] }
testcontainers = { version = "0.27", features = ["watchdog"] }
testcontainers-modules = { version = "0.15", features = ["postgres"] }
urlencoding = "2"
wiremock = "0.6.5"

[build-dependencies]
chrono = { workspace = true }
