/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentResponse,
  CreateCommentRequest,
  ErrorBody,
  ListResponseCommentResponse,
  UpdateCommentRequest,
} from '../models/index';
import {
    CommentResponseFromJSON,
    CommentResponseToJSON,
    CreateCommentRequestFromJSON,
    CreateCommentRequestToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListResponseCommentResponseFromJSON,
    ListResponseCommentResponseToJSON,
    UpdateCommentRequestFromJSON,
    UpdateCommentRequestToJSON,
} from '../models/index';

export interface CreateClusterCommentRequest {
    clusterId: string;
    createCommentRequest: CreateCommentRequest;
}

export interface CreateWateringPlanCommentRequest {
    wateringPlanId: string;
    createCommentRequest: CreateCommentRequest;
}

export interface DeleteClusterCommentRequest {
    clusterId: string;
    commentId: string;
}

export interface DeleteWateringPlanCommentRequest {
    wateringPlanId: string;
    commentId: string;
}

export interface ListClusterCommentsRequest {
    clusterId: string;
    page?: number;
    perPage?: number;
}

export interface ListWateringPlanCommentsRequest {
    wateringPlanId: string;
    page?: number;
    perPage?: number;
}

export interface UpdateClusterCommentRequest {
    clusterId: string;
    commentId: string;
    updateCommentRequest: UpdateCommentRequest;
}

export interface UpdateWateringPlanCommentRequest {
    wateringPlanId: string;
    commentId: string;
    updateCommentRequest: UpdateCommentRequest;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Adds a comment to a tree cluster. Requires `tree_cluster:read` in the cluster\'s organization — anyone who may see the cluster may annotate it.
     * Comment on a tree cluster
     */
    async createClusterCommentRaw(requestParameters: CreateClusterCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling createClusterComment().'
            );
        }

        if (requestParameters['createCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCommentRequest',
                'Required parameter "createCommentRequest" was null or undefined when calling createClusterComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters/{cluster_id}/comments`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommentRequestToJSON(requestParameters['createCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseFromJSON(jsonValue));
    }

    /**
     * Adds a comment to a tree cluster. Requires `tree_cluster:read` in the cluster\'s organization — anyone who may see the cluster may annotate it.
     * Comment on a tree cluster
     */
    async createClusterComment(requestParameters: CreateClusterCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponse> {
        const response = await this.createClusterCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a comment to a watering plan. Requires `watering_plan:read` in the plan\'s organization — anyone who may see the plan may annotate it.
     * Comment on a watering plan
     */
    async createWateringPlanCommentRaw(requestParameters: CreateWateringPlanCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponse>> {
        if (requestParameters['wateringPlanId'] == null) {
            throw new runtime.RequiredError(
                'wateringPlanId',
                'Required parameter "wateringPlanId" was null or undefined when calling createWateringPlanComment().'
            );
        }

        if (requestParameters['createCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCommentRequest',
                'Required parameter "createCommentRequest" was null or undefined when calling createWateringPlanComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/watering-plans/{watering_plan_id}/comments`;
        urlPath = urlPath.replace(`{${"watering_plan_id"}}`, encodeURIComponent(String(requestParameters['wateringPlanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommentRequestToJSON(requestParameters['createCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseFromJSON(jsonValue));
    }

    /**
     * Adds a comment to a watering plan. Requires `watering_plan:read` in the plan\'s organization — anyone who may see the plan may annotate it.
     * Comment on a watering plan
     */
    async createWateringPlanComment(requestParameters: CreateWateringPlanCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponse> {
        const response = await this.createWateringPlanCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes a comment. Only the comment\'s author may delete it.
     * Delete a comment on a tree cluster
     */
    async deleteClusterCommentRaw(requestParameters: DeleteClusterCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling deleteClusterComment().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling deleteClusterComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}/comments/{comment_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));
        urlPath = urlPath.replace(`{${"comment_id"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a comment. Only the comment\'s author may delete it.
     * Delete a comment on a tree cluster
     */
    async deleteClusterComment(requestParameters: DeleteClusterCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteClusterCommentRaw(requestParameters, initOverrides);
    }

    /**
     * Removes a comment. Only the comment\'s author may delete it.
     * Delete a comment on a watering plan
     */
    async deleteWateringPlanCommentRaw(requestParameters: DeleteWateringPlanCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['wateringPlanId'] == null) {
            throw new runtime.RequiredError(
                'wateringPlanId',
                'Required parameter "wateringPlanId" was null or undefined when calling deleteWateringPlanComment().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling deleteWateringPlanComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/watering-plans/{watering_plan_id}/comments/{comment_id}`;
        urlPath = urlPath.replace(`{${"watering_plan_id"}}`, encodeURIComponent(String(requestParameters['wateringPlanId'])));
        urlPath = urlPath.replace(`{${"comment_id"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a comment. Only the comment\'s author may delete it.
     * Delete a comment on a watering plan
     */
    async deleteWateringPlanComment(requestParameters: DeleteWateringPlanCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWateringPlanCommentRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the comments of a tree cluster, newest first. Requires `tree_cluster:read` in the cluster\'s organization.
     * List comments on a tree cluster
     */
    async listClusterCommentsRaw(requestParameters: ListClusterCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseCommentResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling listClusterComments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}/comments`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseCommentResponseFromJSON(jsonValue));
    }

    /**
     * Returns the comments of a tree cluster, newest first. Requires `tree_cluster:read` in the cluster\'s organization.
     * List comments on a tree cluster
     */
    async listClusterComments(requestParameters: ListClusterCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseCommentResponse> {
        const response = await this.listClusterCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the comments of a watering plan, newest first. Requires `watering_plan:read` in the plan\'s organization.
     * List comments on a watering plan
     */
    async listWateringPlanCommentsRaw(requestParameters: ListWateringPlanCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseCommentResponse>> {
        if (requestParameters['wateringPlanId'] == null) {
            throw new runtime.RequiredError(
                'wateringPlanId',
                'Required parameter "wateringPlanId" was null or undefined when calling listWateringPlanComments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/watering-plans/{watering_plan_id}/comments`;
        urlPath = urlPath.replace(`{${"watering_plan_id"}}`, encodeURIComponent(String(requestParameters['wateringPlanId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseCommentResponseFromJSON(jsonValue));
    }

    /**
     * Returns the comments of a watering plan, newest first. Requires `watering_plan:read` in the plan\'s organization.
     * List comments on a watering plan
     */
    async listWateringPlanComments(requestParameters: ListWateringPlanCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseCommentResponse> {
        const response = await this.listWateringPlanCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces a comment\'s text. Only the comment\'s author may edit it.
     * Edit a comment on a tree cluster
     */
    async updateClusterCommentRaw(requestParameters: UpdateClusterCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling updateClusterComment().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling updateClusterComment().'
            );
        }

        if (requestParameters['updateCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCommentRequest',
                'Required parameter "updateCommentRequest" was null or undefined when calling updateClusterComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters/{cluster_id}/comments/{comment_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));
        urlPath = urlPath.replace(`{${"comment_id"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommentRequestToJSON(requestParameters['updateCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseFromJSON(jsonValue));
    }

    /**
     * Replaces a comment\'s text. Only the comment\'s author may edit it.
     * Edit a comment on a tree cluster
     */
    async updateClusterComment(requestParameters: UpdateClusterCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponse> {
        const response = await this.updateClusterCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces a comment\'s text. Only the comment\'s author may edit it.
     * Edit a comment on a watering plan
     */
    async updateWateringPlanCommentRaw(requestParameters: UpdateWateringPlanCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponse>> {
        if (requestParameters['wateringPlanId'] == null) {
            throw new runtime.RequiredError(
                'wateringPlanId',
                'Required parameter "wateringPlanId" was null or undefined when calling updateWateringPlanComment().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling updateWateringPlanComment().'
            );
        }

        if (requestParameters['updateCommentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCommentRequest',
                'Required parameter "updateCommentRequest" was null or undefined when calling updateWateringPlanComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/watering-plans/{watering_plan_id}/comments/{comment_id}`;
        urlPath = urlPath.replace(`{${"watering_plan_id"}}`, encodeURIComponent(String(requestParameters['wateringPlanId'])));
        urlPath = urlPath.replace(`{${"comment_id"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCommentRequestToJSON(requestParameters['updateCommentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseFromJSON(jsonValue));
    }

    /**
     * Replaces a comment\'s text. Only the comment\'s author may edit it.
     * Edit a comment on a watering plan
     */
    async updateWateringPlanComment(requestParameters: UpdateWateringPlanCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponse> {
        const response = await this.updateWateringPlanCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
