/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorBody,
  ListResponseRegionResponse,
  RegionResponse,
} from '../models/index';
import {
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListResponseRegionResponseFromJSON,
    ListResponseRegionResponseToJSON,
    RegionResponseFromJSON,
    RegionResponseToJSON,
} from '../models/index';

export interface GetRegionRequest {
    regionId: string;
}

export interface ListRegionsRequest {
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class RegionsApi extends runtime.BaseAPI {

    /**
     * Returns a single region by its unique identifier.
     * Get a region
     */
    async getRegionRaw(requestParameters: GetRegionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegionResponse>> {
        if (requestParameters['regionId'] == null) {
            throw new runtime.RequiredError(
                'regionId',
                'Required parameter "regionId" was null or undefined when calling getRegion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/regions/{region_id}`;
        urlPath = urlPath.replace(`{${"region_id"}}`, encodeURIComponent(String(requestParameters['regionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single region by its unique identifier.
     * Get a region
     */
    async getRegion(requestParameters: GetRegionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegionResponse> {
        const response = await this.getRegionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of all geographic regions used to organize tree clusters.
     * List all regions
     */
    async listRegionsRaw(requestParameters: ListRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseRegionResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/regions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseRegionResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of all geographic regions used to organize tree clusters.
     * List all regions
     */
    async listRegions(requestParameters: ListRegionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseRegionResponse> {
        const response = await this.listRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
