/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorBody,
  StartPointRequest,
  StartPointResponse,
  TransferRequest,
} from '../models/index';
import {
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    StartPointRequestFromJSON,
    StartPointRequestToJSON,
    StartPointResponseFromJSON,
    StartPointResponseToJSON,
    TransferRequestFromJSON,
    TransferRequestToJSON,
} from '../models/index';

export interface CreateStartPointRequest {
    startPointRequest: StartPointRequest;
}

export interface DeleteStartPointRequest {
    startPointId: string;
}

export interface SetDefaultStartPointRequest {
    startPointId: string;
}

export interface TransferStartPointRequest {
    startPointId: string;
    transferRequest: TransferRequest;
}

export interface UpdateStartPointRequest {
    startPointId: string;
    startPointRequest: StartPointRequest;
}

/**
 * 
 */
export class RoutingApi extends runtime.BaseAPI {

    /**
     * Create a start point
     */
    async createStartPointRaw(requestParameters: CreateStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartPointResponse>> {
        if (requestParameters['startPointRequest'] == null) {
            throw new runtime.RequiredError(
                'startPointRequest',
                'Required parameter "startPointRequest" was null or undefined when calling createStartPoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/routing/start-points`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartPointRequestToJSON(requestParameters['startPointRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartPointResponseFromJSON(jsonValue));
    }

    /**
     * Create a start point
     */
    async createStartPoint(requestParameters: CreateStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartPointResponse> {
        const response = await this.createStartPointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a start point
     */
    async deleteStartPointRaw(requestParameters: DeleteStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['startPointId'] == null) {
            throw new runtime.RequiredError(
                'startPointId',
                'Required parameter "startPointId" was null or undefined when calling deleteStartPoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/routing/start-points/{start_point_id}`;
        urlPath = urlPath.replace(`{${"start_point_id"}}`, encodeURIComponent(String(requestParameters['startPointId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a start point
     */
    async deleteStartPoint(requestParameters: DeleteStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteStartPointRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the persisted named start/return points for watering routes.
     * List routing start points
     */
    async listRoutingStartPointsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StartPointResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/routing/start-points`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StartPointResponseFromJSON));
    }

    /**
     * Returns the persisted named start/return points for watering routes.
     * List routing start points
     */
    async listRoutingStartPoints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StartPointResponse>> {
        const response = await this.listRoutingStartPointsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Set the default start point
     */
    async setDefaultStartPointRaw(requestParameters: SetDefaultStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['startPointId'] == null) {
            throw new runtime.RequiredError(
                'startPointId',
                'Required parameter "startPointId" was null or undefined when calling setDefaultStartPoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/routing/start-points/{start_point_id}/default`;
        urlPath = urlPath.replace(`{${"start_point_id"}}`, encodeURIComponent(String(requestParameters['startPointId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set the default start point
     */
    async setDefaultStartPoint(requestParameters: SetDefaultStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setDefaultStartPointRaw(requestParameters, initOverrides);
    }

    /**
     * Moves a start point to a different owning organization. If it was the default for its organization, it loses that status (the target organization\'s own default, if any, is left untouched). Requires `watering_plan:update` in both the source and target organization.
     * Transfer a start point\'s ownership to another organization
     */
    async transferStartPointRaw(requestParameters: TransferStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['startPointId'] == null) {
            throw new runtime.RequiredError(
                'startPointId',
                'Required parameter "startPointId" was null or undefined when calling transferStartPoint().'
            );
        }

        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transferStartPoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/routing/start-points/{start_point_id}/organization`;
        urlPath = urlPath.replace(`{${"start_point_id"}}`, encodeURIComponent(String(requestParameters['startPointId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Moves a start point to a different owning organization. If it was the default for its organization, it loses that status (the target organization\'s own default, if any, is left untouched). Requires `watering_plan:update` in both the source and target organization.
     * Transfer a start point\'s ownership to another organization
     */
    async transferStartPoint(requestParameters: TransferStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferStartPointRaw(requestParameters, initOverrides);
    }

    /**
     * Update a start point
     */
    async updateStartPointRaw(requestParameters: UpdateStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartPointResponse>> {
        if (requestParameters['startPointId'] == null) {
            throw new runtime.RequiredError(
                'startPointId',
                'Required parameter "startPointId" was null or undefined when calling updateStartPoint().'
            );
        }

        if (requestParameters['startPointRequest'] == null) {
            throw new runtime.RequiredError(
                'startPointRequest',
                'Required parameter "startPointRequest" was null or undefined when calling updateStartPoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/routing/start-points/{start_point_id}`;
        urlPath = urlPath.replace(`{${"start_point_id"}}`, encodeURIComponent(String(requestParameters['startPointId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StartPointRequestToJSON(requestParameters['startPointRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartPointResponseFromJSON(jsonValue));
    }

    /**
     * Update a start point
     */
    async updateStartPoint(requestParameters: UpdateStartPointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartPointResponse> {
        const response = await this.updateStartPointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
