/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcknowledgeDataQualityRequest,
  ActivateSensorRequest,
  CreateSensorRequest,
  ErrorBody,
  ListResponseSensorDataResponse,
  ListResponseSensorResponse,
  SensorDataQualityResponse,
  SensorModelResponse,
  SensorResponse,
  SetSensorTreeRequest,
  SoilMoistureSeriesResponse,
  TransferRequest,
} from '../models/index';
import {
    AcknowledgeDataQualityRequestFromJSON,
    AcknowledgeDataQualityRequestToJSON,
    ActivateSensorRequestFromJSON,
    ActivateSensorRequestToJSON,
    CreateSensorRequestFromJSON,
    CreateSensorRequestToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListResponseSensorDataResponseFromJSON,
    ListResponseSensorDataResponseToJSON,
    ListResponseSensorResponseFromJSON,
    ListResponseSensorResponseToJSON,
    SensorDataQualityResponseFromJSON,
    SensorDataQualityResponseToJSON,
    SensorModelResponseFromJSON,
    SensorModelResponseToJSON,
    SensorResponseFromJSON,
    SensorResponseToJSON,
    SetSensorTreeRequestFromJSON,
    SetSensorTreeRequestToJSON,
    SoilMoistureSeriesResponseFromJSON,
    SoilMoistureSeriesResponseToJSON,
    TransferRequestFromJSON,
    TransferRequestToJSON,
} from '../models/index';

export interface AcknowledgeSensorDataQualityRequest {
    sensorId: string;
    acknowledgeDataQualityRequest: AcknowledgeDataQualityRequest;
}

export interface ActivateSensorOperationRequest {
    sensorId: string;
    activateSensorRequest: ActivateSensorRequest;
}

export interface CreateSensorOperationRequest {
    createSensorRequest: CreateSensorRequest;
}

export interface DeleteSensorRequest {
    sensorId: string;
}

export interface GetSensorRequest {
    sensorId: string;
}

export interface GetSensorDataQualityRequest {
    sensorId: string;
}

export interface GetSensorModelRequest {
    id: string;
}

export interface GetSensorSoilMoistureRequest {
    sensorId: string;
    from?: Date | null;
    to?: Date | null;
    bucket?: string | null;
}

export interface ListSensorDataRequest {
    sensorId: string;
    page?: number;
    perPage?: number;
    from?: Date | null;
    to?: Date | null;
}

export interface ListSensorsRequest {
    page?: number;
    perPage?: number;
}

export interface RemoveSensorTreeRequest {
    sensorId: string;
}

export interface SetSensorTreeOperationRequest {
    sensorId: string;
    setSensorTreeRequest: SetSensorTreeRequest;
}

export interface TransferSensorRequest {
    sensorId: string;
    transferRequest: TransferRequest;
}

/**
 * 
 */
export class SensorsApi extends runtime.BaseAPI {

    /**
     * Records that the flagged readings up to now have been reviewed. Readings flagged afterwards raise the warning again on their own.
     * Acknowledge a sensor\'s flagged readings
     */
    async acknowledgeSensorDataQualityRaw(requestParameters: AcknowledgeSensorDataQualityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorDataQualityResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling acknowledgeSensorDataQuality().'
            );
        }

        if (requestParameters['acknowledgeDataQualityRequest'] == null) {
            throw new runtime.RequiredError(
                'acknowledgeDataQualityRequest',
                'Required parameter "acknowledgeDataQualityRequest" was null or undefined when calling acknowledgeSensorDataQuality().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sensors/{sensor_id}/data-quality/acknowledge`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcknowledgeDataQualityRequestToJSON(requestParameters['acknowledgeDataQualityRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorDataQualityResponseFromJSON(jsonValue));
    }

    /**
     * Records that the flagged readings up to now have been reviewed. Readings flagged afterwards raise the warning again on their own.
     * Acknowledge a sensor\'s flagged readings
     */
    async acknowledgeSensorDataQuality(requestParameters: AcknowledgeSensorDataQualityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorDataQualityResponse> {
        const response = await this.acknowledgeSensorDataQualityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Transitions a sensor from `Prepared` to `Offline` and attaches it to the given tree. Idempotent if the sensor is already attached to the same tree.
     * Activate a prepared sensor by binding it to a tree
     */
    async activateSensorRaw(requestParameters: ActivateSensorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling activateSensor().'
            );
        }

        if (requestParameters['activateSensorRequest'] == null) {
            throw new runtime.RequiredError(
                'activateSensorRequest',
                'Required parameter "activateSensorRequest" was null or undefined when calling activateSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sensors/{sensor_id}/activate`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActivateSensorRequestToJSON(requestParameters['activateSensorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     * Transitions a sensor from `Prepared` to `Offline` and attaches it to the given tree. Idempotent if the sensor is already attached to the same tree.
     * Activate a prepared sensor by binding it to a tree
     */
    async activateSensor(requestParameters: ActivateSensorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.activateSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a sensor record in `Prepared` state. The sensor must later be bound to a tree via `POST /sensors/{sensor_id}/activate` before it starts receiving data.
     * Register a new (prepared) sensor unit
     */
    async createSensorRaw(requestParameters: CreateSensorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['createSensorRequest'] == null) {
            throw new runtime.RequiredError(
                'createSensorRequest',
                'Required parameter "createSensorRequest" was null or undefined when calling createSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sensors`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSensorRequestToJSON(requestParameters['createSensorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     * Creates a sensor record in `Prepared` state. The sensor must later be bound to a tree via `POST /sensors/{sensor_id}/activate` before it starts receiving data.
     * Register a new (prepared) sensor unit
     */
    async createSensor(requestParameters: CreateSensorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.createSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes a sensor by its EUI identifier.
     * Delete a sensor
     */
    async deleteSensorRaw(requestParameters: DeleteSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling deleteSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a sensor by its EUI identifier.
     * Delete a sensor
     */
    async deleteSensor(requestParameters: DeleteSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSensorRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single sensor by its EUI identifier.
     * Get a sensor by ID
     */
    async getSensorRaw(requestParameters: GetSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling getSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single sensor by its EUI identifier.
     * Get a sensor by ID
     */
    async getSensor(requestParameters: GetSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.getSensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the derived data health, the number of values flagged as implausible in the last 7 days, and the most recent flagged values.
     * Get the data quality of a sensor
     */
    async getSensorDataQualityRaw(requestParameters: GetSensorDataQualityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorDataQualityResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling getSensorDataQuality().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}/data-quality`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorDataQualityResponseFromJSON(jsonValue));
    }

    /**
     * Returns the derived data health, the number of values flagged as implausible in the last 7 days, and the most recent flagged values.
     * Get the data quality of a sensor
     */
    async getSensorDataQuality(requestParameters: GetSensorDataQualityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorDataQualityResponse> {
        const response = await this.getSensorDataQualityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single sensor model
     */
    async getSensorModelRaw(requestParameters: GetSensorModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorModelResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSensorModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/models/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorModelResponseFromJSON(jsonValue));
    }

    /**
     * Get a single sensor model
     */
    async getSensorModel(requestParameters: GetSensorModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorModelResponse> {
        const response = await this.getSensorModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aggregates the sensor\'s volumetric soil-moisture readings (mean/min/max per probe depth and time bucket). Stress thresholds and the REW condition series are derived from the soil condition of the linked tree\'s cluster and are empty when the sensor is not linked or the soil is unknown.
     * Bucketed soil-moisture series for a sensor
     */
    async getSensorSoilMoistureRaw(requestParameters: GetSensorSoilMoistureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SoilMoistureSeriesResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling getSensorSoilMoisture().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}/soil-moisture`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SoilMoistureSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Aggregates the sensor\'s volumetric soil-moisture readings (mean/min/max per probe depth and time bucket). Stress thresholds and the REW condition series are derived from the soil condition of the linked tree\'s cluster and are empty when the sensor is not linked or the soil is unknown.
     * Bucketed soil-moisture series for a sensor
     */
    async getSensorSoilMoisture(requestParameters: GetSensorSoilMoistureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SoilMoistureSeriesResponse> {
        const response = await this.getSensorSoilMoistureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of historical data readings for a sensor, optionally restricted to a time range.
     * List sensor data
     */
    async listSensorDataRaw(requestParameters: ListSensorDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseSensorDataResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling listSensorData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}/data`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseSensorDataResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of historical data readings for a sensor, optionally restricted to a time range.
     * List sensor data
     */
    async listSensorData(requestParameters: ListSensorDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseSensorDataResponse> {
        const response = await this.listSensorDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns every sensor model registered in the catalogue along with its abilities (e.g. soil tension at 30/60/90 cm).
     * List all supported sensor models
     */
    async listSensorModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SensorModelResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/models`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SensorModelResponseFromJSON));
    }

    /**
     * Returns every sensor model registered in the catalogue along with its abilities (e.g. soil tension at 30/60/90 cm).
     * List all supported sensor models
     */
    async listSensorModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SensorModelResponse>> {
        const response = await this.listSensorModelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of all LoRaWAN sensors.
     * List all sensors
     */
    async listSensorsRaw(requestParameters: ListSensorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseSensorResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseSensorResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of all LoRaWAN sensors.
     * List all sensors
     */
    async listSensors(requestParameters: ListSensorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseSensorResponse> {
        const response = await this.listSensorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Detaches the sensor from its tree and deactivates it, returning it to the `Prepared` state. Idempotent for an already prepared sensor.
     * Remove a sensor\'s tree link and reset it to prepared
     */
    async removeSensorTreeRaw(requestParameters: RemoveSensorTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling removeSensorTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}/tree`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     * Detaches the sensor from its tree and deactivates it, returning it to the `Prepared` state. Idempotent for an already prepared sensor.
     * Remove a sensor\'s tree link and reset it to prepared
     */
    async removeSensorTree(requestParameters: RemoveSensorTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.removeSensorTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Re-links an already activated sensor to `tree_id`. Rejects a tree that already has a different sensor and a sensor that is not yet activated. Idempotent if the sensor is already linked to that tree.
     * Move an activated sensor to a different tree
     */
    async setSensorTreeRaw(requestParameters: SetSensorTreeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SensorResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling setSensorTree().'
            );
        }

        if (requestParameters['setSensorTreeRequest'] == null) {
            throw new runtime.RequiredError(
                'setSensorTreeRequest',
                'Required parameter "setSensorTreeRequest" was null or undefined when calling setSensorTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sensors/{sensor_id}/tree`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetSensorTreeRequestToJSON(requestParameters['setSensorTreeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SensorResponseFromJSON(jsonValue));
    }

    /**
     * Re-links an already activated sensor to `tree_id`. Rejects a tree that already has a different sensor and a sensor that is not yet activated. Idempotent if the sensor is already linked to that tree.
     * Move an activated sensor to a different tree
     */
    async setSensorTree(requestParameters: SetSensorTreeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SensorResponse> {
        const response = await this.setSensorTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Moves an unbound sensor to a different owning organization. Requires `sensor:update` in both the source and target organization. A sensor bound to a tree must be transferred via its tree instead.
     * Transfer a sensor\'s ownership to another organization
     */
    async transferSensorRaw(requestParameters: TransferSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling transferSensor().'
            );
        }

        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transferSensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/sensors/{sensor_id}/organization`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Moves an unbound sensor to a different owning organization. Requires `sensor:update` in both the source and target organization. A sensor bound to a tree must be transferred via its tree instead.
     * Transfer a sensor\'s ownership to another organization
     */
    async transferSensor(requestParameters: TransferSensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferSensorRaw(requestParameters, initOverrides);
    }

}
