/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorBody,
  ListResponseTreeResponse,
  NearestTreeListResponse,
  TransferRequest,
  TreeCreateRequest,
  TreeMarkerListResponse,
  TreeResponse,
  TreeUpdateRequest,
  WateringStatus,
} from '../models/index';
import {
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListResponseTreeResponseFromJSON,
    ListResponseTreeResponseToJSON,
    NearestTreeListResponseFromJSON,
    NearestTreeListResponseToJSON,
    TransferRequestFromJSON,
    TransferRequestToJSON,
    TreeCreateRequestFromJSON,
    TreeCreateRequestToJSON,
    TreeMarkerListResponseFromJSON,
    TreeMarkerListResponseToJSON,
    TreeResponseFromJSON,
    TreeResponseToJSON,
    TreeUpdateRequestFromJSON,
    TreeUpdateRequestToJSON,
    WateringStatusFromJSON,
    WateringStatusToJSON,
} from '../models/index';

export interface CreateTreeRequest {
    treeCreateRequest: TreeCreateRequest;
}

export interface DeleteTreeRequest {
    treeId: string;
}

export interface GetNearestTreesRequest {
    lat: number;
    lng: number;
    limit?: number | null;
}

export interface GetTreeRequest {
    treeId: string;
}

export interface GetTreeBySensorRequest {
    sensorId: string;
}

export interface ListTreeMarkersRequest {
    bbox: string;
    hasCluster?: boolean | null;
    plantingYear?: Array<number>;
    wateringStatus?: Array<WateringStatus>;
    organizationId?: string | null;
}

export interface ListTreesRequest {
    page?: number;
    perPage?: number;
    q?: string | null;
    wateringStatus?: Array<WateringStatus>;
    hasCluster?: boolean | null;
    plantingYear?: Array<number>;
}

export interface TransferTreeRequest {
    treeId: string;
    transferRequest: TransferRequest;
}

export interface UpdateTreeRequest {
    treeId: string;
    treeUpdateRequest: TreeUpdateRequest;
}

/**
 * 
 */
export class TreesApi extends runtime.BaseAPI {

    /**
     * Creates a new tree with location and optional cluster or sensor association.
     * Create a new tree
     */
    async createTreeRaw(requestParameters: CreateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeResponse>> {
        if (requestParameters['treeCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'treeCreateRequest',
                'Required parameter "treeCreateRequest" was null or undefined when calling createTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/trees`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TreeCreateRequestToJSON(requestParameters['treeCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new tree with location and optional cluster or sensor association.
     * Create a new tree
     */
    async createTree(requestParameters: CreateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeResponse> {
        const response = await this.createTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes a tree by its ID.
     * Delete a tree
     */
    async deleteTreeRaw(requestParameters: DeleteTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling deleteTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/trees/{tree_id}`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a tree by its ID.
     * Delete a tree
     */
    async deleteTree(requestParameters: DeleteTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTreeRaw(requestParameters, initOverrides);
    }

    /**
     * Finds trees closest to a given coordinate.
     * Get nearest trees
     */
    async getNearestTreesRaw(requestParameters: GetNearestTreesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NearestTreeListResponse>> {
        if (requestParameters['lat'] == null) {
            throw new runtime.RequiredError(
                'lat',
                'Required parameter "lat" was null or undefined when calling getNearestTrees().'
            );
        }

        if (requestParameters['lng'] == null) {
            throw new runtime.RequiredError(
                'lng',
                'Required parameter "lng" was null or undefined when calling getNearestTrees().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lng'] != null) {
            queryParameters['lng'] = requestParameters['lng'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/trees/nearest`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NearestTreeListResponseFromJSON(jsonValue));
    }

    /**
     * Finds trees closest to a given coordinate.
     * Get nearest trees
     */
    async getNearestTrees(requestParameters: GetNearestTreesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NearestTreeListResponse> {
        const response = await this.getNearestTreesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a single tree by its ID, including associated sensor data.
     * Get a tree by ID
     */
    async getTreeRaw(requestParameters: GetTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeResponse>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling getTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/trees/{tree_id}`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single tree by its ID, including associated sensor data.
     * Get a tree by ID
     */
    async getTree(requestParameters: GetTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeResponse> {
        const response = await this.getTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the tree linked to the given sensor. Returns 404 if the sensor or its associated tree does not exist.
     * Get the tree associated with a sensor
     */
    async getTreeBySensorRaw(requestParameters: GetTreeBySensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeResponse>> {
        if (requestParameters['sensorId'] == null) {
            throw new runtime.RequiredError(
                'sensorId',
                'Required parameter "sensorId" was null or undefined when calling getTreeBySensor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/sensors/{sensor_id}/tree`;
        urlPath = urlPath.replace(`{${"sensor_id"}}`, encodeURIComponent(String(requestParameters['sensorId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the tree linked to the given sensor. Returns 404 if the sensor or its associated tree does not exist.
     * Get the tree associated with a sensor
     */
    async getTreeBySensor(requestParameters: GetTreeBySensorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeResponse> {
        const response = await this.getTreeBySensorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of distinct planting years across all trees.
     * List distinct planting years
     */
    async listPlantingYearsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/trees/planting-years`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns a list of distinct planting years across all trees.
     * List distinct planting years
     */
    async listPlantingYears(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.listPlantingYearsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns minimal tree markers (id, lat, lng, watering_status, number, has_sensor) intersecting the given bounding box. Optional filter parameters narrow the result. Not paginated — the bounding box bounds the result.
     * List tree markers in a bounding box
     */
    async listTreeMarkersRaw(requestParameters: ListTreeMarkersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeMarkerListResponse>> {
        if (requestParameters['bbox'] == null) {
            throw new runtime.RequiredError(
                'bbox',
                'Required parameter "bbox" was null or undefined when calling listTreeMarkers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['hasCluster'] != null) {
            queryParameters['has_cluster'] = requestParameters['hasCluster'];
        }

        if (requestParameters['plantingYear'] != null) {
            queryParameters['planting_year'] = requestParameters['plantingYear'];
        }

        if (requestParameters['wateringStatus'] != null) {
            queryParameters['watering_status'] = requestParameters['wateringStatus'];
        }

        if (requestParameters['organizationId'] != null) {
            queryParameters['organization_id'] = requestParameters['organizationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/trees/markers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeMarkerListResponseFromJSON(jsonValue));
    }

    /**
     * Returns minimal tree markers (id, lat, lng, watering_status, number, has_sensor) intersecting the given bounding box. Optional filter parameters narrow the result. Not paginated — the bounding box bounds the result.
     * List tree markers in a bounding box
     */
    async listTreeMarkers(requestParameters: ListTreeMarkersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeMarkerListResponse> {
        const response = await this.listTreeMarkersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of all trees with their associated sensor data. Optional `q` parameter case-insensitively filters by tree number or species. Optional filter parameters (watering_status, has_cluster, planting_year) narrow the result; array parameters are repeatable.
     * List all trees
     */
    async listTreesRaw(requestParameters: ListTreesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseTreeResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['wateringStatus'] != null) {
            queryParameters['watering_status'] = requestParameters['wateringStatus'];
        }

        if (requestParameters['hasCluster'] != null) {
            queryParameters['has_cluster'] = requestParameters['hasCluster'];
        }

        if (requestParameters['plantingYear'] != null) {
            queryParameters['planting_year'] = requestParameters['plantingYear'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/trees`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseTreeResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of all trees with their associated sensor data. Optional `q` parameter case-insensitively filters by tree number or species. Optional filter parameters (watering_status, has_cluster, planting_year) narrow the result; array parameters are repeatable.
     * List all trees
     */
    async listTrees(requestParameters: ListTreesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseTreeResponse> {
        const response = await this.listTreesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Moves a clusterless tree (and any attached sensor) to a different owning organization. Requires `tree:update` in both the source and target organization.
     * Transfer a tree\'s ownership to another organization
     */
    async transferTreeRaw(requestParameters: TransferTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling transferTree().'
            );
        }

        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transferTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/trees/{tree_id}/organization`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Moves a clusterless tree (and any attached sensor) to a different owning organization. Requires `tree:update` in both the source and target organization.
     * Transfer a tree\'s ownership to another organization
     */
    async transferTree(requestParameters: TransferTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferTreeRaw(requestParameters, initOverrides);
    }

    /**
     * Performs a full replacement update of a tree by its ID.
     * Update a tree
     */
    async updateTreeRaw(requestParameters: UpdateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeResponse>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling updateTree().'
            );
        }

        if (requestParameters['treeUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'treeUpdateRequest',
                'Required parameter "treeUpdateRequest" was null or undefined when calling updateTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/trees/{tree_id}`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TreeUpdateRequestToJSON(requestParameters['treeUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeResponseFromJSON(jsonValue));
    }

    /**
     * Performs a full replacement update of a tree by its ID.
     * Update a tree
     */
    async updateTree(requestParameters: UpdateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeResponse> {
        const response = await this.updateTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
