/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClusterBoundaryListResponse,
  ClusterMarkerListResponse,
  ClusterStatisticsResponse,
  ErrorBody,
  ListResponseTreeClusterInListResponse,
  SoilCondition,
  SoilMoistureSeriesResponse,
  TransferRequest,
  TreeClusterCreateRequest,
  TreeClusterResponse,
  TreeClusterUpdateRequest,
  WateringStatus,
} from '../models/index';
import {
    ClusterBoundaryListResponseFromJSON,
    ClusterBoundaryListResponseToJSON,
    ClusterMarkerListResponseFromJSON,
    ClusterMarkerListResponseToJSON,
    ClusterStatisticsResponseFromJSON,
    ClusterStatisticsResponseToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListResponseTreeClusterInListResponseFromJSON,
    ListResponseTreeClusterInListResponseToJSON,
    SoilConditionFromJSON,
    SoilConditionToJSON,
    SoilMoistureSeriesResponseFromJSON,
    SoilMoistureSeriesResponseToJSON,
    TransferRequestFromJSON,
    TransferRequestToJSON,
    TreeClusterCreateRequestFromJSON,
    TreeClusterCreateRequestToJSON,
    TreeClusterResponseFromJSON,
    TreeClusterResponseToJSON,
    TreeClusterUpdateRequestFromJSON,
    TreeClusterUpdateRequestToJSON,
    WateringStatusFromJSON,
    WateringStatusToJSON,
} from '../models/index';

export interface CreateClusterRequest {
    treeClusterCreateRequest: TreeClusterCreateRequest;
}

export interface DeleteClusterRequest {
    clusterId: string;
}

export interface GetClusterRequest {
    clusterId: string;
}

export interface GetClusterSoilMoistureRequest {
    clusterId: string;
    from?: Date | null;
    to?: Date | null;
    bucket?: string | null;
}

export interface ListClustersRequest {
    page?: number;
    perPage?: number;
    wateringStatus?: Array<WateringStatus>;
    region?: Array<string>;
    soilCondition?: Array<SoilCondition>;
    query?: string | null;
    sort?: string | null;
    order?: string | null;
}

export interface TransferClusterRequest {
    clusterId: string;
    transferRequest: TransferRequest;
}

export interface UpdateClusterRequest {
    clusterId: string;
    treeClusterUpdateRequest: TreeClusterUpdateRequest;
}

/**
 * 
 */
export class TreeClustersApi extends runtime.BaseAPI {

    /**
     * Creates a new tree cluster with the given properties and returns the created resource.
     * Create a tree cluster
     */
    async createClusterRaw(requestParameters: CreateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeClusterResponse>> {
        if (requestParameters['treeClusterCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'treeClusterCreateRequest',
                'Required parameter "treeClusterCreateRequest" was null or undefined when calling createCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TreeClusterCreateRequestToJSON(requestParameters['treeClusterCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeClusterResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new tree cluster with the given properties and returns the created resource.
     * Create a tree cluster
     */
    async createCluster(requestParameters: CreateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeClusterResponse> {
        const response = await this.createClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a tree cluster identified by its ID.
     * Delete a tree cluster
     */
    async deleteClusterRaw(requestParameters: DeleteClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling deleteCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a tree cluster identified by its ID.
     * Delete a tree cluster
     */
    async deleteCluster(requestParameters: DeleteClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteClusterRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single tree cluster by its unique identifier, including fully resolved tree objects.
     * Get a tree cluster
     */
    async getClusterRaw(requestParameters: GetClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeClusterResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling getCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeClusterResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single tree cluster by its unique identifier, including fully resolved tree objects.
     * Get a tree cluster
     */
    async getCluster(requestParameters: GetClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeClusterResponse> {
        const response = await this.getClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aggregates volumetric soil-moisture readings (mean/min/max per probe depth and time bucket) across all sensors of the cluster, with per-depth stress thresholds derived from the cluster\'s soil condition and the cluster\'s finished watering runs.
     * Bucketed soil-moisture series for a cluster
     */
    async getClusterSoilMoistureRaw(requestParameters: GetClusterSoilMoistureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SoilMoistureSeriesResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling getClusterSoilMoisture().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}/soil-moisture`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SoilMoistureSeriesResponseFromJSON(jsonValue));
    }

    /**
     * Aggregates volumetric soil-moisture readings (mean/min/max per probe depth and time bucket) across all sensors of the cluster, with per-depth stress thresholds derived from the cluster\'s soil condition and the cluster\'s finished watering runs.
     * Bucketed soil-moisture series for a cluster
     */
    async getClusterSoilMoisture(requestParameters: GetClusterSoilMoistureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SoilMoistureSeriesResponse> {
        const response = await this.getClusterSoilMoistureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Counts of non-archived clusters per watering status, plus total clusters and total trees in clusters.
     * Cluster statistics
     */
    async getClusterStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterStatisticsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/statistics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterStatisticsResponseFromJSON(jsonValue));
    }

    /**
     * Counts of non-archived clusters per watering status, plus total clusters and total trees in clusters.
     * Cluster statistics
     */
    async getClusterStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterStatisticsResponse> {
        const response = await this.getClusterStatisticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a convex-hull boundary polygon (GeoJSON, buffered by a fixed margin in meters) around the trees of each non-archived cluster. Not paginated.
     * List cluster boundaries
     */
    async listClusterBoundariesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBoundaryListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/boundaries`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBoundaryListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a convex-hull boundary polygon (GeoJSON, buffered by a fixed margin in meters) around the trees of each non-archived cluster. Not paginated.
     * List cluster boundaries
     */
    async listClusterBoundaries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBoundaryListResponse> {
        const response = await this.listClusterBoundariesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns lightweight markers (id, name, lat, lng, status, tree_count) for all non-archived clusters with a centroid. Not paginated.
     * List cluster markers
     */
    async listClusterMarkersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterMarkerListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/markers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterMarkerListResponseFromJSON(jsonValue));
    }

    /**
     * Returns lightweight markers (id, name, lat, lng, status, tree_count) for all non-archived clusters with a centroid. Not paginated.
     * List cluster markers
     */
    async listClusterMarkers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterMarkerListResponse> {
        const response = await this.listClusterMarkersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of all tree clusters with a compact representation including region info. Optional filter parameters (watering_status, region) narrow the result; array parameters are repeatable.
     * List all tree clusters
     */
    async listClustersRaw(requestParameters: ListClustersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseTreeClusterInListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['wateringStatus'] != null) {
            queryParameters['watering_status'] = requestParameters['wateringStatus'];
        }

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['soilCondition'] != null) {
            queryParameters['soil_condition'] = requestParameters['soilCondition'];
        }

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseTreeClusterInListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of all tree clusters with a compact representation including region info. Optional filter parameters (watering_status, region) narrow the result; array parameters are repeatable.
     * List all tree clusters
     */
    async listClusters(requestParameters: ListClustersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseTreeClusterInListResponse> {
        const response = await this.listClustersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Moves the cluster, its member trees, and their attached sensors to a different owning organization in one operation. Requires `tree_cluster:update` in both the source and target organization.
     * Transfer a cluster\'s ownership to another organization
     */
    async transferClusterRaw(requestParameters: TransferClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling transferCluster().'
            );
        }

        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transferCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters/{cluster_id}/organization`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Moves the cluster, its member trees, and their attached sensors to a different owning organization in one operation. Requires `tree_cluster:update` in both the source and target organization.
     * Transfer a cluster\'s ownership to another organization
     */
    async transferCluster(requestParameters: TransferClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferClusterRaw(requestParameters, initOverrides);
    }

    /**
     * Updates an existing tree cluster identified by its ID and returns the updated resource.
     * Update a tree cluster
     */
    async updateClusterRaw(requestParameters: UpdateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeClusterResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling updateCluster().'
            );
        }

        if (requestParameters['treeClusterUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'treeClusterUpdateRequest',
                'Required parameter "treeClusterUpdateRequest" was null or undefined when calling updateCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters/{cluster_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TreeClusterUpdateRequestToJSON(requestParameters['treeClusterUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeClusterResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing tree cluster identified by its ID and returns the updated resource.
     * Update a tree cluster
     */
    async updateCluster(requestParameters: UpdateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeClusterResponse> {
        const response = await this.updateClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
