/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorBody,
  ListResponseVehicleResponse,
  TransferRequest,
  VehicleCreateRequest,
  VehicleResponse,
  VehicleUpdateRequest,
} from '../models/index';
import {
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    ListResponseVehicleResponseFromJSON,
    ListResponseVehicleResponseToJSON,
    TransferRequestFromJSON,
    TransferRequestToJSON,
    VehicleCreateRequestFromJSON,
    VehicleCreateRequestToJSON,
    VehicleResponseFromJSON,
    VehicleResponseToJSON,
    VehicleUpdateRequestFromJSON,
    VehicleUpdateRequestToJSON,
} from '../models/index';

export interface ArchiveVehicleRequest {
    vehicleId: string;
}

export interface CreateVehicleRequest {
    vehicleCreateRequest: VehicleCreateRequest;
}

export interface DeleteVehicleRequest {
    vehicleId: string;
}

export interface GetVehicleRequest {
    vehicleId: string;
}

export interface GetVehicleByPlateRequest {
    plate: string;
}

export interface ListArchivedVehiclesRequest {
    page?: number;
    perPage?: number;
}

export interface ListVehiclesRequest {
    page?: number;
    perPage?: number;
}

export interface TransferVehicleRequest {
    vehicleId: string;
    transferRequest: TransferRequest;
}

export interface UpdateVehicleRequest {
    vehicleId: string;
    vehicleUpdateRequest: VehicleUpdateRequest;
}

/**
 * 
 */
export class VehiclesApi extends runtime.BaseAPI {

    /**
     * Moves a vehicle to the archived state.
     * Archive a vehicle
     */
    async archiveVehicleRaw(requestParameters: ArchiveVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['vehicleId'] == null) {
            throw new runtime.RequiredError(
                'vehicleId',
                'Required parameter "vehicleId" was null or undefined when calling archiveVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vehicles/archived/{vehicle_id}`;
        urlPath = urlPath.replace(`{${"vehicle_id"}}`, encodeURIComponent(String(requestParameters['vehicleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Moves a vehicle to the archived state.
     * Archive a vehicle
     */
    async archiveVehicle(requestParameters: ArchiveVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveVehicleRaw(requestParameters, initOverrides);
    }

    /**
     * Registers a new watering vehicle.
     * Create a vehicle
     */
    async createVehicleRaw(requestParameters: CreateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VehicleResponse>> {
        if (requestParameters['vehicleCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'vehicleCreateRequest',
                'Required parameter "vehicleCreateRequest" was null or undefined when calling createVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/vehicles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleCreateRequestToJSON(requestParameters['vehicleCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleResponseFromJSON(jsonValue));
    }

    /**
     * Registers a new watering vehicle.
     * Create a vehicle
     */
    async createVehicle(requestParameters: CreateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VehicleResponse> {
        const response = await this.createVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes a vehicle.
     * Delete a vehicle
     */
    async deleteVehicleRaw(requestParameters: DeleteVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['vehicleId'] == null) {
            throw new runtime.RequiredError(
                'vehicleId',
                'Required parameter "vehicleId" was null or undefined when calling deleteVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vehicles/{vehicle_id}`;
        urlPath = urlPath.replace(`{${"vehicle_id"}}`, encodeURIComponent(String(requestParameters['vehicleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a vehicle.
     * Delete a vehicle
     */
    async deleteVehicle(requestParameters: DeleteVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVehicleRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single vehicle by its ID.
     * Get a vehicle
     */
    async getVehicleRaw(requestParameters: GetVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VehicleResponse>> {
        if (requestParameters['vehicleId'] == null) {
            throw new runtime.RequiredError(
                'vehicleId',
                'Required parameter "vehicleId" was null or undefined when calling getVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vehicles/{vehicle_id}`;
        urlPath = urlPath.replace(`{${"vehicle_id"}}`, encodeURIComponent(String(requestParameters['vehicleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single vehicle by its ID.
     * Get a vehicle
     */
    async getVehicle(requestParameters: GetVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VehicleResponse> {
        const response = await this.getVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Looks up a vehicle by its license plate number.
     * Get vehicle by plate
     */
    async getVehicleByPlateRaw(requestParameters: GetVehicleByPlateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VehicleResponse>> {
        if (requestParameters['plate'] == null) {
            throw new runtime.RequiredError(
                'plate',
                'Required parameter "plate" was null or undefined when calling getVehicleByPlate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vehicles/plate/{plate}`;
        urlPath = urlPath.replace(`{${"plate"}}`, encodeURIComponent(String(requestParameters['plate'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleResponseFromJSON(jsonValue));
    }

    /**
     * Looks up a vehicle by its license plate number.
     * Get vehicle by plate
     */
    async getVehicleByPlate(requestParameters: GetVehicleByPlateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VehicleResponse> {
        const response = await this.getVehicleByPlateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of decommissioned vehicles.
     * List archived vehicles
     */
    async listArchivedVehiclesRaw(requestParameters: ListArchivedVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseVehicleResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vehicles/archived`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseVehicleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of decommissioned vehicles.
     * List archived vehicles
     */
    async listArchivedVehicles(requestParameters: ListArchivedVehiclesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseVehicleResponse> {
        const response = await this.listArchivedVehiclesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of active vehicles.
     * List all vehicles
     */
    async listVehiclesRaw(requestParameters: ListVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseVehicleResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/vehicles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseVehicleResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of active vehicles.
     * List all vehicles
     */
    async listVehicles(requestParameters: ListVehiclesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseVehicleResponse> {
        const response = await this.listVehiclesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Moves a vehicle to a different owning organization. Requires `vehicle:update` in both the source and target organization.
     * Transfer a vehicle\'s ownership to another organization
     */
    async transferVehicleRaw(requestParameters: TransferVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['vehicleId'] == null) {
            throw new runtime.RequiredError(
                'vehicleId',
                'Required parameter "vehicleId" was null or undefined when calling transferVehicle().'
            );
        }

        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transferVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/vehicles/{vehicle_id}/organization`;
        urlPath = urlPath.replace(`{${"vehicle_id"}}`, encodeURIComponent(String(requestParameters['vehicleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Moves a vehicle to a different owning organization. Requires `vehicle:update` in both the source and target organization.
     * Transfer a vehicle\'s ownership to another organization
     */
    async transferVehicle(requestParameters: TransferVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferVehicleRaw(requestParameters, initOverrides);
    }

    /**
     * Updates the details of an existing vehicle.
     * Update a vehicle
     */
    async updateVehicleRaw(requestParameters: UpdateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VehicleResponse>> {
        if (requestParameters['vehicleId'] == null) {
            throw new runtime.RequiredError(
                'vehicleId',
                'Required parameter "vehicleId" was null or undefined when calling updateVehicle().'
            );
        }

        if (requestParameters['vehicleUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'vehicleUpdateRequest',
                'Required parameter "vehicleUpdateRequest" was null or undefined when calling updateVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/vehicles/{vehicle_id}`;
        urlPath = urlPath.replace(`{${"vehicle_id"}}`, encodeURIComponent(String(requestParameters['vehicleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleUpdateRequestToJSON(requestParameters['vehicleUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleResponseFromJSON(jsonValue));
    }

    /**
     * Updates the details of an existing vehicle.
     * Update a vehicle
     */
    async updateVehicle(requestParameters: UpdateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VehicleResponse> {
        const response = await this.updateVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
